import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { QUESTIONS, INTAKE_VERSION, EVENT_QUESTION_IDS, wording } from '../src/lib/athleteBosV1/intake.js';
import { FIXTURES, getFixture, filterAudience } from '../api/engine/athleteBosV1/fixtures.js';
import { normalizeIntake, stateHash, validateInterpretation, checkCustomerText, resolveFutureReadiness, deriveProjectionContracts } from '../api/engine/athleteBosV1/contract.js';
import { AthleteLocalStore } from '../api/engine/athleteBosV1/localStore.js';
import { generationIdentity, validateSchema } from '../api/engine/athleteBosV1/generation.js';
import { createLocalSingleFlightCoordinator } from '../api/engine/newBosProductionReadinessV1/singleFlight.js';
const source = getFixture('synthetic-athlete-nia');
const sha256 = value => crypto.createHash('sha256').update(value).digest('hex');
const snapshot = () => ({ metadata: { fictional: true, assent: true, ageBand: '14–17' }, responses: Object.fromEntries(QUESTIONS.map(q => [q.id, { status: 'UNKNOWN', text: '', selected: [] }])) });
async function store() { const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'athlete-bos-unit-')); const s = new AthleteLocalStore(dir); await s.init(); return s; }
const PACKAGED_MIKA_ARTIFACT = new URL('../server/athleteLivingConsultOneShotV1/fixtures/mika-bos-v1.json', import.meta.url);
const PACKAGED_MIKA_ARTIFACT_SHA256 = '21dad9299058dbdaa935bc89e66a0d3126d9c845c18b599bfa6afda3cd1ce6d0';
async function packagedMikaArtifactAndSource() {
  const bytes = await fs.readFile(PACKAGED_MIKA_ARTIFACT);
  assert.equal(sha256(bytes), PACKAGED_MIKA_ARTIFACT_SHA256);
  const artifact = JSON.parse(bytes);
  assert.equal(artifact.contract, 'athlete-bos-synthetic-v1-contract-new-bos-parity-v12');
  assert.equal(artifact.subject.id, 'synthetic-athlete-parity');
  const fixtureSource = {
    ...artifact.subject,
    relationshipId: artifact.identity_context.relationship_id,
    synthetic: true,
    revision: 1,
    capturedAt: artifact.createdAt,
    intakeVersion: INTAKE_VERSION,
    lifeHopes: structuredClone(artifact.lifeHopes),
    evidence: structuredClone(artifact.evidence),
    corrections: [],
    responses: {},
  };
  return { artifact, fixtureSource };
}

test('Founder-review composition is 20 / 14 narrative / 6 structured, with both dream variants', () => { assert.equal(QUESTIONS.length, 20); assert.equal(QUESTIONS.filter(q => q.kind === 'narrative').length, 14); assert.equal(QUESTIONS.filter(q => q.kind === 'structured').length, 6); assert.equal(new Set(QUESTIONS.map(q => q.id)).size, 20); assert.equal(INTAKE_VERSION, 'athlete-intake-v1.21-new-bos-parity-20260905'); assert.match(wording(QUESTIONS[0], '14–17'), /life beyond sport/); assert.match(wording(QUESTIONS[0], '18–20'), /life you want to build/); });
test('the v1.21 intake rejects unknown fields and narrative options while preserving a structured answer’s optional own words', () => { const unknown = snapshot(); unknown.responses.C21 = { status: 'ANSWERED', text: 'not a governed question' }; assert.throws(() => normalizeIntake(unknown, null), /UNKNOWN_RESPONSE_ID/); const narrativeOptions = snapshot(); narrativeOptions.responses.C02 = { status: 'ANSWERED', text: 'I want to enjoy practice.', selected: ['invented option'] }; assert.throws(() => normalizeIntake(narrativeOptions, null), /NARRATIVE_OPTION_NOT_ALLOWED/); const unknownField = snapshot(); unknownField.responses.C02 = { status: 'ANSWERED', text: 'I want to enjoy practice.', action: 'publish' }; assert.throws(() => normalizeIntake(unknownField, null), /RESPONSE_FIELD_NOT_ALLOWED/); const structuredWords = snapshot(); structuredWords.responses.C02 = { status: 'ANSWERED', text: 'I want to enjoy practice.' }; structuredWords.responses.C03 = { status: 'ANSWERED', selected: ['Mine'], text: 'That is my own goal.' }; const normalized = normalizeIntake(structuredWords, null); assert.equal(normalized.responses.C03.text, 'That is my own goal.'); assert.equal(normalized.evidence.find(({ id }) => id === 'C03').text, 'That is my own goal. | Mine'); });
test('the current source identifies v1.21 and cannot masquerade as historical v1.20', async () => { const currentSource = await fs.readFile(new URL('../src/lib/athleteBosV1/intake.js', import.meta.url)); assert.equal(sha256(currentSource), '817fae144a573bc858684f40c732c99c0a520daf449e460af74122d6b6e50cf5'); assert.match(currentSource.toString('utf8'), /athlete-intake-v1\.21-new-bos-parity-20260905/); assert.match(currentSource.toString('utf8'), /question\('C19', 'What people may miss'/); assert.doesNotMatch(currentSource.toString('utf8'), /Check this understanding|What fits, and what should MORE change/); assert.equal(QUESTIONS.filter(q => q.kind === 'narrative').length, 14); assert.equal(QUESTIONS.filter(q => q.kind === 'structured').length, 6); assert.match(QUESTIONS.find(({ id }) => id === 'C19').text, /label that does not fit/); });
test('same eight original subjects retain NOT_ASKED dreams, not fabricated unknown answers', () => { assert.equal(FIXTURES.length, 8); assert.ok(FIXTURES.every(f => f.lifeHopes.status === 'NOT_ASKED' && !f.lifeHopes.evidenceIds.length)); });
test('unknown/deferred/declined remain different and discard hidden answer payloads before model-visible storage', () => { const s = snapshot(); s.responses.C02 = { status: 'DECLINED', text: 'hidden declined content', binding: { sourceId: 'C04', label: 'hidden binding' }, conditions: ['hidden condition'], eventTime: '2026-09-05' }; s.responses.C04 = { status: 'DEFERRED', text: 'hidden deferred content', eventRelation: { kind: 'same', sourceId: 'C05' } }; s.responses.C18 = { status: 'UNKNOWN', selected: ['instructions from a qualified professional'] }; const n = normalizeIntake(s, null); assert.equal(n.responses.C01.status, 'UNKNOWN'); assert.equal(n.responses.C02.status, 'DECLINED'); assert.equal(n.responses.C04.status, 'DEFERRED'); assert.equal(n.responses.C18.status, 'UNKNOWN'); for (const id of ['C01', 'C02', 'C04', 'C18']) { assert.equal(n.responses[id].text, ''); assert.deepEqual(n.responses[id].selected, []); assert.equal(n.responses[id].binding, null); assert.equal(n.responses[id].eventRelation, null); assert.deepEqual(n.responses[id].conditions, []); assert.equal(n.responses[id].eventTime, null); } assert.equal(n.evidence.length, 0); for (const hidden of ['hidden declined content', 'hidden deferred content', 'hidden binding', 'hidden condition', 'qualified professional']) assert.ok(!JSON.stringify(n).includes(hidden)); assert.ok(!JSON.stringify(n).includes('score')); });
test('unasked and explicitly uncertain dreams are different governed states', () => { const s = snapshot(); delete s.responses.C01; assert.equal(normalizeIntake(s, null).lifeHopes.status, 'NOT_ASKED'); s.responses.C01 = { status: 'UNKNOWN' }; assert.equal(normalizeIntake(s, null).lifeHopes.status, 'UNKNOWN'); });
test('life answer root is C01 only, never another goal', () => { const s = snapshot(); s.responses.C02 = { status: 'ANSWERED', text: 'I want to win.' }; assert.deepEqual(normalizeIntake(s, null).lifeHopes.evidenceIds, []); s.responses.C01 = { status: 'ANSWERED', text: 'A life with friends and time outside. I am unsure about work.' }; assert.deepEqual(normalizeIntake(s, null).lifeHopes.evidenceIds, ['C01']); });
test('question version/exact wording, actor, assistance, permission and unknown event date retained', () => { const s = snapshot(); s.metadata.assistance = 'dictation'; s.responses.C04 = { status: 'ANSWERED', text: 'I packed my bag.' }; const n = normalizeIntake(s, null); assert.equal(n.responses.C04.questionVersion, INTAKE_VERSION); assert.equal(n.responses.C04.wording, QUESTIONS[3].text); assert.equal(n.responses.C04.assistance, 'dictation'); assert.equal(n.responses.C04.eventTime, null); assert.equal(n.responses.C04.permission.audience, 'private'); });
test('P0 synthetic assent required; real data marker cannot open this intake', () => { for (const change of [{ fictional: false }, { assent: false }, { ageBand: 'adult' }]) { const s = snapshot(); Object.assign(s.metadata, change); assert.throws(() => normalizeIntake(s, null)); } });
test('C15 cannot bind an invented event; C16 must bind an answered source or an explicitly new task', () => { const s = snapshot(); s.responses.C15 = { status: 'ANSWERED', selected: ['Mostly usual'], binding: { sourceId: 'invented', label: 'a final' } }; assert.throws(() => normalizeIntake(s, null), /EXACT_EVENT/); delete s.responses.C15; s.responses.C16 = { status: 'ANSWERED', selected: ['Very sure'], binding: { sourceId: 'invented', label: 'a task' } }; assert.throws(() => normalizeIntake(s, null), /TASK_BINDING/); s.responses.C16.binding = { sourceId: 'new-task', label: 'a new task I named' }; assert.equal(normalizeIntake(s, null).evidence.find(({ id }) => id === 'C16').rootId, 'C16'); s.responses.C04 = { status: 'ANSWERED', text: 'I chose to pack the night before.' }; s.responses.C16.binding = { sourceId: 'C04', label: 'packing before practice' }; assert.equal(normalizeIntake(s, null).evidence.find(({ id }) => id === 'C16').rootId, 'C04'); });
test('C04–C14 may identify one transitive shared event root, preventing pseudo-corroboration', () => { const s = snapshot(); s.responses.C04 = { status: 'ANSWERED', text: 'I chose to pack the night before.', eventRelation: { kind: 'new' } }; s.responses.C05 = { status: 'ANSWERED', text: 'That same night I finished packing.', eventRelation: { kind: 'same', sourceId: 'C04' } }; s.responses.C06 = { status: 'ANSWERED', text: 'I learned the packing order in that moment.', eventRelation: { kind: 'same', sourceId: 'C05' } }; s.responses.C15 = { status: 'ANSWERED', selected: ['Mostly usual'], binding: { sourceId: 'C06', label: s.responses.C06.text } }; const n = normalizeIntake(s, null); assert.equal(n.evidence.find(({ id }) => id === 'C04').rootId, 'C04'); assert.equal(n.evidence.find(({ id }) => id === 'C05').rootId, 'C04'); assert.equal(n.evidence.find(({ id }) => id === 'C06').rootId, 'C04'); assert.equal(n.evidence.find(({ id }) => id === 'C15').rootId, 'C04'); assert.deepEqual(n.responses.C05.eventRelation, { kind: 'same', sourceId: 'C04' }); assert.deepEqual(EVENT_QUESTION_IDS, ['C04', 'C05', 'C06', 'C07', 'C08', 'C09', 'C10', 'C11', 'C12', 'C13', 'C14']); s.responses.C04.eventRelation = { kind: 'same', sourceId: 'C05' }; assert.throws(() => normalizeIntake(s, null), /EVENT_RELATION_SOURCE_INVALID/); });
test('C19 is a direct athlete account about a misfit label, not a synthetic recognition review', () => { const s = snapshot(); s.responses.C19 = { status: 'ANSWERED', text: 'People call me quiet, but I ask questions one-on-one after practice.' }; const n = normalizeIntake(s, null); const evidence = n.evidence.find(({ id }) => id === 'C19'); assert.equal(evidence.rootId, 'C19'); assert.equal(evidence.kind, 'self_report'); assert.equal(n.responses.C19.binding, null); assert.match(evidence.text, /one-on-one/); });
test('exclusive unknown/no-support selections do not coexist with asserted supports', () => { const s = snapshot(); s.responses.C18 = { status: 'ANSWERED', selected: ['unsure', 'practical help or access'] }; assert.throws(() => normalizeIntake(s, null), /EXCLUSIVE/); });
test('C20 exploration/keep/pause creates no commitment or intervention', () => { const s = snapshot(); s.responses.C20 = { status: 'ANSWERED', selected: ['Keep what is working'] }; const n = normalizeIntake(s, null); assert.equal(n.commitments, undefined); assert.equal(n.interventions, undefined); });
test('coach projection has only the exact authorized shared object, no private object existence', () => { const p = filterAudience(getFixture('synthetic-athlete-mara'), 'coach', '2026-09-04T00:00:00Z'); assert.deepEqual(p.evidence.map(e => e.id), ['E05']); for (const forbidden of ['home responsibility', 'called passive', 'E01', 'E03', 'E04']) assert.ok(!JSON.stringify(p).includes(forbidden)); assert.deepEqual(p.responses, {}); });
test('grant expiry refuses projection; unrelated coach/guardian cannot retrieve', () => { assert.throws(() => filterAudience(getFixture('synthetic-athlete-mara'), 'coach', '2026-10-01T00:00:00Z')); assert.throws(() => filterAudience(source, 'coach')); assert.throws(() => filterAudience(source, 'guardian')); });
test('real customer IDs, traversal and Patricia cannot resolve to storage', async () => { const s = await store(); for (const id of ['mm-20260708-dsst020z', 'mm-real', '../customer', 'synthetic-athlete-unknown']) await assert.rejects(s.subject(id)); });
test('identity changes on evidence, permission/audience and correction; same state stays stable', () => { const id = generationIdentity(source, 'athlete'); assert.equal(id, generationIdentity(structuredClone(source), 'athlete')); assert.notEqual(id, generationIdentity(source, 'coach')); const next = structuredClone(source); next.revision++; assert.notEqual(id, generationIdentity(next, 'athlete')); });
test('existing BOS single-flight deduplicates overlapping generation work', async () => { const f = createLocalSingleFlightCoordinator(); let calls = 0; const run = () => f.run('same', async () => { calls++; await Promise.resolve(); return 9; }); assert.deepEqual(await Promise.all([run(), run()]), [9, 9]); assert.equal(calls, 1); });
test('local draft token, stale refusal and idempotency survive disk restart', async () => { const s = await store(); const first = await s.draft('create', { snapshot: snapshot() }); await assert.rejects(s.draft('resume', { draft_id: first.draft_id }, 'wrong')); const next = { draft_id: first.draft_id, base_revision: 1, mutation_id: 'same', snapshot: snapshot() }; const updated = await s.draft('update', next, first.resume_token); assert.equal(updated.revision, 2); assert.equal((await s.draft('update', next, first.resume_token)).revision, 2); await assert.rejects(s.draft('update', { ...next, mutation_id: 'other' }, first.resume_token), /STALE/); const reboot = new AthleteLocalStore(s.root); assert.equal((await reboot.draft('resume', { draft_id: first.draft_id }, first.resume_token)).revision, 2); });
test('required life invitation cannot silently disappear', async () => { const s = await store(); const input = snapshot(); delete input.responses.C01; const d = await s.draft('create', { snapshot: input }); await assert.rejects(s.submitIntake(d.draft_id, d.resume_token, d.revision), /LIFE_INVITATION/); });
test('first value does not require all 20 answers or skip markers', async () => { const s = await store(); const input = snapshot(); input.responses = { C01: { status: 'UNKNOWN' }, C02: { status: 'ANSWERED', text: 'I want to enjoy practice.' } }; const d = await s.draft('create', { snapshot: input }); const result = await s.submitIntake(d.draft_id, d.resume_token, d.revision); assert.equal(Object.keys(result.responses).length, 2); assert.equal(result.responses.C03, undefined); assert.equal(result.lifeHopes.status, 'UNKNOWN'); });
test('correction is append-only, evidence-bound, preserves the old account, and refuses stale writes', async () => { const s = await store(); await assert.rejects(s.correct(source.id, { sourceHash: stateHash(source), claimId: 'C1', displayedClaim: 'Arrival readiness matters.', reportIdentity: 'synthetic-report-v1', text: 'Packing is fine now. I need to understand the ride.' }), /CORRECTED_CLAIM_EVIDENCE_BINDING_REQUIRED/); const n = await s.correct(source.id, { sourceHash: stateHash(source), claimId: 'C1', displayedClaim: 'Arrival readiness matters.', reportIdentity: 'synthetic-report-v1', claimEvidenceIds: ['E01'], text: 'Packing is fine now. I need to understand the ride.' }); assert.equal(n.revision, 2); assert.equal(n.corrections.length, 1); assert.deepEqual(n.corrections[0].claimEvidenceIds, ['E01']); assert.equal(n.evidence[0].text, source.evidence[0].text); await assert.rejects(s.correct(source.id, { sourceHash: stateHash(source), claimId: 'C1', displayedClaim: 'Old', reportIdentity: 'old', claimEvidenceIds: ['E01'], text: 'stale' }), /STALE/); assert.equal((await new AthleteLocalStore(s.root).subject(source.id)).revision, 2); });
test('a regenerated interpretation cannot silently keep an exact corrected-away claim current', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const corrected = structuredClone(fixtureSource); corrected.corrections = [{ id: 'correction-2', claimId: artifact.plan.claims[0].id, displayedClaim: artifact.plan.claims[0].statement, text: 'That no longer fits.', status: 'athlete_correction_not_third_party_proof' }]; assert.throws(() => validateInterpretation(artifact.plan, corrected, { allowIncompleteArchitecture: true }), /CORRECTED_CLAIM_CANNOT_REMAIN_CURRENT/); });
test('a paraphrase cannot keep the same corrected claim identity current', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const corrected = structuredClone(fixtureSource); corrected.corrections = [{ id: 'correction-2', claimId: artifact.plan.claims[0].id, displayedClaim: artifact.plan.claims[0].statement, text: 'That no longer fits.', status: 'athlete_correction_not_third_party_proof' }]; const paraphrase = structuredClone(artifact.plan); paraphrase.claims[0].statement = `A revised wording of ${artifact.plan.claims[0].statement}`; assert.throws(() => validateInterpretation(paraphrase, corrected, { allowIncompleteArchitecture: true }), /CORRECTED_CLAIM_CANNOT_REMAIN_CURRENT/); });
test('a lightly paraphrased corrected claim cannot evade supersession under a new claim id', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const corrected = structuredClone(fixtureSource); const prior = artifact.plan.claims[0]; corrected.corrections = [{ id: 'correction-3', claimId: prior.id, displayedClaim: prior.statement, text: 'That no longer fits.', status: 'athlete_correction_not_third_party_proof' }]; const renamed = structuredClone(artifact.plan); renamed.claims[0] = { ...renamed.claims[0], id: 'NEW-CLAIM-ID', statement: `${prior.statement.replace(/\.$/u, '')} in this setting.` }; assert.throws(() => validateInterpretation(renamed, corrected, { allowIncompleteArchitecture: true }), /CORRECTED_CLAIM_CANNOT_REMAIN_CURRENT/); });
test('a corrected claim cannot evade supersession by changing both id and wording while silently reusing the same evidence', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const corrected = structuredClone(fixtureSource); const prior = artifact.plan.claims[0]; corrected.corrections = [{ id: 'correction-evidence-bound', claimId: prior.id, displayedClaim: prior.statement, claimEvidenceIds: prior.support.map(({ evidenceId }) => evidenceId), text: 'That account no longer fits.', status: 'athlete_correction_not_third_party_proof' }]; const renamed = structuredClone(artifact.plan); renamed.claims[0] = { ...renamed.claims[0], id: 'NEW-CLAIM-WITH-SAME-SUPPORT', statement: 'A different-sounding conclusion built from the same old account.' }; assert.throws(() => validateInterpretation(renamed, corrected, { allowIncompleteArchitecture: true }), /CORRECTED_CLAIM_CANNOT_REMAIN_CURRENT/); });
test('catastrophic diagnosis, numerical youth scoring, internal evidence mechanics, malformed non-English fragments and secrets fail closed', () => { for (const text of ['You are autistic.', 'Your coachability score is 92.', 'Your personality percentile is 99.', 'This is a bounded baseline.', 'These same-root items establish a pattern.', 'The event root is C04.', 'Your best business role and seat are clear.', 'The athlete named a希望 for the future.', `Bearer ${'abcdefghijklmnopqrstuvwxyz'}`]) assert.throws(() => checkCustomerText(text)); });
test('strict schema rejects invented fields and enum values', () => { const schema = { type: 'object', required: ['kind'], properties: { kind: { type: 'string', enum: ['allowed'] } }, additionalProperties: false }; assert.throws(() => validateSchema({ kind: 'allowed', action: 'send' }, schema)); assert.throws(() => validateSchema({ kind: 'write' }, schema)); });
test('packaged generated evidence references and exact spans remain falsifiable without binding new identity to old artifacts', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const bad = structuredClone(artifact.plan); bad.claims[0].support[0].evidenceId = 'PRIVATE_OTHER_CUSTOMER'; assert.throws(() => validateInterpretation(bad, fixtureSource, { allowIncompleteArchitecture: true }), /SPAN/); const fabricated = structuredClone(artifact.plan); fabricated.claims[0].support[0].exactSpan = 'I want a professional career.'; assert.throws(() => validateInterpretation(fabricated, fixtureSource, { allowIncompleteArchitecture: true }), /SPAN/); });
test('packaged same-root evidence cannot be duplicated into durable-trait corroboration', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const p = structuredClone(artifact.plan); const boundedClaim = p.claims.find(claim => claim.id === 'CF04'); boundedClaim.layer = 'relatively_durable_tendency'; boundedClaim.support.push(structuredClone(boundedClaim.support[0])); assert.throws(() => validateInterpretation(p, fixtureSource, { allowIncompleteArchitecture: true }), /DURABLE_TENDENCY_REQUIRES_FOUR_SEPARATE_EVENTS/); });
test('packaged invented Future goal still stops rather than being hidden as missingness', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const p = structuredClone(artifact.plan); p.futures[0].athleteGoalId = 'someone_else'; assert.throws(() => resolveFutureReadiness(p, fixtureSource), /GOAL_REFERENCE/); });
test('packaged derived Future and suggestion contracts retain scope but never imply acceptance, execution, or outcome', async () => { const { artifact, fixtureSource } = await packagedMikaArtifactAndSource(); const p = deriveProjectionContracts(artifact.plan, fixtureSource, 'athlete', artifact.identity); assert.equal(p.moveSuggestion.acceptanceState, 'NOT_ACCEPTED'); assert.equal(p.moveSuggestion.executionState, 'NOT_RECORDED'); assert.equal(p.moveSuggestion.outcomeState, 'NOT_RECORDED'); assert.equal(p.subjectId, fixtureSource.id); assert.equal(p.relationshipId, fixtureSource.relationshipId); assert.equal(p.futurePaths[0].sourceHash, stateHash(fixtureSource)); assert.ok(!p.allowedActions.includes('accept_intervention')); });
