import test from'node:test';import assert from'node:assert/strict';import{createLearningCandidate,createPrivateCoachArtifact,decideCoachShare,decideLearningCandidate,proposeCoachShare,subscriberVisibleCoachProjection}from'../src/lib/intelligenceFabric/index.js';
const scope={tenant_id:'tenant_synthetic',business_id:'business_synthetic',profile_id:'profile_synthetic'};const privateArtifact=()=>createPrivateCoachArtifact({...scope,coach_session_ref:'session_synthetic',content_ref:'opaque_ref',content_hash:'sha256:synthetic',source_provenance:{source_id:'synthetic'}}).artifact;
test('coach note is private, canonical-ineligible, and learning-ineligible by default',()=>{const a=privateArtifact();assert.equal(a.use_class,'COACH_PRIVATE');assert.equal(a.subscriber_visible,false);assert.equal(a.canonical_state_eligible,false);assert.equal(a.learning_eligible,false);assert.deepEqual(subscriberVisibleCoachProjection([a]),[])});
test('authorized share creates redacted derivative without changing eligibility',()=>{const a=privateArtifact(),p=proposeCoachShare(a,{summary_fields:{summary_code:'SHARED_SYNTHETIC'},proposed_at:'2026-07-21T00:00:00.000Z'}).proposal;const shared=decideCoachShare(a,p,{decision:'AUTHORIZED',authorization:{...scope,actor_type:'HUMAN',actor_ref:'human_synthetic',artifact_id:a.coach_artifact_id,purpose:'SUBSCRIBER_SHARE'},decided_at:'2026-07-21T01:00:00.000Z'}).shared;assert.equal(shared.subscriber_visible,true);assert.equal(shared.canonical_state_eligible,false);assert.equal(shared.learning_eligible,false);assert.doesNotMatch(JSON.stringify(shared),/opaque_ref/);assert.equal(subscriberVisibleCoachProjection([a,shared]).length,1)});
test('rejected, missing-authority, and cross-tenant shares fail safely',()=>{const a=privateArtifact(),p=proposeCoachShare(a,{summary_fields:{code:'x'},proposed_at:'2026-07-21T00:00:00.000Z'}).proposal;assert.equal(decideCoachShare(a,p,{decision:'REJECTED',decided_at:'2026-07-21T01:00:00.000Z'}).shared,null);assert.equal(decideCoachShare(a,p,{decision:'AUTHORIZED',authorization:{actor_type:'SYSTEM'},decided_at:'2026-07-21T01:00:00.000Z'}).ok,false);assert.equal(decideCoachShare(a,{...p,tenant_id:'attacker'},{decision:'REJECTED'}).ok,false)});
const learning=(patch={})=>createLearningCandidate({...scope,source_intervention_id:'intervention_synthetic',source_outcome_ids:['o1','o2'],replication_contexts:['c1','c2'],evidence_quality:.8,privacy_eligible:true,causal_claim_status:'MATCHED_CONTEXT_SUPPORT',generalizability_hypothesis:'Synthetic bounded hypothesis',...patch}).candidate;
test('learning gate blocks privacy, confounding, causal overclaim, and weak replication',()=>{assert.equal(learning({privacy_eligible:false}).status,'BLOCKED_BY_PRIVACY');assert.equal(learning({confounders:[{id:'c'}]}).status,'BLOCKED_BY_CONFOUNDING');assert.equal(learning({causal_claim_status:'EXPERIMENTAL_SUPPORT'}).status,'BLOCKED_BY_CAUSAL_OVERCLAIM');assert.equal(learning({source_outcome_ids:['o1']}).status,'INSUFFICIENT_EVIDENCE')});
test('replicated eligible candidate awaits governance and only bounded experiment may be approved',()=>{const c=learning();assert.equal(c.status,'PENDING_GOVERNANCE');assert.equal(c.universal_rsl_eligible,false);assert.equal(decideLearningCandidate(c,{decision:'APPROVE_BOUNDED_EXPERIMENT',governance:{actor_type:'SYSTEM'},decided_at:'2026-07-21T00:00:00.000Z'}).ok,false);const d=decideLearningCandidate(c,{decision:'APPROVE_BOUNDED_EXPERIMENT',governance:{actor_type:'HUMAN',candidate_id:c.learning_candidate_id,candidate_version:1},decided_at:'2026-07-21T00:00:00.000Z'}).decision;assert.equal(d.status,'APPROVED_FOR_BOUNDED_EXPERIMENT');assert.equal(d.universal_rsl_modified,false)});
test('learning provenance is order independent and rejection/archive remain auditable',()=>{const a=learning(),b=learning({source_outcome_ids:['o2','o1'],replication_contexts:['c2','c1']});assert.equal(a.provenance_hash,b.provenance_hash);assert.equal(decideLearningCandidate(a,{decision:'REJECT',decided_at:'2026-07-21T00:00:00.000Z',reason:'insufficient applicability'}).decision.status,'REJECTED');assert.equal(decideLearningCandidate(a,{decision:'ARCHIVE',decided_at:'2026-07-21T00:00:00.000Z'}).decision.status,'ARCHIVED')});
