import test from 'node:test';
import assert from 'node:assert/strict';
import { createCoachAuthService, createCoachConnectService, InMemoryCoachAuthStore, InMemoryCoachConnectStore } from '../src/lib/intelligenceFabric/index.js';

test('synthetic invitation through governed canonical refresh preserves one Business Engine', () => {
  const scope = { tenant_id: 'tenant_e2e', profile_id: 'profile_e2e', business_id: 'business_e2e', subscriber_id: 'subscriber_e2e' }, at = '2026-07-21T12:00:00.000Z'; let sequence = 0, canonicalEvents = 0;
  const auth = createCoachAuthService({ store: new InMemoryCoachAuthStore(), flags: { coach_auth_enabled: true, account_creation_enabled: true, verification_enabled: true, session_enabled: true, acceptance_context_enabled: true, production_traffic_enabled: false, synthetic_only: true, emergency_disabled: false }, clock: () => at, tokenFactory: () => `e2e-auth-token-${++sequence}-abcdefghijklmnop` });
  const actor = auth.createAccount({ auth_subject_reference: 'provider_e2e_coach', primary_contact_reference: 'contact_e2e_coach', display_name: 'Synthetic E2E Coach' }).actor; auth.changeVerification({ coach_actor_id: actor.coach_actor_id, action: 'BEGIN' }); auth.changeVerification({ coach_actor_id: actor.coach_actor_id, action: 'COMPLETE' }); const authSession = auth.issueSession({ auth_subject_reference: actor.auth_subject_reference });
  const flags = { coach_connect_enabled: true, invitation_enabled: true, qr_enabled: true, relationship_enabled: true, checkout_enabled: true, billing_events_enabled: true, cockpit_enabled: true, session_capture_enabled: true, proposal_routing_enabled: true, subscriber_projection_enabled: true, live_auth_provider_enabled: false, live_billing_enabled: false, live_model_provider_enabled: false, live_voice_video_enabled: false, production_traffic_enabled: false, synthetic_only: true, emergency_disabled: false }, store = new InMemoryCoachConnectStore();
  const service = createCoachConnectService({ store, authService: auth, flags, clock: () => at, tokenFactory: () => `e2e-invite-token-${++sequence}-abcdefghijklmnop`, billingVerifier: (event) => event.signature_valid, canonicalRuntimeAppend: (event) => ({ ok: event.confirmation_status === 'CONFIRMED_AS_PROPOSED', event_id: `governed_event_${++canonicalEvents}` }) });
  const invitation = service.createInvitation({ subscriber_scope: scope, created_by_actor: scope.subscriber_id, idempotency_key: 'e2e_invitation' }), token = decodeURIComponent(invitation.qr_payload.split('invite=')[1]), accepted = service.acceptInvitation({ token, auth_session_id: authSession.session.session_id, auth_session_token: authSession.session_token, subscriber_consent_reference: 'consent_e2e' }), checkout = service.createCheckoutContext({ relationship_id: accepted.relationship.relationship_id, coach_actor_id: actor.coach_actor_id });
  service.processBillingEvent({ event: { event_id: 'e2e_billing_1', type: 'subscription.active', target_status: 'ACTIVE', signature_valid: true, livemode: false, cursor: 1, entitlement_id: checkout.entitlement.entitlement_id, relationship_id: accepted.relationship.relationship_id, coach_actor_id: actor.coach_actor_id, subscriber_scope: scope, product_reference: checkout.entitlement.billing_product_reference, price_reference: checkout.entitlement.billing_price_reference, customer_reference: 'synthetic_customer', subscription_reference: 'synthetic_subscription' } });
  const session = service.createSession({ relationship_id: accepted.relationship.relationship_id, entitlement_id: checkout.entitlement.entitlement_id, subscriber_scope: scope, auth_session_id: authSession.session.session_id, auth_session_token: authSession.session_token, idempotency_key: 'e2e_session' }); service.transitionSession({ session_id: session.session.session_id, action: 'PREPARE' }); service.transitionSession({ session_id: session.session.session_id, action: 'START' }); const judgment = service.recordJudgment({ session_id: session.session.session_id, judgment_class: 'OBSERVATION', protected_summary_reference: 'protected_observation_e2e', coach_confidence: 'MEDIUM', privacy_classification: 'COACH_ATTRIBUTED_SHAREABLE' }); service.transitionSession({ session_id: session.session.session_id, action: 'COMPLETE', structured_artifact: { judgments: [{ class: 'OBSERVATION', protected_summary_reference: 'protected_observation_e2e' }], commitments: [{ status: 'PROPOSED' }], evidence_candidates: [{ status: 'PROPOSED' }] } }); const note = service.createCoachingNote({ judgment_id: judgment.judgment.judgment_id }), promotion = service.createPromotion({ judgment_id: judgment.judgment.judgment_id }), id = promotion.promotion.promotion_record_id;
  service.advancePromotion({ promotion_record_id: id, expected_next_stage: 'STRUCTURED_PROPOSAL' }); service.advancePromotion({ promotion_record_id: id, expected_next_stage: 'BUSINESS_ENGINE_EVALUATION', business_engine_evaluation: 'ACCEPTED_FOR_REVIEW' }); service.advancePromotion({ promotion_record_id: id, expected_next_stage: 'SUBSCRIBER_CONFIRMATION', subscriber_confirmation_state: 'CONFIRMED' }); service.advancePromotion({ promotion_record_id: id, expected_next_stage: 'SUPPORTING_EVIDENCE', supporting_evidence_references: ['synthetic_evidence'] }); service.advancePromotion({ promotion_record_id: id, expected_next_stage: 'OUTCOME_VALIDATION', outcome_validation_references: ['synthetic_outcome'] }); const completed = service.advancePromotion({ promotion_record_id: id, expected_next_stage: 'CANONICAL_BUSINESS_STATE', canonical_event: { event_id: 'candidate_e2e' } });
  const subscriber = service.subscriberProjection({ invitation_id: invitation.invitation.invitation_id, relationship_id: accepted.relationship.relationship_id, entitlement_id: checkout.entitlement.entitlement_id, confirmation_requests: [], governed_updates: [{ promotion_reference: completed.promotion.promotion_record_id }] }), cockpit = service.cockpit({ relationship_id: accepted.relationship.relationship_id, entitlement_id: checkout.entitlement.entitlement_id, requested_scope: scope, auth_session_id: authSession.session.session_id, auth_session_token: authSession.session_token, business_engine_projection: { version: 2, coaching_brief: { summary: 'governed' }, current_one_move: { title: 'Existing One Move' }, living_five_futures: [] } });
  assert.equal(note.coaching_note.confidence_class, 'COACHING_NOTE'); assert.equal(note.coaching_note.missing_evidence, false); assert.equal(completed.promotion.canonical_mutation_reference, 'governed_event_1'); assert.equal(canonicalEvents, 1); assert.equal(subscriber.living_map_refresh_source, 'AUTHORITATIVE_BUSINESS_ENGINE'); assert.equal(subscriber.subscriber_chat_refresh_source, 'AUTHORITATIVE_BUSINESS_ENGINE'); assert.equal(cockpit.projection.canonical_write_capability, false); assert.equal(service.inspect().one_business_engine, true); assert.equal(service.inspect().live_billing, false);
});
