import test from 'node:test';
import assert from 'node:assert/strict';
import { createLiveSessionService, DEFAULT_LIVE_SESSION_FLAGS, InjectedLiveSessionEventStore, InMemoryLiveSessionDriver, SyntheticMediaProvider } from '../src/lib/intelligenceFabric/index.js';

test('synthetic governed live session updates one Business Engine and closes without duplicate promotion', () => {
  const at = '2026-07-22T12:00:00.000Z', scope = { tenant_id: 'tenant_e2e_live', profile_id: 'profile_e2e_live', business_id: 'business_e2e_live', subscriber_id: 'subscriber_e2e_live' };
  const flags = { ...DEFAULT_LIVE_SESSION_FLAGS, live_session_enabled: true, session_establishment_enabled: true, provider_adapter_enabled: true, transcription_enabled: true, extraction_enabled: true, coach_review_enabled: true, engine_evaluation_enabled: true, subscriber_confirmation_enabled: true, projection_refresh_enabled: true, synthetic_proof_enabled: true, emergency_disabled: false };
  const driver = new InMemoryLiveSessionDriver(), eventStore = new InjectedLiveSessionEventStore({ driver }), provider = new SyntheticMediaProvider({ clock: () => at }); let canonicalAppendCount = 0;
  let engine = { business_engine_id: 'engine_e2e_live', version: 7, policy_version: 'policy_live_v1', confidence_reality: { known: [], coaching_notes: [] }, five_futures: { status: 'CURRENT', probability_mutated_by_coach: false }, one_move: { id: 'move_existing', status: 'CURRENT', replaced_by_coach: false } };
  const before = structuredClone(engine);
  const service = createLiveSessionService({ driver, eventStore, provider, flags, parentActivation: () => ({ allowed: true }), authorityEvaluator: () => ({ allowed: true, reason_code: 'AUTHORIZED' }), clock: () => at, canonicalAppend: (event) => { canonicalAppendCount += 1; engine = { ...engine, version: engine.version + 1, confidence_reality: { ...engine.confidence_reality, coaching_notes: [...engine.confidence_reality.coaching_notes, event.source_proposal_id] }, five_futures: { ...engine.five_futures, status: 'RECOMPUTED_FROM_CANONICAL_INPUTS' }, one_move: { ...engine.one_move, status: 'REEVALUATED_FROM_CANONICAL_INPUTS' } }; return { ok: true, event_id: `canonical_e2e_${canonicalAppendCount}`, new_version: engine.version }; } });
  const made = service.createSession({ subscriber_scope: scope, coach_id: 'coach_e2e_live', relationship_id: 'relationship_e2e_live', entitlement_id: 'entitlement_e2e_live', business_engine_id: engine.business_engine_id, created_by: scope.subscriber_id, policy_version: 'policy_live_v1', idempotency_key: 'e2e_live_create' });
  const consent = { PARTICIPATION: 'GRANTED', TRANSCRIPTION: 'GRANTED', RECORDING: 'RESTRICTED', STRUCTURED_EXTRACTION: 'GRANTED', COACH_SHARING: 'GRANTED', BUSINESS_ENGINE_EVALUATION: 'GRANTED', FUTURE_LEARNING: 'RESTRICTED' };
  assert.equal(service.authorizeSession({ session_id: made.session.session_id, authorized_participants: [scope.subscriber_id, 'coach_e2e_live'], consent, retention_policy: 'SYNTHETIC_DELETE_AFTER_PROOF', provider_permissions: ['CONNECT', 'TRANSCRIBE'] }).session.status, 'READY');
  assert.equal(service.connect({ session_id: made.session.session_id }).session.status, 'ACTIVE');
  assert.equal(service.ingestProviderEvent({ session_id: made.session.session_id, type: 'PARTICIPANT_CONNECTED', actor_id: 'coach_e2e_live', actor_role: 'COACH', payload_reference: 'payload_ref_connected', idempotency_key: 'e2e_event_1', expected_sequence: 0 }).status, 'APPENDED');
  assert.equal(service.ingestProviderEvent({ session_id: made.session.session_id, type: 'TRANSCRIPT_SEGMENT_AVAILABLE', actor_id: scope.subscriber_id, actor_role: 'SUBSCRIBER', payload_reference: 'payload_ref_segment', idempotency_key: 'e2e_event_2', expected_sequence: 1 }).status, 'APPENDED');
  const transcript = service.captureTranscript({ transcript_id: 'transcript_e2e_live', session_id: made.session.session_id, status: 'FINALIZED', confidence: 0.98, finalized_at: at, segments: [{ segment_id: 'segment_e2e_live', speaker_id: scope.subscriber_id, content_reference: 'protected_commitment_statement', confidence: 0.98, started_at: at }] }).transcript;
  const artifact = service.extract({ transcript_id: transcript.transcript_id, candidates: [{ artifact_type: 'COMMITMENT', source_spans: ['segment_e2e_live'], speaker_id: scope.subscriber_id, confidence: 0.92, direct_statement: true, content_reference: 'reviewable_commitment_reference' }] }).artifacts[0];
  service.queueReview({ artifact_id: artifact.artifact_id }); const reviewed = service.review({ artifact_id: artifact.artifact_id, action: 'ACCEPT', coach_id: 'coach_e2e_live' }).artifact;
  const proposed = service.propose({ artifact_id: reviewed.artifact_id, business_engine: engine, reason_for_change: 'Subscriber-stated commitment reviewed by coach' }); assert.equal(proposed.confidence_reality_update.destination_class, 'COACHING_NOTES');
  const request = service.requestConfirmation({ proposal_id: proposed.proposal.proposal_id }).confirmation; assert.equal(service.confirm({ confirmation_id: request.confirmation_id, response: 'ACCEPT', subscriber_id: scope.subscriber_id }).confirmation.response_state, 'ACCEPTED');
  const promoted = service.promote({ proposal_id: proposed.proposal.proposal_id, confirmation_id: request.confirmation_id, evidence_references: ['evidence_e2e_live'], outcome_references: ['outcome_e2e_live'], current_business_engine: before, idempotency_key: 'e2e_promotion' }); assert.equal(promoted.ok, true); assert.equal(promoted.promotion.new_business_engine_version, 8);
  assert.equal(service.promote({ proposal_id: proposed.proposal.proposal_id, confirmation_id: request.confirmation_id, evidence_references: ['evidence_e2e_live'], outcome_references: ['outcome_e2e_live'], current_business_engine: before, idempotency_key: 'e2e_promotion' }).status, 'IDEMPOTENT_REPLAY'); assert.equal(canonicalAppendCount, 1);
  const projections = service.refresh({ subscriber_scope: scope, business_engine: engine, previous_version: before.version, reason_for_change: 'Confirmed reviewed live-session commitment', evidence_sources: ['evidence_e2e_live'] }); assert.equal(projections.subscriber_projection.business_engine_version, 8); assert.equal(projections.coach_projection.business_engine_version, 8); assert.equal(projections.coach_projection.canonical_write_capability, false);
  assert.equal(service.close({ session_id: made.session.session_id }).session.status, 'CLOSED');
  assert.deepEqual(before.confidence_reality.coaching_notes, []); assert.equal(engine.confidence_reality.coaching_notes.length, 1); assert.equal(before.five_futures.status, 'CURRENT'); assert.equal(engine.five_futures.status, 'RECOMPUTED_FROM_CANONICAL_INPUTS'); assert.equal(before.one_move.id, engine.one_move.id); assert.equal(engine.one_move.replaced_by_coach, false); assert.equal(service.inspect().one_business_engine, true);
});

test('service-driven subscriber rejection blocks promotion and leaves Business Engine unchanged', () => {
  const at = '2026-07-22T12:00:00.000Z', scope = { tenant_id: 'tenant_reject_live', profile_id: 'profile_reject_live', business_id: 'business_reject_live', subscriber_id: 'subscriber_reject_live' };
  const flags = { ...DEFAULT_LIVE_SESSION_FLAGS, live_session_enabled: true, session_establishment_enabled: true, provider_adapter_enabled: true, transcription_enabled: true, extraction_enabled: true, coach_review_enabled: true, engine_evaluation_enabled: true, subscriber_confirmation_enabled: true, projection_refresh_enabled: true, synthetic_proof_enabled: true, emergency_disabled: false };
  const driver = new InMemoryLiveSessionDriver(), eventStore = new InjectedLiveSessionEventStore({ driver }), provider = new SyntheticMediaProvider({ clock: () => at }); let canonicalAppendCount = 0;
  let engine = { business_engine_id: 'engine_rejected', version: 2, policy_version: 'policy_live_v1', confidence_reality: { known: ['known_ref'], coaching_notes: [] }, five_futures: { status: 'CURRENT' }, one_move: { id: 'move_rejected_path', status: 'CURRENT' } }; const before = structuredClone(engine);
  const service = createLiveSessionService({ driver, eventStore, provider, flags, parentActivation: () => ({ allowed: true }), authorityEvaluator: () => ({ allowed: true, reason_code: 'AUTHORIZED' }), clock: () => at, canonicalAppend: () => { canonicalAppendCount += 1; engine = { ...engine, version: engine.version + 1 }; return { ok: true, event_id: `unexpected_rejection_append_${canonicalAppendCount}`, new_version: engine.version }; } });
  const created = service.createSession({ subscriber_scope: scope, coach_id: 'coach_reject_live', relationship_id: 'relationship_reject_live', entitlement_id: 'entitlement_reject_live', business_engine_id: engine.business_engine_id, created_by: scope.subscriber_id, policy_version: 'policy_live_v1', idempotency_key: 'reject_live_create' });
  const consent = { PARTICIPATION: 'GRANTED', TRANSCRIPTION: 'GRANTED', RECORDING: 'RESTRICTED', STRUCTURED_EXTRACTION: 'GRANTED', COACH_SHARING: 'GRANTED', BUSINESS_ENGINE_EVALUATION: 'GRANTED', FUTURE_LEARNING: 'RESTRICTED' };
  assert.equal(service.authorizeSession({ session_id: created.session.session_id, authorized_participants: [scope.subscriber_id, 'coach_reject_live'], consent, retention_policy: 'SYNTHETIC_DELETE_AFTER_PROOF', provider_permissions: ['CONNECT', 'TRANSCRIBE'] }).session.status, 'READY');
  assert.equal(service.connect({ session_id: created.session.session_id }).session.status, 'ACTIVE');
  const transcript = service.captureTranscript({ transcript_id: 'transcript_reject_live', session_id: created.session.session_id, status: 'FINALIZED', confidence: 0.95, finalized_at: at, segments: [{ segment_id: 'segment_reject_live', speaker_id: scope.subscriber_id, content_reference: 'protected_rejection_statement', confidence: 0.95, started_at: at }] }).transcript;
  const artifact = service.extract({ transcript_id: transcript.transcript_id, candidates: [{ artifact_type: 'OBSERVATION', source_spans: ['segment_reject_live'], speaker_id: scope.subscriber_id, confidence: 0.85, direct_statement: true, content_reference: 'reviewable_rejection_reference' }] }).artifacts[0];
  service.queueReview({ artifact_id: artifact.artifact_id }); const reviewed = service.review({ artifact_id: artifact.artifact_id, action: 'ACCEPT', coach_id: 'coach_reject_live' }).artifact;
  const proposed = service.propose({ artifact_id: reviewed.artifact_id, business_engine: engine, reason_for_change: 'Reviewed proposal rejected by subscriber' }).proposal;
  const confirmation = service.requestConfirmation({ proposal_id: proposed.proposal_id }).confirmation;
  const rejected = service.confirm({ confirmation_id: confirmation.confirmation_id, response: 'REJECT', subscriber_id: scope.subscriber_id }); assert.equal(rejected.confirmation.response_state, 'REJECTED');
  const promotion = service.promote({ proposal_id: proposed.proposal_id, confirmation_id: confirmation.confirmation_id, evidence_references: ['evidence_reject_live'], outcome_references: ['outcome_reject_live'], current_business_engine: engine, idempotency_key: 'rejected_promotion' });
  assert.equal(promotion.code, 'SUBSCRIBER_CONFIRMATION_REQUIRED'); assert.equal(canonicalAppendCount, 0); assert.deepEqual(engine, before); assert.equal(engine.version, 2); assert.deepEqual(engine.confidence_reality, before.confidence_reality); assert.deepEqual(engine.five_futures, before.five_futures); assert.deepEqual(engine.one_move, before.one_move);
});
