import test from 'node:test'; import assert from 'node:assert/strict';
import { createCoachAuthService, InMemoryCoachAuthStore } from '../src/lib/intelligenceFabric/index.js';

const enabled = { coach_auth_enabled: true, account_creation_enabled: true, verification_enabled: true, session_enabled: true,
  acceptance_context_enabled: true, production_traffic_enabled: false, synthetic_only: true, emergency_disabled: false };
function fixture() { let at = '2026-07-21T00:00:00.000Z', sequence = 0; const store = new InMemoryCoachAuthStore(); const service = createCoachAuthService({ store, flags: enabled, clock: () => at, tokenFactory: () => `synthetic-secure-token-${++sequence}-abcdefghijklmnop` }); return { store, service, setTime: (value) => { at = value; } }; }
const account = (service, subject = 'provider_subject_alpha', contact = 'contact_ref_alpha') => service.createAccount({ auth_subject_reference: subject, primary_contact_reference: contact, display_name: 'Synthetic Coach' });
const verify = (service, actorId) => { assert.equal(service.changeVerification({ coach_actor_id: actorId, action: 'BEGIN' }).ok, true); return service.changeVerification({ coach_actor_id: actorId, action: 'COMPLETE' }); };

test('account creation is durable idempotent and rejects subject collision and synthetic actors', () => { const { service } = fixture(), first = account(service); assert.equal(first.status, 'CREATED'); assert.equal(account(service).status, 'IDEMPOTENT_REPLAY'); assert.equal(account(service, 'provider_subject_alpha', 'different_contact').code, 'AUTH_SUBJECT_COLLISION'); assert.equal(service.createAccount({ auth_subject_reference: 'synthetic_subject', primary_contact_reference: 'contact_ref', display_name: 'Synthetic', synthetic_actor: true }).code, 'SYNTHETIC_ACTOR_DENIED'); });
test('verification and account lifecycle preserve terminal revocation and invalidate stale sessions', () => { const { service } = fixture(), created = account(service), actorId = created.actor.coach_actor_id; assert.equal(verify(service, actorId).actor.verification_state, 'VERIFIED'); const signed = service.issueSession({ auth_subject_reference: created.actor.auth_subject_reference }); assert.equal(signed.ok, true); assert.equal(service.changeAccountStatus({ coach_actor_id: actorId, action: 'SUSPEND' }).actor.account_status, 'SUSPENDED'); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: signed.session_token }).code, 'ACCOUNT_SUSPENDED'); assert.equal(service.changeAccountStatus({ coach_actor_id: actorId, action: 'REVOKE' }).actor.account_status, 'REVOKED'); assert.equal(service.changeAccountStatus({ coach_actor_id: actorId, action: 'RESTORE' }).code, 'INVALID_ACCOUNT_TRANSITION'); const locked = account(service, 'provider_subject_locked', 'contact_ref_locked'); assert.equal(service.changeAccountStatus({ coach_actor_id: locked.actor.coach_actor_id, action: 'LOCK' }).actor.account_status, 'LOCKED'); assert.equal(service.issueSession({ auth_subject_reference: locked.actor.auth_subject_reference }).code, 'ACCOUNT_LOCKED'); });
test('session validation uses instant expiry and denies fixation substitution rotation and revocation replay', () => { const { service, setTime } = fixture(), created = account(service); verify(service, created.actor.coach_actor_id); const signed = service.issueSession({ auth_subject_reference: created.actor.auth_subject_reference, client_context: { device: 'synthetic' } }); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: signed.session_token, expected_actor_id: created.actor.coach_actor_id, evaluated_at: '2026-07-20T18:30:00-05:00' }).ok, true); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: 'attacker-token-abcdefghijklmnop' }).code, 'SESSION_TOKEN_MISMATCH'); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: signed.session_token, expected_actor_id: 'coach_attacker' }).code, 'ACTOR_SUBSTITUTION_DENIED'); setTime('2026-07-21T00:10:00.000Z'); const rotated = service.rotateSession({ session_id: signed.session.session_id, session_token: signed.session_token }); assert.equal(rotated.ok, true); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: signed.session_token }).code, 'SESSION_ROTATED'); assert.equal(service.invalidateSession({ session_id: rotated.session.session_id }).ok, true); assert.equal(service.validateSession({ session_id: rotated.session.session_id, session_token: rotated.session_token }).code, 'SESSION_INVALID'); const fresh = service.issueSession({ auth_subject_reference: created.actor.auth_subject_reference }); assert.equal(service.revokeSession({ session_id: fresh.session.session_id }).ok, true); assert.equal(service.validateSession({ session_id: fresh.session.session_id, session_token: fresh.session_token }).code, 'SESSION_REVOKED'); });
test('expired and boundary-expired sessions fail across UTC offsets', () => { const { service } = fixture(), created = account(service), signed = service.issueSession({ auth_subject_reference: created.actor.auth_subject_reference }); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: signed.session_token, evaluated_at: '2026-07-20T20:00:00-05:00' }).code, 'SESSION_EXPIRED'); assert.equal(service.validateSession({ session_id: signed.session.session_id, session_token: signed.session_token, evaluated_at: '2026-07-21T01:00:00Z' }).code, 'SESSION_EXPIRED'); });
test('security events never retain session tokens contacts or browser references', () => { const { service, store } = fixture(), created = account(service); verify(service, created.actor.coach_actor_id); const signed = service.issueSession({ auth_subject_reference: created.actor.auth_subject_reference, client_context: { browser: 'private-browser' } }); service.revokeSession({ session_id: signed.session.session_id }); const serialized = JSON.stringify(store.snapshot().events); assert.doesNotMatch(serialized, /synthetic-secure-token|contact_ref_alpha|private-browser|provider_subject_alpha/); });
