import assert from 'node:assert/strict';
import test from 'node:test';

import {
  createCheckoutIdempotencyKey,
  startStripeCheckout,
} from '../src/lib/stripeCheckout.js';

test('checkout client uses governed same-origin ingress with a caller-stable idempotency key', async () => {
  const calls = [];
  const navigations = [];
  const idempotencyKey = 'subscription-checkout_1234567890abcdef';
  await startStripeCheckout({
    product_key: 'more_monthly_intelligence',
    profile_id: 'mm-20260912-paid0001',
  }, {
    idempotencyKey,
    fetchImpl: async (url, options) => {
      calls.push({ url, options });
      return {
        ok: true,
        async json() {
          return { ok: true, checkout_url: 'https://checkout.stripe.com/c/pay/synthetic' };
        },
      };
    },
    navigate: (url) => navigations.push(url),
  });
  assert.equal(calls.length, 1);
  assert.equal(calls[0].url, '/api/public-v1/purchase-intent');
  assert.equal(calls[0].options.credentials, 'same-origin');
  assert.equal(calls[0].options.cache, 'no-store');
  assert.equal(calls[0].options.headers['Idempotency-Key'], idempotencyKey);
  assert.deepEqual(navigations, ['https://checkout.stripe.com/c/pay/synthetic']);
});

test('checkout client refuses a missing retry key before network or navigation', async () => {
  let networkCalls = 0;
  await assert.rejects(startStripeCheckout({ product_key: 'behavior_operating_system' }, {
    fetchImpl: async () => { networkCalls += 1; },
    navigate: () => { throw new Error('must_not_navigate'); },
  }), /Payment setup is not available yet/u);
  assert.equal(networkCalls, 0);
});

test('checkout attempt keys are opaque, labeled and cryptographically generated by the browser', () => {
  const key = createCheckoutIdempotencyKey('Subscription Checkout');
  assert.match(key, /^subscription-checkout_[a-f0-9]{32}$/u);
});
