import { deepFreeze } from '../../validation.js';

export const PRIVATE_RUNTIME_FAILURE_CODES = deepFreeze([
  'PRIVATE_RUNTIME_DISABLED',
  'PRIVATE_RUNTIME_ENVIRONMENT_DENIED',
  'PRIVATE_TESTER_APPROVAL_REQUIRED',
  'PRIVATE_TESTER_APPROVAL_EXPIRED',
  'SUBJECT_ASSERTION_REQUIRED',
  'SUBJECT_ASSERTION_INVALID',
  'SUBJECT_MAPPING_NOT_FOUND',
  'SUBJECT_MAPPING_AMBIGUOUS',
  'SUBJECT_MAPPING_STALE',
  'SUBJECT_DISABLED',
  'SUBJECT_DELETED',
  'SESSION_ELEVATION_REQUIRED',
  'SESSION_ROTATION_FAILED',
  'SESSION_EXPIRED',
  'SESSION_REVOKED',
  'CAPABILITY_INVALID',
  'CAPABILITY_EXPIRED',
  'CAPABILITY_REVOKED',
  'SHARED_SECURITY_STATE_REQUIRED',
  'SHARED_SECURITY_STATE_UNAVAILABLE',
  'SHARED_SECURITY_STATE_PARTITIONED',
  'BUSINESS_ENGINE_ATTACHMENT_NOT_FOUND',
  'BUSINESS_ENGINE_ATTACHMENT_AMBIGUOUS',
  'BUSINESS_ENGINE_ATTACHMENT_MISMATCH',
  'SUBSCRIPTION_RUNTIME_UNAVAILABLE',
  'SUBSCRIPTION_RUNTIME_ATTACHMENT_MISMATCH',
  'COACH_CONNECT_STATE_MISSING',
  'COACH_CONNECT_ATTACHMENT_MISMATCH',
  'PRIVATE_ENTITLEMENT_REQUIRED',
  'ATTACHMENT_PARTIAL_FAILURE',
  'ACTION_NOT_ALLOWLISTED',
  'EMERGENCY_DISABLED',
]);

export function isPrivateRuntimeFailureCode(value) {
  return PRIVATE_RUNTIME_FAILURE_CODES.includes(value);
}
