const wrap=(texts,key)=>texts.map((text,i)=>({[key]:`${key==='id'?'A':'Q'}${String(i+1).padStart(2,'0')}`,text,skipped:false}));
export const ATHLETES=[{
 email:'alex-review@test.invalid',password:'Athlete-review-only-2026',name:'Alex Rivera',dateOfBirth:'2007-03-10',sport:'Soccer',pronouns:'he/him',
 bos:wrap([
 'My friends, making music on my laptop and helping my younger brother with his little video projects matter a lot. I am in community college. I would like time to make an EP with two friends, but I also want to see if I can transfer to a four-year school. I do not have the whole career plan yet.',
 'People think I am careless because I joke when a group is tense. Usually I notice the tension and want everyone to breathe. Sometimes I joke too soon and it sounds as if I do not care, even when I care a lot. I want people to know I take keeping my word seriously.',
 'I get into something when I can see what it will become or when someone needs me. I stayed up mixing a track because I could hear it improving. I keep putting off a repetitive online history worksheet even though I know it counts. Starting with someone else nearby helps me begin.',
 'After seeing close friends I usually have more energy. With a big unfamiliar group I talk first but then need an hour alone. Last weekend I liked meeting new teammates, then I went home and made music quietly instead of joining another outing.',
 'I tend to get a group moving. On a college presentation I suggested we divide it into short parts and volunteered to introduce it. One person had a better structure, so we used hers. I can interrupt if I think of a solution; I am practicing letting people finish.',
 'I say the options aloud to a friend, then try a small version if I can. When choosing between two courses I asked a student in each one, checked the workload, and decided that evening. I did not spend weeks comparing. A big family decision would take me longer.',
 'I want to try things before I know everything. I joined a beginner photography session with a borrowed camera and learned by taking bad pictures. I hold back if a mistake could cost someone else money or if I have no idea what the expectations are.',
 'I like a few clear points and room to change the order. I write down deadlines, not an hourly timetable. When our presentation partner was absent, I was comfortable changing who said what. I was less comfortable when the teacher changed the grading rule after we had finished.',
 'I will keep going if I can see progress. With a song I sometimes try a totally different beat when stuck. With boring homework I open other tabs and lose time. A friend and I worked in the library for forty minutes last week and I finished more than I do at home.',
 'I try an example, then ask someone to show where my version differs. In algebra I watched a short explanation and brought the step I still could not do to a tutor. A long page of theory on its own does not help me much, but I can use it once I have seen the problem.',
 'Show me one specific thing I can try and let me have another attempt. A tutor said my answer jumped a step and showed the missing line; that helped. Being corrected loudly in front of everyone makes me argue first even if the point is right.',
 'I get louder or make a sharp joke, then I go quiet later. People might think I am over it because I am still talking. I may be replaying the conversation afterward. I do not always say that at the time.',
 'I usually say I disagree directly. My friend said I had changed our recording time without checking, and I initially said it was only half an hour. He said he had arranged work around it. I apologized and we now check before changing times. I still felt embarrassed.',
 'After not getting a part in a college music performance I went for a walk, then talked to my brother. The next day I asked the organizer what to work on. I do not know which thing helped most. Having another chance mattered.',
 'I bring ideas and make it easier for a quiet person to join in. At home I cook when my mother works late, but I need the day written down or I can forget. I share the job if someone is better at a part. I am not the person who checks every small detail.',
 'My speed helps us get started, but sometimes I solve the wrong problem before listening. In a group project I built slides before we agreed on the question and had to redo them. When I have a written brief I slow down enough to check it first.',
 'I feel respected when people tell me the reason for a rule and hear my side. I try to say directly when I cannot do something rather than disappear. I am still inconsistent about replying to messages when I am busy.',
 'Ordinarily I can try something and laugh at a mistake. In a close game after I lose the ball, I try to win it back immediately and can rush the next decision. In a calm practice I look up much earlier. A teammate saying next play can bring my attention back, but not every time.',
 'Back-to-back commitments and lots of messages drain me more than one hard session. Music with no deadline and a quiet walk help. This week I had two exams and was sleeping less, so I was more impatient than usual. I do not want that week to define me.',
 'I like being useful and I also want people to enjoy being around me. I sometimes say yes to a plan before checking my week. I am still figuring out which commitments I really want. I am not always outgoing; with something personal I choose one person rather than the whole group.'
 ],'question_id'),
 apa:wrap([
 'Soccer. I play central midfield for a local club and study at community college. We are early in the league season, with one match on Saturday most weeks.',
 'I would like to earn more trust in close matches and eventually try out for a college team. Right now I want to make better decisions with the ball without losing my enjoyment.',
 'I spot forward passes quickly and communicate. Last Saturday two early passes helped us get out of pressure. I like getting teammates involved.',
 'After I lose possession I rush the next touch or pass to make up for it. In the second half last Saturday I tried a difficult pass immediately after a mistake and lost it again.',
 'Over the next seven weeks, I want to look up before my next pass after a mistake in close games. I would notice fewer rushed passes, rather than judge it only by minutes played.',
 'Club training Tuesday and Thursday for ninety minutes and a match Saturday. I sometimes kick a ball around with my brother on Sunday. I have classes three mornings and work in a cafe on Monday and Friday evenings.',
 'I want training to help me notice options earlier and make a calmer first decision after losing the ball.',
 'Small-sided games help because I get lots of decisions. When I look over my shoulder before receiving, I usually see an easier pass.',
 'I have tried adding extra running after a bad match. It makes me tired and does not really practice the decision I want. I do not have time for another evening session.',
 'Use something inside existing Tuesday and Thursday sessions. I need Sunday evening clear for school work. I can ask my coach for a simple cue but have not asked yet.',
 'I scan early, talk, and am willing to play a simple pass. I am less concerned with making a highlight moment.',
 'In a close score I speed up, especially after a mistake. I focus on getting the ball back rather than where the next option is.',
 'A breath and a teammate saying next play sometimes help. I have not practiced a consistent reset. I do not know if a long routine would stick.',
 'I want to handle the next thirty seconds after a mistake with more patience and attention.',
 'One clear cue is useful. Several people shouting different instructions makes me try to respond to all of them. My coach has not agreed to a specific cue with me yet.',
 'My first community-college year is going reasonably well. I enjoy media class. I am behind on two online history worksheets. I am keeping up in algebra with a weekly tutor.',
 'I am good at explaining ideas aloud and working with a group. Starting repetitive solo assignments is the weak part. I usually understand once I actually sit down.',
 'I want to hand in my next three history assignments on time and catch up on the two missing ones without an all-night rush.',
 'I am considering transferring for media production. I need to ask an adviser about the courses; I have not chosen a university or scholarship path.',
 'Tuesday and Thursday are full but workable. Sunday evening is the best homework window, yet I often agree to meet friends then. I could keep a forty-minute library block with a friend before leaving campus on Wednesday.'
 ],'id'),
 goals:{sport:'Look up before my next pass after a mistake in close games.',training:'Practice calmer passing decisions inside my existing club sessions.',mindset:'Handle the next thirty seconds after a mistake with more patience and attention.',school:'Hand in my next three history assignments on time and catch up on the two missing ones.'},priority:'Make the next useful decision after a mistake while keeping enough space for my college work.'
},{
 email:'dana-review@test.invalid',password:'Athlete-review-only-2026',name:'Dana Morris',dateOfBirth:'2009-04-19',sport:'Volleyball',pronouns:'she/her',
 bos:wrap([
 'Drawing, my younger sister and doing well enough in school to choose a college matter most. I like design but I am not sure whether to study it. I want more time for my sketchbook without feeling that I have left something unfinished.',
 'People think I have nothing to say because I am quiet in a big group. I usually have an opinion, but I like to work out how to explain it first. With two close friends I talk a lot. I do not want people to assume quiet means I agree.',
 'I like knowing what good work looks like and seeing myself improve. I redrew a difficult hand in a picture several times because I wanted to understand it. I struggle to care about an assignment when the instructions are vague and I cannot tell what is expected.',
 'Close friends are comfortable, but I still need quiet time afterward. A whole day with new people leaves me tired. At a team event I enjoyed the games, then wanted to read alone when I got home. That did not mean I disliked anyone.',
 'I often keep track of what needs doing and notice if someone has been left out. I speak up more when I know the topic. In a school project I made the checklist, while my friend presented. When the checklist was ignored I got frustrated but did not say so until later.',
 'I write down the options and what could go wrong, then ask one person I trust. I took several days to choose my classes because two good subjects clashed. Once I understood how each fit my schedule I decided. Small choices can be quick.',
 'I want to see an example before I try. I joined a design workshop after looking at the materials and knowing a friend would be there. Once I understand the first step I can be curious. Being told to just improvise in front of strangers makes me hesitate.',
 'I like a clear plan, especially when other people depend on me. When a class deadline moved earlier I rewrote my week and asked which part mattered most. I can adjust, but I need a little time. Last-minute changes without explanation annoy me.',
 'I usually keep going longer than I need to. I once spent an hour fixing tiny details on a poster after the important parts were done. A teacher helped me choose what was good enough. When I can see no progress I may avoid coming back the next day.',
 'I reread the instruction and try a worked example. If I am still stuck I write down the exact point and ask the teacher after class. Last week that helped with a chemistry calculation. I would rather ask privately than interrupt the whole class.',
 'Quiet, specific feedback with one example helps. My art teacher showed how a darker edge could change the picture and then let me try. A vague good job is pleasant but does not tell me what to do. Being compared with another person makes it harder to listen.',
 'I get very brief and my shoulders feel tight. I may say I am fine because I do not have the words yet. A close friend can tell when I stop making little jokes. Someone who only knows me in class may not notice anything.',
 'I tend to go quiet first and prepare what to say. A friend kept choosing the project topic, and I finally told her I wanted a turn. She said she had thought I did not mind. We chose together after that. I wish I had said it sooner.',
 'I need some space, then it helps to talk about what actually happened rather than hear that everything is fine. After a low chemistry mark I looked through the questions with my teacher the next day. I still felt disappointed, but I knew what I had misunderstood.',
 'I remember details and notice when someone needs a way in. At home I help my sister plan her homework, though she sometimes wants me just to sit with her. In a group I can organize the work, but I need to let others do it in their own way.',
 'Being careful can become checking the same thing too often. I sometimes redo someone else’s work because I worry about the final result. In art that care is useful; in a group it can make people feel I do not trust them. I am learning to ask before changing it.',
 'I feel respected when people ask what I think and give me time to answer. I try to remember what matters to a friend and not share something private. I can be too indirect when I want a different plan.',
 'On an ordinary day I can focus and work step by step. Under pressure I narrow in on one error and keep replaying it. At a tournament I was still thinking about a missed serve when the next rally started. In a familiar practice I recover more easily.',
 'Noise, uncertainty and unfinished tasks take energy. Drawing without a grade, reading and a quiet walk help. This month school deadlines overlap with tournaments, so I have been going to bed late. Some of my tiredness is this particular month.',
 'I want to be dependable, but I do not want being dependable to mean I never get to need help. I am learning to say when a plan is too much. My quiet side and my funny side are both real, depending on who I am with.'
 ],'question_id'),
 apa:wrap([
 'Club volleyball, mostly outside hitter. I am seventeen and in my final year of high school. We have tournaments about every other weekend this part of the season.',
 'I want to contribute confidently in matches and explore playing at college. I have not decided whether college sport is the main goal. I want to enjoy competing without carrying every mistake for the rest of the set.',
 'I prepare well, read the block and usually know the rotation. In our last match I found a good line shot twice when I took time to look.',
 'I hesitate after an error and become careful about calling for the ball. After a missed serve last weekend I stopped communicating for a few rallies.',
 'In seven weeks I want to call clearly for the next ball after a mistake instead of going quiet. I want to notice myself rejoining the play within the next rally.',
 'Practice Monday, Wednesday and Friday for two hours. Tournaments alternate weekends. I do assigned strength work inside team time. Tuesday is homework and Thursday is art club.',
 'I want training to help me communicate and choose a useful next action after a mistake, inside realistic rallies.',
 'Practice games with clear roles help. I feel more comfortable when I know what we are working on and get another attempt right away.',
 'I sometimes stay after practice to repeat serves until the last one feels perfect. That can turn into twenty extra minutes and a late dinner. It has not solved going quiet in a match.',
 'A clear stopping point and one thing to practice inside team time would help. I do not want extra sessions because chemistry needs attention and I want to keep art club.',
 'I call early, see the other side of the net and trust a sensible choice. I can accept a point against us and get ready again.',
 'I replay the error and wonder whether I let the team down. I check where everyone is but forget to say what I see.',
 'A teammate using my name and giving one next-play cue can help. Quietly taking a breath sometimes helps too. I have not asked for a consistent cue.',
 'I want to speak and rejoin the next rally rather than wait until I feel completely confident.',
 'Clear, calm feedback helps. Being told not to overthink does not tell me what to do. I would like my coach’s view, but I have not discussed a new plan with her.',
 'School is mostly going well. English and art feel strong. Chemistry is harder, especially applying formulas in unfamiliar questions. I have two important assessments next month.',
 'I plan assignments well and write carefully. In chemistry I sometimes keep rereading instead of identifying the exact step I do not understand. I lose time trying to solve it alone.',
 'I want to ask for help on the chemistry steps I do not understand before the next assessment, and finish my work without another midnight session.',
 'I am considering design at college and want to keep my options open. I need to compare programs and understand entry requirements. I do not know yet if I want to play college volleyball.',
 'Tournament weekends make Sunday homework uncertain. Tuesday afternoon is usually free for school. Art club on Thursday helps me recharge and I do not want to give it up. I could ask my chemistry teacher for a short check-in before Friday.'
 ],'id'),
 goals:{sport:'Call clearly for the next ball after a mistake instead of going quiet.',training:'Practice a useful next-rally response inside existing team time.',mindset:'Speak and rejoin the next rally without waiting to feel completely confident.',school:'Ask for help with chemistry before the next assessment and avoid midnight catch-up.'},priority:'Return to the next rally with a clear voice while protecting school work and art club.'
}];
