import {
  CONSTRAINT_TYPES,
  EPISTEMIC_CLASSES,
  PERSON_BUSINESS_RELATIONSHIP_TYPES,
  PROJECTION_ELIGIBILITY,
  WBM_CONTRACT_ID,
  WBM_CONTRACT_VERSION,
  WBM_SCHEMA_VERSION,
} from './constants.js';

const stringArray = Object.freeze({ type: 'array', items: { type: 'string' } });

export const WHOLE_BUSINESS_MODEL_V1_SCHEMA = Object.freeze({
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $id: 'https://moremindmap.local/schemas/whole-business-model-v1.json',
  title: 'MORE MindMap Whole-Business Model V1',
  type: 'object',
  required: [
    'contract_id',
    'contract_version',
    'schema_version',
    'assessment_identity',
    'frozen_whole_person_authority',
    'source_integrity',
    'authority_receipts',
    'governed_business_evidence',
    'current_business_reality',
    'business_model',
    'domain_states',
    'person_business_synthesis',
    'team_organizational_synthesis',
    'causal_model',
    'governing_constraint',
    'assets',
    'vulnerabilities',
    'momentum',
    'epistemic_state',
    'open_questions',
    'dynamic_research',
    'projection_eligibility',
    'state_lineage',
    'downstream_contributions',
    'runtime_boundaries',
  ],
  properties: {
    contract_id: { const: WBM_CONTRACT_ID },
    contract_version: { const: WBM_CONTRACT_VERSION },
    schema_version: { const: WBM_SCHEMA_VERSION },
    assessment_identity: {
      type: 'object',
      required: ['business_id', 'assessment_id', 'owner_profile_id', 'vertical'],
      properties: {
        business_id: { type: 'string', minLength: 1 },
        assessment_id: { type: 'string', minLength: 1 },
        owner_profile_id: { type: 'string', minLength: 1 },
        vertical: { type: 'string', minLength: 1 },
      },
    },
    frozen_whole_person_authority: {
      type: 'object',
      required: ['profile_id', 'bos_version', 'bos_hash', 'selected_claim_refs'],
      properties: {
        profile_id: { type: 'string', minLength: 1 },
        bos_version: { type: 'string', minLength: 1 },
        bos_hash: { type: 'string', pattern: '^[a-f0-9]{64}$' },
        selected_claim_refs: stringArray,
      },
    },
    source_integrity: {
      type: 'object',
      required: ['context_hash', 'authority_hashes', 'evidence_refs'],
      properties: {
        context_hash: { type: 'string', pattern: '^[a-f0-9]{64}$' },
        authority_hashes: { type: 'object', additionalProperties: { type: 'string', pattern: '^[a-f0-9]{64}$' } },
        evidence_refs: stringArray,
        dynamic_refs: stringArray,
      },
    },
    authority_receipts: { type: 'array', minItems: 1 },
    governed_business_evidence: { type: 'array' },
    current_business_reality: { type: 'object' },
    business_model: { type: 'object' },
    domain_states: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        required: ['domain_id', 'authority_refs', 'epistemic_class', 'claims', 'missing_evidence'],
        properties: {
          domain_id: { type: 'string', minLength: 1 },
          authority_refs: stringArray,
          epistemic_class: { enum: EPISTEMIC_CLASSES },
          claims: { type: 'array' },
          missing_evidence: { type: 'array' },
        },
      },
    },
    person_business_synthesis: {
      type: 'array',
      items: {
        type: 'object',
        required: ['business_mechanism_ref', 'whole_person_claim_ref', 'relationship_type', 'business_evidence_refs', 'epistemic_class', 'falsifier'],
        properties: {
          relationship_type: { enum: PERSON_BUSINESS_RELATIONSHIP_TYPES },
          epistemic_class: { enum: EPISTEMIC_CLASSES },
        },
      },
    },
    team_organizational_synthesis: { type: 'array' },
    causal_model: {
      type: 'object',
      required: ['mechanisms', 'reinforcing_loops', 'balancing_loops', 'compensating_strengths', 'confounds'],
      properties: { mechanisms: { type: 'array', minItems: 1 } },
    },
    governing_constraint: {
      type: 'object',
      required: ['constraint_id', 'constraint_type', 'evidence_refs', 'alternatives', 'epistemic_class'],
      properties: {
        constraint_type: { enum: CONSTRAINT_TYPES },
        epistemic_class: { enum: EPISTEMIC_CLASSES },
      },
    },
    assets: { type: 'array' },
    vulnerabilities: { type: 'array' },
    momentum: {
      type: 'object',
      required: ['direction', 'emerging_changes', 'leading_indicators', 'lagging_indicators', 'evidence_refs', 'epistemic_class'],
      properties: { direction: { enum: ['IMPROVING', 'DETERIORATING', 'STABLE', 'MIXED', 'UNCERTAIN'] } },
    },
    epistemic_state: { type: 'object' },
    open_questions: { type: 'array' },
    dynamic_research: { type: 'array' },
    projection_eligibility: {
      type: 'object',
      required: ['five_futures_v2', 'one_move_v2'],
      properties: {
        five_futures_v2: { type: 'object', properties: { status: { enum: PROJECTION_ELIGIBILITY } } },
        one_move_v2: { type: 'object', properties: { status: { enum: PROJECTION_ELIGIBILITY } } },
      },
    },
    state_lineage: { type: 'object' },
    downstream_contributions: { type: 'object' },
    runtime_boundaries: { type: 'object' },
  },
});
