import {clientSessionEvents} from './sessionEvents.js';
let csrf=null,bootstrapping=null;
clientSessionEvents.subscribe(event=>{if(event.kind==='invalidated'||event.kind==='actor-changed'){csrf=null;bootstrapping=null;}});
const authenticationChanges=new Set(['login','logout','reset_password']);
const sessionChanged=()=>{const error=new Error('Your sign-in changed. Your saved work remains protected.');error.code='SESSION_CHANGED';return error;};
const staleFormRetryActions=new Set(['login','request_password_reset','reset_password']);
const messages={LOCAL_REVIEW_USE_TEST_EMAIL:'This private review uses fictional accounts only. Use a name@test.invalid address; email stays in the local review mailbox.',SIGN_IN_REQUIRED:'Please sign in to continue.',SESSION_OR_FORM_EXPIRED:'Your sign-in form expired. Refresh the page and try again.',SESSION_EXPIRED:'Please sign in again.',GUARDIAN_REQUIRED:'A parent or guardian needs to finish the invitation first.',STATE_CHANGED_RELOAD:'Your saved work changed in another tab. Reload to pick up the latest version.',GENERATION_NOT_CONFIGURED:'Report generation is not connected in this review environment yet. Your answers are saved.',COACH_CONNECTION_UNAVAILABLE:'The coaching connection is not available yet. Your reports and saved work are safe.',EMAIL_SERVICE_UNAVAILABLE:'Email delivery is not available yet. Please try again later.',INSTITUTION_CODE_INVALID:'That academy code was not recognized.',EMAIL_OR_PASSWORD_NOT_RECOGNIZED:'We could not match that email and password.',VERIFY_EMAIL_FIRST:'Please confirm your email before signing in.',PASSWORD_12_CHARACTERS_REQUIRED:'Use a password with at least 12 characters.',ACCOUNT_CANNOT_BE_CREATED:'An account could not be created with these details. If you already joined, sign in or reset your password.',PILOT_CALIFORNIA_13_PLUS:'This first test is for people age 13 or older in California.',ADULT_GUARDIAN_REQUIRED:'A guardian account must belong to an adult age 18 or older.',GUARDIAN_INVITATION_INVALID:'This invitation is not current, or it was sent to a different email.',PARTICIPANT_ACCOUNT_REQUIRED:'Use your own athlete account for this action.',PILOT_CALIFORNIA_18_PLUS:'This first test is for adults age 18 or older in California.',YOUTH_ENROLLMENT_NOT_ACTIVE:'Youth participation is paused for this adult pilot. Saved records remain protected.',PARTICIPATION_REVIEW_REQUIRED:'Please review the participation information first.',LINK_EXPIRED_OR_USED:'This link has expired or was already used.',ATTEMPT_STILL_ACTIVE:'This saved attempt is still active. Check again before setting it aside.',PREVIOUS_RESPONSE_NEEDS_REVIEW:'Your previous response needs a recovery check. Your message and saved plan are safe.'};
export async function bootstrap(){
 if(bootstrapping)return bootstrapping;
 const epoch=clientSessionEvents.epoch();
 const pending=(async()=>{const response=await fetch('/api/athlete/academy',{credentials:'same-origin',cache:'no-store'});const d=await response.json();if(epoch!==clientSessionEvents.epoch())throw sessionChanged();if(!response.ok||!d.ok)throw new Error(messages[d.error?.code]||d.error?.message||'MORE is unavailable right now.');clientSessionEvents.observe(d,epoch);csrf=d.csrfToken;return d;})();
 bootstrapping=pending;
 try{return await pending;}finally{if(bootstrapping===pending)bootstrapping=null;}
}
async function post(action,body,requestId){const response=await fetch('/api/athlete/academy',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({action,requestId,...body})});return {response,d:await response.json()};}
export async function call(action,body={}){if(!csrf)await bootstrap();let epoch=clientSessionEvents.epoch();const requestId=body.requestId||crypto.randomUUID();let result=await post(action,body,requestId);if(epoch!==clientSessionEvents.epoch())throw sessionChanged();if(staleFormRetryActions.has(action)&&!result.response.ok&&result.d.error?.code==='SESSION_OR_FORM_EXPIRED'){await bootstrap();epoch=clientSessionEvents.epoch();result=await post(action,body,requestId);if(epoch!==clientSessionEvents.epoch())throw sessionChanged();}const {response,d}=result;if(!response.ok||!d.ok){const e=new Error(messages[d.error?.code]||String(d.error?.code||'Something interrupted this request. Your saved work is safe.').replaceAll('_',' ').toLowerCase());e.code=d.error?.code;if(['SIGN_IN_REQUIRED','SESSION_EXPIRED'].includes(e.code))clientSessionEvents.invalidate();throw e;}if(authenticationChanges.has(action))clientSessionEvents.invalidate(true);else if(d.csrfToken)csrf=d.csrfToken;return d;}
export const workspaceLink=(kind,mm)=>`/athlete/workspace/${kind}.html?mm=${encodeURIComponent(mm)}`;
