import {DOMAINS,ROLES,ROLE_LABELS,dateLabel} from './design.js';
export function project(a){
 const objects={},r=a.report,m=a.move;
 const sourceText=s=>s.id==='CONFIRM'?DOMAINS.map(d=>`${d.label}: ${a.confirmation.goals[d.id]}`).join(' ') + ` Your chosen priority: ${a.confirmation.priority} Review your move on ${dateLabel(a.confirmation.review_date)}; look ahead to ${dateLabel(a.confirmation.horizon_date)}.`:s.text;
 const section=(title,items)=>({id:title.toLowerCase().replace(/[^a-z]+/g,'-'),title,items:Array.isArray(items)?items:[items]});
 const sourceSections=x=>[section('Your current answers',(x.refs||[]).map(id=>{const s=a.sources.find(s=>s.id===id);return s?`${s.source}${s.question?` · ${s.question}`:''}: ${sourceText(s)}`:id;})),section('Your saved BOS',(x.bos_refs||[]).map(id=>{const b=a.bos_sources.find(b=>b.id===id);return `${b.headline}: ${b.text}`;}))].filter(s=>s.items.length);
 const obj=(id,destination,title,items,kind='MORE interpretation')=>{objects[id]={object_id:id,destination,drawer_type:'apa-v2',display_payload:{title},epistemic_class:kind,confidence:null,drawer_payload:items};};
 for(const d of r.domains)obj(`domain-${d.id}`,'where',DOMAINS.find(x=>x.id===d.id).label,[section('What MORE sees',d.detail),section('How your BOS helps',d.bos_connection),...(d.unknowns.length?[section('Still to understand',d.unknowns)]:[]),...sourceSections(d)]);
 for(const f of r.futures)obj(`future-${f.role}`,'futures',f.headline,[section('Why this path is possible',f.details),...sourceSections(f)],'Conditional possibility');
 if(m)obj('move','move','Why this move fits you',[section('Your personality matters',m.bos_fit),section('Why this first',m.why),section('Other options we considered',r.candidates.filter(c=>c.candidate_id!==m.candidate_id).map(c=>c.gates.every(g=>g.pass)?`Possible alternative: ${c.action} ${c.why}`:`Not recommended this week: ${c.action} ${c.gates.filter(g=>!g.pass).map(g=>g.reason).join(' ')}`)),section('Fits your real week',m.gates.map(g=>g.reason)),...sourceSections(m)],'Suggestion to discuss');
 obj('connection','where','How the four parts connect',[section('The whole picture',r.connection),section('Your chosen priority',a.confirmation.priority),section('What may be getting in the way',r.main_obstacle),section('Still to understand',r.what_we_dont_know.length?r.what_we_dont_know:['No other major gap was identified in these answers.'])]);
 obj('sources','evidence','Your sources',[section('Your APA',a.sources.map(s=>`${s.source}${s.question?` · ${s.question}`:''}: ${sourceText(s)}`)),section('Your BOS',a.bos_sources.map(s=>`${s.headline}: ${sourceText(s)}`))],'Your saved words and BOS');
 const nav=[{id:'where',label:'Where you are',order:1},{id:'futures',label:'Five Futures',order:2},{id:'move',label:'One Move',order:3},{id:'plan',label:'Your plan',order:4},{id:'evidence',label:'Why MORE says this',order:5}];
 return {identity:{firstName:a.identity.name.split(' ')[0],vertical:a.identity.sport},stateHash:a.artifact_sha256,nav,objects,destinations:Object.fromEntries(nav.map(n=>[n.id,{}])),hero:{eyebrow:'YOUR ATHLETE PERFORMANCE ASSESSMENT',title:`${a.identity.name.split(' ')[0]}, this is your next chapter.`,subtitle:r.opening,modelDate:`${dateLabel(a.confirmation.assessment_date)}, ${a.confirmation.assessment_date.slice(0,4)} · ${a.mm}`},presentation:{explanationEyebrow:'YOUR APA',brandAria:'MORE Athlete',brandTop:'MORE',brandBottom:'ATHLETE',railKicker:'Your performance assessment',navAria:'Your APA',boundaryTitle:'Your saved assessment',boundaryCopy:'Your answers today, connected to your saved personality profile (BOS).' ,backLabel:'← Back to your APA',overviewAria:'Your APA boxes',bigPictureLabel:'The whole picture',bigPictureAria:'How the four parts of your life connect',nextStepLabel:'Your chosen priority',startPlanLabel:'See your next step',snapshotTitle:'Your voice comes first.',snapshotCopy:'This is a suggestion to discuss. You choose what to try.',drawerSuffix:'Why MORE says this',drawerFooter:'Your answers and your saved BOS. Suggestions can be corrected.',howCopy:'Your BOS is your saved personality profile. This APA connects that whole person to your sport and life now. Start with Where you are: Sport, Training, Warrior Mindset, and School. Five Futures shows what could happen under different conditions. One Move suggests one useful next step. Open Why MORE says this whenever you want the reasoning. You can review and correct your answers from the top bar.',returnLabel:'Return to your APA'},layer0:{cards:[
 {id:'where',objectId:'connection',title:'Where you are',description:'Four parts of your life. One clear picture.',value:'4',qualifier:'Goals that belong to you',details:DOMAINS.map(d=>({value:d.label,label:a.confirmation.goals[d.id]})),cta:'See your four areas'},
 {id:'futures',objectId:'connection',title:'Five Futures',description:`Five possible paths to ${dateLabel(a.confirmation.horizon_date)}.`,items:r.futures.map((f,i)=>({label:f.headline,displayValue:ROLE_LABELS[i]})),cta:'Explore the paths'},
 {id:'move',objectId:'move',title:'One Move',description:'One useful thing to do next.',icon:'⌾',value:m?.action||'Clarify what fits first.',qualifier:'Chosen to fit your goals, your personality, and your week.',cta:'See your move'},
 {id:'plan',objectId:'move',title:'Your plan',description:'Keep the next step simple.',icon:'✓',value:'Try. Notice. Review.',qualifier:m?.review_schedule?`Setup check on ${dateLabel(a.confirmation.review_date)}. Check usefulness after the agreed test.`:`A proposal for you to consider. Review on ${dateLabel(a.confirmation.review_date)}.`,cta:'See the proposal'},
 {id:'evidence',objectId:'sources',title:'Why MORE says this',description:'Your words. Your personality. The reasoning.',icon:'▤',items:[{value:'20',label:'Answers from you'},{value:'4',label:'Goals you confirmed'},{value:'BOS',label:'Your whole-person profile'}],cta:'See the reasons'}
 ],bigPicture:r.headline,bigPictureQualifier:r.connection,nextStep:a.confirmation.priority,nextStepQualifier:'One practical next step, with room for the rest of your life.'}};
}
