export const SYNTHETIC_RECRUITING_FIXTURE = Object.freeze({
  synthetic_only: true,
  manager: {
    name: 'Sophia Bennett', enterprise_name: 'Harborline Realty Group', profile_id: 'mm-20990101-sophia01',
    capabilities: { master_control: true },
    operating_style: 'Direct, fast-moving, candid, and highly responsive. Strong coaching cadence; can move past detail before trust is established.',
  },
  entitlement: { mode: '5_per_month', limit: 5, used: 3, reserved: 1, consumed: 2, remaining: 2, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' },
  notifications: [
    { notification_id: 'notice_synthetic_ba', kind: 'BA_INTELLIGENCE_READY', title: "Evan's business intelligence is ready.", body: 'Database conversion and operating-capacity evidence can now sharpen the conversation.', created_at: '2026-08-20T15:20:00.000Z', read: false },
  ],
  candidates: [
    { invitation_id: 'invite_synthetic_evan', candidate_id: 'candidate_synthetic_evan', recruit_name: 'Evan Brooks', recruit_email: 'evan.brooks@example.test', purpose: 'Explore whether Harborline can genuinely help Evan build a more durable real-estate business.', state: 'ACCEPTED', readiness_state: 'BA_INTELLIGENCE_READY', ba_readiness: 'BA_INTELLIGENCE_READY', delivery_state: 'DELIVERED', entitlement_state: 'CONSUMED', issued_at: '2026-08-13T15:00:00.000Z', expires_at: '2026-08-20T15:00:00.000Z', accepted_at: '2026-08-14T16:30:00.000Z', bos_profile_id: 'mm-20990101-evan0001', ba_assessment_id: 'ba-20990101-evan0001' },
    { invitation_id: 'invite_synthetic_maya', candidate_id: 'candidate_synthetic_maya', recruit_name: 'Maya Chen', recruit_email: 'maya.chen@example.test', purpose: 'Offer a private MORE MindMap profile before an exploratory conversation.', state: 'DELIVERED', readiness_state: 'INVITED', ba_readiness: 'BA_NOT_STARTED', delivery_state: 'DELIVERED', entitlement_state: 'RESERVED', issued_at: '2026-08-19T19:00:00.000Z', expires_at: '2026-08-26T19:00:00.000Z', accepted_at: null, bos_profile_id: null, ba_assessment_id: null },
    { invitation_id: 'invite_synthetic_luis', candidate_id: 'candidate_synthetic_luis', recruit_name: 'Luis Romero', recruit_email: 'luis.romero@example.test', purpose: 'Understand how Luis naturally builds trust and where local support may matter.', state: 'ACCEPTED', readiness_state: 'BOS_READY', ba_readiness: 'BA_NOT_STARTED', delivery_state: 'DELIVERED', entitlement_state: 'CONSUMED', issued_at: '2026-08-07T17:00:00.000Z', expires_at: '2026-08-14T17:00:00.000Z', accepted_at: '2026-08-08T18:15:00.000Z', bos_profile_id: 'mm-20990101-luis0001', ba_assessment_id: null },
  ],
  opportunity: {
    authority_id: 'opportunity_synthetic_harborline', enterprise_id: 'enterprise_synthetic_harborline', updated_at: '2026-08-20T17:00:00.000Z',
    items: [
      { opportunity_evidence_id: 'opp_coaching_system', category: 'COACHING_AND_TRAINING', scope: 'LOCAL_LEADER_PRIMARY', statement: 'Sophia runs a weekly database-conversion lab with call review, follow-up design, and measured next actions.', status: 'SUPPORTED', source: 'Manager operating review', source_date: '2026-08-12', freshness: 'CURRENT_30_DAYS', constraints: ['Capacity is limited to six active coaching seats.'], counterevidence: [] },
      { opportunity_evidence_id: 'opp_ops_capacity', category: 'OPERATIONS_AND_LEVERAGE', scope: 'LOCAL_LEADER_PRIMARY', statement: 'A shared transaction coordinator can support agents after two closed sides in a rolling month.', status: 'CONDITIONAL', source: 'Local service standard', source_date: '2026-08-09', freshness: 'CURRENT_30_DAYS', constraints: ['Eligibility threshold and coordinator capacity apply.'], counterevidence: [] },
      { opportunity_evidence_id: 'opp_lead_unknown', category: 'LEAD_OPPORTUNITY', scope: 'LOCAL_LEADER_PRIMARY', statement: 'No current evidence establishes a consistent company-provided lead allocation for a new agent.', status: 'NON_PROMISE', source: 'Manager clarification', source_date: '2026-08-18', freshness: 'CURRENT_30_DAYS', constraints: [], counterevidence: ['Lead volume and conversion by agent are not yet verified.'] },
      { opportunity_evidence_id: 'opp_platform', category: 'COMPANY_PLATFORM', scope: 'COMPANY_SECONDARY', statement: 'Harborline provides transaction software and a shared vendor directory.', status: 'SUPPORTED', source: 'Current enterprise services sheet', source_date: '2026-08-01', freshness: 'CURRENT_30_DAYS', constraints: [], counterevidence: [] },
    ],
  },
  manager_evidence: [
    { evidence_id: 'evidence_database_constraint', candidate_id: 'candidate_synthetic_evan', type: 'CONVERSATION', claim: 'Evan said his database is large enough to matter but his follow-up is inconsistent and difficult to trust.', source: 'Manager conversation note', source_date: '2026-08-11', recorded_at: '2026-08-11T21:00:00.000Z', truth_class: 'MANAGER_SUPPLIED_EVIDENCE', canonical_recruit_truth_mutated: false },
    { evidence_id: 'evidence_capacity_constraint', candidate_id: 'candidate_synthetic_evan', type: 'GOAL', claim: 'Evan wants to grow without adding another layer of personal administrative work.', source: 'Manager conversation note', source_date: '2026-08-11', recorded_at: '2026-08-11T21:05:00.000Z', truth_class: 'MANAGER_SUPPLIED_EVIDENCE', canonical_recruit_truth_mutated: false },
  ],
  recruit: {
    name: 'Evan Brooks', readiness: 'BA_INTELLIGENCE_READY',
    bos_summary: 'Deliberate, detail-oriented, and trust-sensitive. Evan prefers evidence, sequence, and clear operating expectations before committing.',
    ba_summary: 'The business has meaningful relationship inventory but inconsistent database conversion and limited operational capacity.',
    known: ['MORE MindMap Profile verified', 'Business Assessment intelligence ready', 'Database-conversion constraint is evidence-supported', 'Capacity concern appears in both recruit and manager evidence'],
    unknown: ['Current conversion rate by segment', 'Exact economics of changing companies', 'Whether local coaching capacity is available in Evan’s preferred meeting window'],
  },
  intelligence: {
    contract: 'recruiting_intelligence_projection_v1', generated_at: '2026-08-20T18:00:00.000Z', stale: false,
    projection_hash: '3863e6846c010de78cd19223eedc858f5b68d1194b184a72f20452d8a122eb4d',
    output: {
      understand_this_recruit: { summary: 'Evan is not looking for more noise. He is trying to make an existing relationship business more reliable without giving up control or adding administrative drag.', important_realities: ['He processes change through evidence and operational detail.', 'Database conversion is a legitimate business constraint, not merely a motivation issue.', 'Capacity support matters only if eligibility and ownership are explicit.'] },
      bilateral_communication: { advantage: 'Sophia can create clarity quickly and make a concrete operating path visible.', recruiter_watchout: 'Sophia’s natural speed may feel like pressure if she moves to conclusions before Evan has tested the details.', adaptation: 'Lead with the operating problem, name what is not known, and let Evan examine one supported mechanism at a time.' },
      authentic_angles: [
        { title: 'Turn relationship inventory into a reliable follow-up system', recruit_need: 'Reliable follow-up that converts existing relationships without constant reinvention.', current_reality: 'Evan has relationship inventory but inconsistent segmentation and next-action discipline.', locally_supported_help: 'Sophia’s weekly database-conversion lab directly addresses call review, follow-up design, and measured next actions.', rationale: 'This connects a verified business constraint to a current local coaching mechanism.', validating_question: 'If you could see the exact weekly operating rhythm before deciding anything, what would you need it to prove?', uncertainty: 'Current seat availability and Evan’s segment-level conversion baseline remain unverified.', recruit_evidence_ids: ['evidence_database_constraint'], opportunity_evidence_ids: ['opp_coaching_system'] },
        { title: 'Create capacity without promising immediate leverage', recruit_need: 'Growth that does not add another layer of personal administrative work.', current_reality: 'Operational capacity is constrained and Evan wants ownership boundaries to be explicit.', locally_supported_help: 'Harborline has conditional transaction coordination after a stated production threshold.', rationale: 'The support may matter if the threshold, handoff standard, and current capacity are acceptable.', validating_question: 'Which administrative work would have to leave your plate before growth would feel genuinely sustainable?', uncertainty: 'Eligibility timing and coordinator capacity must be confirmed before this becomes a promise.', recruit_evidence_ids: ['evidence_capacity_constraint'], opportunity_evidence_ids: ['opp_ops_capacity'] },
      ],
      withheld_angles: ['Company-provided leads are withheld as an angle because local volume, allocation, and outcomes are not established.'],
      success_environment: { natural_success_patterns: ['Trust-based advisor who wins through preparation and follow-through', 'Deliberate systems builder who improves consistency once ownership is clear'], supportive_conditions: ['Clear evidence before commitment', 'Defined operating rhythms and handoffs', 'A leader who answers detailed questions without interpreting them as resistance'], likely_frictions: ['Fast promises without operating proof', 'Ambiguous ownership', 'High-volume activity expectations without quality context'] },
      missing_evidence: ['Segment-level database conversion', 'Current local coaching seat availability', 'Transaction coordination capacity and service standard', 'Comparable economics and transition cost'],
      meeting_plan: { start_here: 'Start with Evan’s stated desire to make the business more reliable, not with Harborline.', learn: ['What breaks first in the current follow-up system?', 'Which work must remain personally owned?', 'What proof would make a new operating rhythm credible?'], listen_for: ['Whether the constraint is process, skill, capacity, or trust', 'The threshold at which support becomes valuable', 'Evidence that the current situation may already be improving'], your_watchout: 'Do not let speed turn a useful hypothesis into a premature recommendation.', supported_paths_if_confirmed: ['Database-conversion coaching', 'Conditional transaction coordination'], do_not_assume: 'Do not imply leads, immediate leverage, or better economics without current local proof.', next_step_if_fit_is_real: 'Agree on one evidence-gathering step: let Evan inspect the coaching rhythm and verify support capacity before discussing a move.' },
    },
  },
  invite_preview: { recruit_name: 'Maya Chen', inviter_name: 'Sophia Bennett', enterprise_name: 'Harborline Realty Group', purpose: 'Offer a private MORE MindMap profile before an exploratory conversation.', expires_at: '2026-08-26T19:00:00.000Z' },
  manager_setup_preview: { manager_name: 'Elena Torres', masked_email: 'el***@example.test', enterprise_name: 'Canyon Ridge Realty', profile_bound: false, expires_at: '2026-08-28T17:00:00.000Z' },
  master_control: {
    default_view: 'ALL_AUTHORIZED_MEMBERSHIPS',
    total: 5,
    admin: { manager_name: 'Darren Synthetic', enterprise_name: 'MORE MindMap Enterprise', status: 'ACTIVE', setup_state: 'COMPLETE', entitlement: { mode: 'unlimited', limit: null, used: 8, reserved: 3, consumed: 5, remaining: null, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' } },
    memberships: [
      { membership_id: 'membership_synthetic_canyon_pending', manager_name: 'Elena Torres', manager_email: 'elena.torres@example.test', enterprise_id: 'enterprise_synthetic_canyon', enterprise_name: 'Canyon Ridge Realty', status: 'PENDING_SETUP', setup_state: 'SETUP_SENT', profile_bound: false, setup_sent_at: '2026-08-20T17:00:00.000Z', entitlement: { mode: '5_per_month', limit: 5, used: 0, reserved: 0, consumed: 0, remaining: 5, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' }, audit: [] },
      { membership_id: 'membership_synthetic_harborline_sophia', manager_name: 'Sophia Bennett', manager_email: 'sophia.bennett@example.test', enterprise_id: 'enterprise_synthetic_harborline', enterprise_name: 'Harborline Realty Group', status: 'ACTIVE', setup_state: 'COMPLETE', profile_bound: true, setup_completed_at: '2026-07-28T17:00:00.000Z', entitlement: { mode: '5_per_month', limit: 5, used: 3, reserved: 1, consumed: 2, remaining: 2, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' }, audit: [] },
      { membership_id: 'membership_synthetic_moremindmap_darren', manager_name: 'Darren Synthetic', manager_email: 'darren.admin@example.test', enterprise_id: 'enterprise_synthetic_moremindmap', enterprise_name: 'MORE MindMap Enterprise', status: 'ACTIVE', setup_state: 'COMPLETE', profile_bound: true, setup_completed_at: '2026-07-01T17:00:00.000Z', entitlement: { mode: 'unlimited', limit: null, used: 8, reserved: 3, consumed: 5, remaining: null, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' }, audit: [] },
      { membership_id: 'membership_synthetic_northstar_revoked', manager_name: 'Priya Shah', manager_email: 'priya.shah@example.test', enterprise_id: 'enterprise_synthetic_northstar', enterprise_name: 'Northstar Properties', status: 'REVOKED', setup_state: 'COMPLETE', profile_bound: true, revoked_at: '2026-08-17T18:00:00.000Z', entitlement: { mode: '5_per_month', limit: 5, used: 1, reserved: 0, consumed: 1, remaining: 4, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' }, audit: [] },
      { membership_id: 'membership_synthetic_summit_suspended', manager_name: 'Marcus Lee', manager_email: 'marcus.lee@example.test', enterprise_id: 'enterprise_synthetic_summit', enterprise_name: 'Summit House Group', status: 'SUSPENDED', setup_state: 'COMPLETE', profile_bound: true, suspended_at: '2026-08-18T18:00:00.000Z', entitlement: { mode: '5_per_month', limit: 5, used: 2, reserved: 1, consumed: 1, remaining: 3, period_start: '2026-08-01T00:00:00.000Z', period_end: '2026-09-01T00:00:00.000Z' }, audit: [] },
    ],
  },
});
