import { deepFreeze } from '../../validation.js';

const move = (machine, current, action, code) => { const next = machine[current]?.[action]; return deepFreeze(next ? { ok: true, previous: current, current: next, action } : { ok: false, code, previous: current, action }); };

const SESSION = {
  CREATED: { AUTHORIZE: 'AUTHORIZING', CANCEL: 'CANCELLED' },
  AUTHORIZING: { AUTHORIZE_SUCCESS: 'READY', AUTHORIZE_FAIL: 'AUTHORIZATION_FAILED', CONSENT_FAIL: 'CONSENT_BLOCKED', CANCEL: 'CANCELLED' },
  READY: { CONNECT: 'CONNECTING', CANCEL: 'CANCELLED' }, CONNECTING: { CONNECTED: 'ACTIVE', DEGRADE: 'CONNECTION_DEGRADED', INTERRUPT: 'INTERRUPTED', FAIL: 'FAILED' },
  ACTIVE: { PAUSE: 'PAUSED', DEGRADE: 'CONNECTION_DEGRADED', INTERRUPT: 'INTERRUPTED', CLOSE: 'CLOSING', CONSENT_REVOKED: 'CONSENT_BLOCKED', FAIL: 'FAILED' },
  PAUSED: { RESUME: 'ACTIVE', INTERRUPT: 'INTERRUPTED', CLOSE: 'CLOSING', CONSENT_REVOKED: 'CONSENT_BLOCKED' },
  CONNECTION_DEGRADED: { RECOVER: 'RECOVERING', INTERRUPT: 'INTERRUPTED', CLOSE: 'CLOSING' }, INTERRUPTED: { RECOVER: 'RECOVERING', CLOSE: 'CLOSING' },
  RECOVERING: { RECOVERED: 'ACTIVE', RECOVERY_FAIL: 'RECOVERY_FAILED', CONSENT_REVOKED: 'CONSENT_BLOCKED' }, RECOVERY_FAILED: { CLOSE: 'CLOSING' },
  CONSENT_BLOCKED: { CLOSE: 'CLOSING' }, CLOSING: { FINALIZE: 'CLOSED', FAIL: 'FAILED' },
  AUTHORIZATION_FAILED: {}, CLOSED: {}, CANCELLED: {}, FAILED: {},
};
const ARTIFACT = { EXTRACTED: { QUEUE_REVIEW: 'PENDING_COACH_REVIEW' }, PENDING_COACH_REVIEW: { ACCEPT: 'COACH_ACCEPTED', EDIT: 'COACH_EDITED', REJECT: 'COACH_REJECTED' }, COACH_ACCEPTED: { SUBMIT: 'PENDING_ENGINE_EVALUATION', SUPERSEDE: 'SUPERSEDED' }, COACH_EDITED: { SUBMIT: 'PENDING_ENGINE_EVALUATION', SUPERSEDE: 'SUPERSEDED' }, PENDING_ENGINE_EVALUATION: { ACCEPT_AS_NOTE: 'ENGINE_ACCEPTED_AS_NOTE', REQUIRE_CONFIRMATION: 'PENDING_SUBSCRIBER_CONFIRMATION', SUPERSEDE: 'SUPERSEDED' }, PENDING_SUBSCRIBER_CONFIRMATION: { CONFIRM: 'SUBSCRIBER_CONFIRMED', REJECT: 'SUBSCRIBER_REJECTED', SUPERSEDE: 'SUPERSEDED' }, SUBSCRIBER_CONFIRMED: { PROMOTE: 'PROMOTED', SUPERSEDE: 'SUPERSEDED' }, ENGINE_ACCEPTED_AS_NOTE: { SUPERSEDE: 'SUPERSEDED' }, PROMOTED: { SUPERSEDE: 'SUPERSEDED' }, COACH_REJECTED: {}, SUBSCRIBER_REJECTED: {}, SUPERSEDED: {} };
const CONSENT = { UNKNOWN: { REQUEST: 'REQUESTED' }, REQUESTED: { GRANT: 'GRANTED', RESTRICT: 'RESTRICTED', REVOKE: 'REVOKED', EXPIRE: 'EXPIRED' }, GRANTED: { RESTRICT: 'RESTRICTED', REVOKE: 'REVOKED', EXPIRE: 'EXPIRED' }, RESTRICTED: { GRANT: 'GRANTED', REVOKE: 'REVOKED', EXPIRE: 'EXPIRED' }, REVOKED: {}, EXPIRED: {} };
const COMMITMENT = { PROPOSED: { ACCEPT: 'ACCEPTED', CANCEL: 'CANCELLED' }, ACCEPTED: { ACTIVATE: 'ACTIVE', CANCEL: 'CANCELLED' }, ACTIVE: { REQUEST_EVIDENCE: 'EVIDENCE_PENDING', COMPLETE: 'COMPLETED', PARTIAL: 'PARTIALLY_COMPLETED', MISS: 'MISSED', CANCEL: 'CANCELLED' }, EVIDENCE_PENDING: { COMPLETE: 'COMPLETED', PARTIAL: 'PARTIALLY_COMPLETED', MISS: 'MISSED', CANCEL: 'CANCELLED' }, COMPLETED: { VALIDATE_OUTCOME: 'OUTCOME_VALIDATED' }, PARTIALLY_COMPLETED: { VALIDATE_OUTCOME: 'OUTCOME_VALIDATED' }, MISSED: { VALIDATE_OUTCOME: 'OUTCOME_VALIDATED' }, CANCELLED: {}, OUTCOME_VALIDATED: {} };
const PROPOSAL = { DRAFT: { REVIEW: 'REVIEWED' }, REVIEWED: { SUBMIT: 'SUBMITTED', SUPERSEDE: 'SUPERSEDED' }, SUBMITTED: { EVALUATE: 'EVALUATING', SUPERSEDE: 'SUPERSEDED' }, EVALUATING: { ACCEPT_CONDITIONALLY: 'ACCEPTED_CONDITIONALLY', REQUIRE_CONFIRMATION: 'CONFIRMATION_REQUIRED', ACCEPT: 'ACCEPTED', REJECT: 'REJECTED', DEFER: 'DEFERRED' }, ACCEPTED_CONDITIONALLY: { REQUIRE_CONFIRMATION: 'CONFIRMATION_REQUIRED', ACCEPT: 'ACCEPTED', REJECT: 'REJECTED' }, CONFIRMATION_REQUIRED: { ACCEPT: 'ACCEPTED', REJECT: 'REJECTED', DEFER: 'DEFERRED' }, ACCEPTED: { SUPERSEDE: 'SUPERSEDED' }, REJECTED: {}, DEFERRED: { REEVALUATE: 'EVALUATING', SUPERSEDE: 'SUPERSEDED' }, SUPERSEDED: {} };

export const transitionLiveSession = (state, action) => move(SESSION, state, action, 'INVALID_LIVE_SESSION_TRANSITION');
export const transitionSessionArtifact = (state, action) => move(ARTIFACT, state, action, 'INVALID_ARTIFACT_TRANSITION');
export const transitionLiveConsent = (state, action) => move(CONSENT, state, action, 'INVALID_CONSENT_TRANSITION');
export const transitionLiveCommitment = (state, action) => move(COMMITMENT, state, action, 'INVALID_COMMITMENT_TRANSITION');
export const transitionBusinessEngineProposal = (state, action) => move(PROPOSAL, state, action, 'INVALID_PROPOSAL_TRANSITION');
export const LIVE_SESSION_TRANSITION_MAP = deepFreeze({ session: SESSION, artifact: ARTIFACT, consent: CONSENT, commitment: COMMITMENT, proposal: PROPOSAL });
