import { NEW_BOS_DEPTH_CONTRACT_VERSION } from './constants.js';

const confidence = 'STRONGLY_SUPPORTED';

function evidence(evidenceId, epistemicClass, sourceRef, exactContent) {
  return { evidence_id: evidenceId, epistemic_class: epistemicClass, source_ref: sourceRef, exact_content: exactContent };
}

function inference({ id, statement, evidenceRefs, counterevidenceRefs = [], confidenceState = confidence, falsifier, ...rest }) {
  return {
    id,
    statement,
    evidence_refs: evidenceRefs,
    counterevidence_refs: counterevidenceRefs,
    confounds: rest.confounds || [],
    confidence: confidenceState,
    what_would_change_it: falsifier,
    ...rest,
  };
}

function bounded({ confidenceState = confidence, evidenceRefs, counterevidenceRefs = [], falsifier, ...meaning }) {
  return {
    ...meaning,
    confidence: confidenceState,
    evidence_refs: evidenceRefs,
    counterevidence_refs: counterevidenceRefs,
    confounds: meaning.confounds || [],
    falsifier,
  };
}

const RAW = {
  version: 'synthetic_raw_evidence_v1',
  synthetic: true,
  subject_token: 'SYNTH-PDNV1-MOSAIC',
  source_artifact_ids: ['fixture_mosaic_assessment_v1', 'fixture_mosaic_history_v1', 'fixture_mosaic_observer_v1'],
  identity_context: {
    display_name: 'Mosaic',
    role: 'Fictional museum exhibition producer',
    context: 'Deliberately rich synthetic validation fixture; every person, episode, outcome, and quotation is fictional.',
  },
  scores: {
    command: 69,
    tempo: 64,
    relational_awareness: 77,
    precision: 74,
    leverage: 48,
    adaptability: 83,
    structure: 66,
    perspective: 88,
  },
  score_source_refs: Object.fromEntries([
    'command', 'tempo', 'relational_awareness', 'precision', 'leverage', 'adaptability', 'structure', 'perspective',
  ].map((id) => [id, ['fixture_mosaic_assessment_v1']])),
  questions: [
    { question_id: 'q01', exact_question: 'How do you begin a complex exhibition?', exact_answer: 'I find the visitor journey and the immovable date, then build a loose frame around the decisions that cannot drift.' },
    { question_id: 'q02', exact_question: 'Describe a meaningful course correction.', exact_answer: 'A visitor test showed the opening story was beautiful but confusing, so I moved the strongest object earlier and rewrote the sequence that night.' },
    { question_id: 'q03', exact_question: 'What do you do when a collaborator misses a handoff?', exact_answer: 'I usually make the missing bridge myself so the whole installation does not stall, then I explain the gap afterward.' },
    { question_id: 'q04', exact_question: 'What happens under deadline pressure?', exact_answer: 'I become much more directive, shorten the room, and assign concrete checklists. It works, but people can stop telling me what they still see.' },
    { question_id: 'q05', exact_question: 'How do you repair after a tense push?', exact_answer: 'I walk the space with the person, explain what I was protecting, ask what I closed down, and decide what must change before the next build.' },
    { question_id: 'q06', exact_question: 'What communication feedback have you received?', exact_answer: 'People say I make the whole story visible and remember their constraints. They also say my calm can hide that I have already made a decision.' },
    { question_id: 'q07', exact_question: 'What work gives you energy?', exact_answer: 'The point where many disciplines suddenly become one experience. Endless cleanup after opening drains me much more than the opening week itself.' },
    { question_id: 'q08', exact_question: 'How do you solve an unfamiliar problem?', exact_answer: 'I put the facts, unknowns, audiences, and sequence on a wall, look for the dependency that changes the rest, then test the story with someone outside the project.' },
    { question_id: 'q09', exact_question: 'What do you want to change in the next year?', exact_answer: 'I want junior producers to own more integration decisions without lowering the coherence of the final experience.' },
    { question_id: 'q10', exact_question: 'Where are you inconsistent?', exact_answer: 'I love a good plan, but I will break it instantly if the visitor experience says the plan is wrong.' },
    { question_id: 'q11', exact_question: 'What role conditions matter?', exact_answer: 'I need authority over the whole experience and a production partner who owns recurring logistics. If I own both, integration gets crowded by administration.' },
    { question_id: 'q12', exact_question: 'What should this map not claim?', exact_answer: 'It should not pretend to know how I recover outside project cycles or how I would perform in a role with no public-facing creative outcome.' },
  ],
  structured_inputs: [
    { field: 'fictional_projects_completed', exact_value: 4 },
    { field: 'fictional_time_window_months', exact_value: 18 },
    { field: 'role_demand_supplied', exact_value: true },
    { field: 'external_observer_packet_supplied', exact_value: true },
  ],
  evidence: [
    evidence('m01', 'self_report', 'q01', 'Begins with visitor journey and immovable date, then frames non-drifting decisions.'),
    evidence('m02', 'observed_history', 'q02', 'Reordered an exhibition sequence after a fictional visitor test revealed confusion.'),
    evidence('m03', 'self_report', 'q03', 'Often fills a missed integration handoff personally and discusses the gap later.'),
    evidence('m04', 'self_report', 'q04', 'Reports becoming more directive and checklist-oriented under deadline pressure.'),
    evidence('m05', 'self_report', 'q05', 'Uses a walk-through, explicit intent, impact inquiry, and next-cycle adjustment for repair.'),
    evidence('m06', 'observed_history', 'q06', 'Fictional collaborators report visible whole-story synthesis and remembered constraints.'),
    evidence('m07', 'counterevidence', 'q06', 'Fictional collaborators also report that calm delivery can obscure a settled decision.'),
    evidence('m08', 'self_report', 'q07', 'Integration moments activate effort; prolonged post-opening cleanup depletes it.'),
    evidence('m09', 'observed_history', 'q08', 'Uses a wall map of facts, unknowns, audiences, and sequence to isolate dependencies.'),
    evidence('m10', 'outcome_evidence', 'fixture_mosaic_history_v1:project_02', 'An outsider test identified a narrative gap before fictional fabrication was locked.'),
    evidence('m11', 'direct_fact', 'q09', 'Explicit goal is to transfer integration decisions to junior producers without losing coherence.'),
    evidence('m12', 'contradiction', 'q10', 'Values plans and deliberately breaks them when live experience contradicts the plan.'),
    evidence('m13', 'direct_fact', 'q11', 'Role demand includes whole-experience authority and a separate logistics partner.'),
    evidence('m14', 'outcome_evidence', 'fixture_mosaic_history_v1:cohort', 'Four fictional projects across eighteen months reached opening with documented postmortems.'),
    evidence('m15', 'counterevidence', 'fixture_mosaic_history_v1:project_04', 'On one fictional project, the team integrated late changes without the subject taking over.'),
    evidence('m16', 'observed_history', 'fixture_mosaic_observer_v1:episode_03', 'A fictional junior producer used an explicit coherence test to decide a handoff without escalation.'),
    evidence('m17', 'unknown', 'q12', 'No non-project recovery history or role evidence outside public-facing creative production.'),
    evidence('m18', 'outcome_evidence', 'fixture_mosaic_history_v1:project_03', 'A fictional pressure checklist protected the opening date but two concerns surfaced only after installation.'),
    evidence('m19', 'self_report', 'q03:q09', 'Wants distributed ownership while repeatedly absorbing integration gaps personally.'),
    evidence('m20', 'observed_history', 'fixture_mosaic_history_v1:project_01', 'A documented fictional postmortem changed the next project handoff sequence.'),
  ],
  contradictions: [
    { contradiction_id: 'mc01', evidence_refs: ['m01', 'm02', 'm12'], statement: 'A strong planning frame coexists with rapid willingness to break the plan when live experience disagrees.' },
    { contradiction_id: 'mc02', evidence_refs: ['m03', 'm11', 'm19'], statement: 'Distributed ownership is a stated goal while integration gaps are still often absorbed personally.' },
  ],
  uncertainties: [
    'External evidence covers only one fictional creative-production domain.',
    'No non-project recovery or wellbeing history is supplied.',
    'The eighteen-month record supports repeated work behavior but not a stable whole-life energy trajectory.',
  ],
  abstentions: [
    'No IQ, clinical, protected-trait, or broad intelligence claim.',
    'No whole-life energy trajectory.',
    'No role-fit claim outside evidence-bearing public-facing creative production.',
    'No claim that every collaborator experiences the same interpersonal impact.',
  ],
};

const topology = [
  inference({ id: 'mt01', statement: 'Long-horizon framing and live adaptation cooperate: the destination stays stable while sequence remains revisable.', evidenceRefs: ['m01', 'm02', 'm10', 'm12'], confidenceState: confidence, falsifier: 'Repeated cases where protecting the plan takes priority over contradictory visitor evidence.', dimensions: ['perspective', 'adaptability', 'structure', 'precision'], dynamic_roles: ['initiating_driver', 'contextual_moderator', 'boundary_regulator', 'quality_qualifier'] }),
  inference({ id: 'mt02', statement: 'Relational sensing qualifies directive authority until deadline pressure narrows the available communication bandwidth.', evidenceRefs: ['m04', 'm05', 'm06', 'm07', 'm18'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Pressure observations showing unchanged listening bandwidth and equally visible dissent.', dimensions: ['relational_awareness', 'command', 'tempo'], dynamic_roles: ['quality_qualifier', 'initiating_driver', 'sequencing_regulator'] }),
  inference({ id: 'mt03', statement: 'Moderate leverage is compensated by personal integration work rather than assumed delegation.', evidenceRefs: ['m03', 'm11', 'm16', 'm19'], counterevidenceRefs: ['m15'], confidenceState: confidence, falsifier: 'Three consecutive late integration decisions resolved by other owners without escalation.', dimensions: ['leverage', 'precision', 'relational_awareness'], dynamic_roles: ['delayed_capability', 'quality_qualifier', 'contextual_moderator'] }),
  inference({ id: 'mt04', statement: 'Structure functions as a coherence frame, not a fixed route.', evidenceRefs: ['m01', 'm02', 'm12', 'm20'], confidenceState: confidence, falsifier: 'Comparable projects where procedures are preserved despite strong evidence that the experience is failing.', dimensions: ['structure', 'adaptability', 'perspective'], dynamic_roles: ['boundary_regulator', 'contextual_moderator', 'initiating_driver'] }),
];

const attributes = [
  inference({ id: 'ma01', statement: 'Integrative sequencing is supported across multiple fictional production episodes.', evidenceRefs: ['m01', 'm02', 'm09', 'm10', 'm14'], confidenceState: confidence, falsifier: 'Independent project evidence showing repeated loss of critical dependencies or narrative order.', subdimensions: { system_mapping: 'supported', sequencing: 'strongly_supported', transfer: 'developing' } }),
  inference({ id: 'ma02', statement: 'Decision speed rises when the cost of delay becomes concrete and an experience-level principle is available.', evidenceRefs: ['m01', 'm02', 'm04', 'm18'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'High-cost decisions remaining delayed even when a governing experience principle is explicit.', subdimensions: { activation_speed: 'context_sensitive', pressure_narrowing: 'supported' } }),
  inference({ id: 'ma03', statement: 'Relational calibration is active but can be overruled by coherence protection under deadline pressure.', evidenceRefs: ['m04', 'm05', 'm06', 'm07', 'm18'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Observer evidence that dissent stays equally available during deadline compression.', subdimensions: { signal_use: 'strongly_supported', impact_visibility: 'variable' } }),
  inference({ id: 'ma04', statement: 'Transferable judgment is emerging but not yet reliable across repeated integration decisions.', evidenceRefs: ['m11', 'm15', 'm16', 'm19'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'A sustained run of junior-owned integration decisions with no coherence regression or hidden subject correction.', subdimensions: { explicit_rule_transfer: 'emerging', independent_execution: 'mixed' } }),
];

const dynamics = [
  inference({ id: 'md01', statement: 'A stable experience principle creates enough structure for rapid local improvisation.', evidenceRefs: ['m01', 'm02', 'm10', 'm12'], confidenceState: confidence, falsifier: 'Successful adaptation repeatedly occurring without any stable experience principle.', trigger: 'complex multi-disciplinary ambiguity', private_calculation: 'Protect what the visitor must understand; let the route change.', action: 'name the experience invariant and keep execution revisable', payoff: 'coherence without rigidity', delayed_cost: 'the governing principle may remain held by one integrator' }),
  inference({ id: 'md02', statement: 'When a handoff threatens whole-system coherence, personal gap-filling restores progress and quietly teaches the system to return integration debt to the same person.', evidenceRefs: ['m03', 'm11', 'm19'], counterevidenceRefs: ['m15', 'm16'], confidenceState: confidence, falsifier: 'Three comparable gaps resolved by the named owner using explicit coherence rules.', trigger: 'late or incomplete integration handoff', private_calculation: 'Fix the bridge now so every other contributor can keep moving.', action: 'complete the missing integration work personally', payoff: 'schedule and relationships are protected', delayed_cost: 'integration judgment and invisible workload stay centralized' }),
  inference({ id: 'md03', statement: 'Deadline pressure narrows inclusive synthesis into directive sequencing, protecting execution while reducing the visibility of unfinished concerns.', evidenceRefs: ['m04', 'm07', 'm18'], confidenceState: confidence, falsifier: 'Pressure observations showing broad input remains visible without schedule loss.', trigger: 'immovable opening date plus unresolved dependencies', private_calculation: 'The room now needs sequence more than another round of interpretation.', action: 'shorten discussion and assign explicit checklists', payoff: 'coordination accelerates', delayed_cost: 'important dissent may arrive after installation' }),
  inference({ id: 'md04', statement: 'Repair restores relationship and learning when intent, impact, and next-cycle structure are all made explicit.', evidenceRefs: ['m05', 'm20'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Repeated repair conversations that feel complete but do not alter the next project sequence.', trigger: 'post-pressure relational residue', private_calculation: 'The opening can be protected without making the pressure pattern the permanent way of working.', action: 'walk through intent, closed input, and structural change', payoff: 'trust and learning reopen', delayed_cost: 'repair remains expensive if pressure design is unchanged' }),
  inference({ id: 'md05', statement: 'Public integration activates effort, while low-meaning cleanup depletes it; recovery appears context-bound rather than globally established.', evidenceRefs: ['m08', 'm14', 'm17'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Repeated evidence of equal activation during maintenance-only periods or sustained depletion across contexts.', trigger: 'transition between integrative production and repetitive cleanup', private_calculation: 'The hard build is worth the effort when the whole experience is becoming visible.', action: 'increase effort around integrative milestones and withdraw during prolonged residue work', payoff: 'high-value convergence receives energy', delayed_cost: 'maintenance debt can accumulate after the visible win' }),
];

const specialist = {
  version: NEW_BOS_DEPTH_CONTRACT_VERSION,
  recognition: {
    mechanisms: [
      bounded({ label: 'Frame, then improvise', explanation: 'A stable experience principle reduces the number of things that must remain fixed, allowing rapid adaptation without losing the story.', evidenceRefs: ['m01', 'm02', 'm10', 'm12'], falsifier: 'Adaptations that repeatedly lose coherence despite a clear experience principle.' }),
      bounded({ label: 'Quiet integration tax', explanation: 'When a bridge is missing, personal gap-filling protects the whole and hides where the system failed to carry integration.', evidenceRefs: ['m03', 'm11', 'm19'], counterevidenceRefs: ['m15', 'm16'], falsifier: 'Repeated owner-led resolutions using transferred coherence rules.' }),
      bounded({ label: 'Pressure compression', explanation: 'At a hard deadline, inclusive synthesis narrows into sequence and control; execution improves while dissent visibility falls.', evidenceRefs: ['m04', 'm07', 'm18'], falsifier: 'Comparable deadline episodes with broad input and no coordination loss.' }),
      bounded({ label: 'Repair through shared reconstruction', explanation: 'Repair is not reassurance alone; it reconstructs intent, impact, and the next operating rule.', evidenceRefs: ['m05', 'm20'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Repair that does not change a later handoff or pressure sequence.' }),
    ],
    private_calculations: [
      'Protect what the visitor must understand; let the route change.',
      'Fix the missing bridge now so everyone else can keep moving.',
      'At this deadline, sequence may matter more than another interpretation round.',
      'Repair is complete only when the next build changes.',
    ],
    recognizable_moments: [
      'You can spend weeks building a plan and feel no loyalty to it once real experience proves it wrong.',
      'You notice a missing handoff early, quietly complete it, and only later realize the team never learned what you saw.',
      'Your calm can coexist with a decision that is already much further along internally than other people realize.',
    ],
    tensions: ['Coherence versus shared ownership', 'Inclusive sensing versus deadline compression', 'Meaningful integration versus maintenance residue'],
  },
  personality_dna: {
    coordinate_explanations: [
      { coordinate_id: 'command', label: 'Command', availability: 'Decisive when an experience principle or hard deadline makes the tradeoff concrete.', not_meaning: 'Not a need to dominate every room.', interaction: 'Relational sensing usually qualifies authority; pressure can temporarily narrow that qualification.', evidence_refs: ['m04', 'm05', 'm06', 'm18'], confidence: 'SUPPORTED_HYPOTHESIS' },
      { coordinate_id: 'tempo', label: 'Tempo', availability: 'Able to accelerate after the governing dependency becomes visible.', not_meaning: 'Not uniformly fast across every decision.', interaction: 'Perspective and Precision slow entry; Adaptability speeds revision.', evidence_refs: ['m01', 'm02', 'm09'], confidence: confidence },
      { coordinate_id: 'relational_awareness', label: 'Relational Awareness', availability: 'Tracks contributor constraints and how the whole will be received.', not_meaning: 'Not proof that every impact is correctly predicted.', interaction: 'Under deadline pressure, Command can outrun the normal listening bandwidth.', evidence_refs: ['m05', 'm06', 'm07', 'm18'], confidence: confidence },
      { coordinate_id: 'precision', label: 'Precision', availability: 'Protects narrative and production details that alter the visitor experience.', not_meaning: 'Not equal attention to every detail.', interaction: 'Perspective decides which details are consequential; Adaptability permits revision.', evidence_refs: ['m02', 'm09', 'm10'], confidence: confidence },
      { coordinate_id: 'leverage', label: 'Leverage', availability: 'Can transfer judgment when the coherence rule is explicit.', not_meaning: 'Not evidence of effortless delegation.', interaction: 'Relational care and Precision can pull integration work back toward personal ownership.', evidence_refs: ['m03', 'm11', 'm15', 'm16'], confidence: 'SUPPORTED_HYPOTHESIS' },
      { coordinate_id: 'adaptability', label: 'Adaptability', availability: 'Revises route quickly when lived experience conflicts with the plan.', not_meaning: 'Not a lack of commitment.', interaction: 'A stable long-horizon experience principle makes flexibility safe.', evidence_refs: ['m01', 'm02', 'm12'], confidence: confidence },
      { coordinate_id: 'structure', label: 'Structure', availability: 'Builds decision frames, handoff sequences, and pressure checklists.', not_meaning: 'Not attachment to a fixed procedure.', interaction: 'Adaptability keeps the frame responsive; Precision makes it usable.', evidence_refs: ['m01', 'm04', 'm12', 'm20'], confidence: confidence },
      { coordinate_id: 'perspective', label: 'Perspective', availability: 'Holds the whole audience journey and downstream consequence while local work changes.', not_meaning: 'Not perfect foresight.', interaction: 'Organizes Precision, Structure, and Adaptability around one governing experience.', evidence_refs: ['m01', 'm02', 'm09', 'm10'], confidence: confidence },
    ],
    topology_summary: 'A stable long-horizon frame coordinates adaptability, precision, and relational sensing. The central developmental edge is transferring that integrative frame without centralizing every bridge.',
    speed: 'Context-sensitive acceleration after the decisive dependency is visible.',
    temperature: 'Warm and composed at baseline; cooler and more directive under deadline compression.',
  },
  operating_engine: {
    loop: ['Frame the experience', 'Map dependencies', 'Invite disciplines', 'Test with reality', 'Revise the route', 'Integrate the handoff', 'Capture the lesson'],
    mechanisms: [
      bounded({ label: 'Experience invariant', explanation: 'Names what must remain true for the audience, then lets local plans change around it.', evidenceRefs: ['m01', 'm02', 'm12'], falsifier: 'Projects where no stable audience principle guides revision.' }),
      bounded({ label: 'Dependency wall', explanation: 'Makes facts, unknowns, audiences, and sequence visible to locate the decision that changes the rest.', evidenceRefs: ['m09', 'm10'], falsifier: 'Comparable problems solved without mapping or external testing.' }),
      bounded({ label: 'Integration handoff', explanation: 'Combines many specialist contributions into one coherent public experience; transfer is possible when the test is explicit.', evidenceRefs: ['m11', 'm15', 'm16'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Transferred rules that repeatedly protect process but lose experience coherence.' }),
    ],
  },
  people_experience: {
    states: [
      bounded({ label: 'First impression', hypothesis: 'Likely composed, attentive to the whole, and already mapping relationships among the parts.', evidenceRefs: ['m06'], confidenceState: 'TENTATIVE', falsifier: 'Multiple independent first-impression accounts that do not include composure or integrative attention.' }),
      bounded({ label: 'Comfortable collaboration', hypothesis: 'People may feel remembered because constraints and contributions are carried into the whole story.', evidenceRefs: ['m06'], falsifier: 'Observer accounts showing constraints are routinely forgotten or overridden.' }),
      bounded({ label: 'Excited state', hypothesis: 'Energy becomes more visible when many disciplines converge into one public experience.', evidenceRefs: ['m08'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Repeated low activation during integrative milestones.' }),
      bounded({ label: 'Pressure state', hypothesis: 'Calm delivery may make a directive decision feel less visibly closed than it actually is.', evidenceRefs: ['m04', 'm07', 'm18'], falsifier: 'Observers consistently report knowing exactly what remains open during deadline pressure.' }),
      bounded({ label: 'After repair', hypothesis: 'Trust may recover through concrete reconstruction of intent, impact, and next-cycle design.', evidenceRefs: ['m05', 'm20'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Later collaborators report repair conversations without changed behavior or restored candor.' }),
    ],
    observer_boundary: 'These are bounded hypotheses from a small fictional observer packet, not universal facts about how people experience this subject.',
  },
  communication: {
    speed: 'Moderate until the governing dependency is clear; fast once the decision frame is stable.',
    temperature: 'Warm, composed, and context-rich at baseline; cooler and more directive under immovable deadlines.',
    dimensions: [
      bounded({ label: 'Speed', continuum: 'Deliberate framing → rapid convergence', interpretation: 'Slower while mapping the whole; faster after the critical dependency becomes visible.', evidenceRefs: ['m01', 'm04', 'm09'], falsifier: 'Stable conversational speed regardless of ambiguity or deadline.' }),
      bounded({ label: 'Temperature', continuum: 'Warm contextual inclusion → cool directive focus', interpretation: 'Usually carries human context; pressure can reduce affective and explanatory bandwidth.', evidenceRefs: ['m04', 'm05', 'm06'], falsifier: 'Observer evidence that pressure increases emotional signaling or warmth.' }),
      bounded({ label: 'Directness', continuum: 'Invitational exploration → decided sequence', interpretation: 'Invites disciplines during framing, then can sound final before the room knows the choice has closed.', evidenceRefs: ['m06', 'm07'], falsifier: 'Observers consistently identify decision closure at the same moment as the subject.' }),
      bounded({ label: 'Listening', continuum: 'Constraint gathering → narrowed input', interpretation: 'Listens for what changes the whole; deadline compression can shrink the channel for unfinished concerns.', evidenceRefs: ['m04', 'm06', 'm18'], falsifier: 'Pressure observations with equal surfacing of unfinished concerns.' }),
      bounded({ label: 'Processing latency', continuum: 'Visible wall-mapping → quick internal integration', interpretation: 'Makes complex reasoning visible early, but later integration can advance internally between meetings.', evidenceRefs: ['m09', 'm07'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Observers report all major integration steps remain shared and visible.' }),
      bounded({ label: 'Detail and abstraction', continuum: 'Whole-story principle ↔ consequential detail', interpretation: 'Moves between the audience-level story and the details that materially change it.', evidenceRefs: ['m02', 'm09', 'm10'], falsifier: 'Repeated fixation on detail without story relevance or abstraction without implementation accuracy.' }),
      bounded({ label: 'Emotional signaling', continuum: 'Composed care → hidden urgency', interpretation: 'Composure protects the room but can conceal how urgent or settled the internal calculation has become.', evidenceRefs: ['m06', 'm07'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Observers reliably detect urgency and closure without explicit labeling.' }),
      bounded({ label: 'Persuasion', continuum: 'Shared experience logic → directive sequencing', interpretation: 'Most persuasive when others can see the visitor consequence behind a decision.', evidenceRefs: ['m01', 'm06', 'm10'], falsifier: 'Decisions gain support equally without an experience-level rationale.' }),
      bounded({ label: 'Disagreement and conflict', continuum: 'Integrative inquiry → deadline closure', interpretation: 'Can explore competing views until time pressure converts the conflict into a sequence problem.', evidenceRefs: ['m04', 'm18'], falsifier: 'Conflict remains exploratory under comparable deadline stakes.' }),
      bounded({ label: 'Repair', continuum: 'Explanation → shared reconstruction', interpretation: 'Strongest repair names what was protected, what input closed, and what structure changes next time.', evidenceRefs: ['m05', 'm20'], falsifier: 'Repair without structural change produces equally durable recovery.' }),
      bounded({ label: 'Audience and channel calibration', continuum: 'Discipline-specific detail → whole-story translation', interpretation: 'Adapts the same governing experience to specialist and outsider audiences.', evidenceRefs: ['m06', 'm10'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Outsider tests repeatedly fail because specialist framing is not translated.' }),
    ],
  },
  strengths_vulnerabilities: {
    mechanisms: [
      bounded({ strength: 'Whole-experience integration', immediate_payoff: 'Many specialist contributions become one legible public experience.', reinforcement: 'The project moves and collaborators feel their constraints were remembered.', delayed_cost: 'Integration gaps are increasingly routed back to the same person.', conditions: 'Multi-disciplinary work with a visible experience outcome.', evidenceRefs: ['m03', 'm06', 'm10', 'm19'], counterevidenceRefs: ['m15', 'm16'], falsifier: 'Integration stays coherent across several projects without personal centralization.' }),
      bounded({ strength: 'Adaptive precision', immediate_payoff: 'The plan changes quickly without abandoning consequential quality.', reinforcement: 'Live tests improve the work before costly lock-in.', delayed_cost: 'Teams may wait for the integrator to decide which details are truly consequential.', conditions: 'A stable experience principle plus fresh user evidence.', evidenceRefs: ['m02', 'm09', 'm10', 'm12'], falsifier: 'Other owners apply the quality threshold independently across repeated changes.' }),
      bounded({ strength: 'Composed deadline direction', immediate_payoff: 'A pressured room receives sequence, ownership, and a protected opening date.', reinforcement: 'The immediate crisis resolves.', delayed_cost: 'Unfinished concerns can disappear until after installation.', conditions: 'Immovable date and unresolved dependencies.', evidenceRefs: ['m04', 'm18'], falsifier: 'Comparable pressure episodes show all material dissent stays visible.' }),
    ],
  },
  pressure_conflict: {
    baseline: 'Context-rich integration with visible relationship and audience constraints.',
    pressure_state: 'Directive sequencing, shorter explanation, narrower listening, and concrete checklists.',
    recovery: 'Walk the work together; distinguish intent from impact; reopen closed input; change the next handoff.',
    transformations: [
      bounded({ label: 'Narrowing', baseline: 'Several disciplines remain in the room as the story is integrated.', pressure_expression: 'Only the critical path and immovable decisions remain active.', recovery: 'Restore excluded concerns after immediate stability returns.', evidenceRefs: ['m04', 'm18'], falsifier: 'Comparable deadlines show no reduction in active perspectives.' }),
      bounded({ label: 'Trained opposite-pole behavior', baseline: 'Influence is usually contextual and integrative.', pressure_expression: 'Authority becomes explicit, directive, and checklist-led.', recovery: 'Return authority to shared sense-making with clear boundaries.', evidenceRefs: ['m04', 'm05'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Pressure behavior remains equally invitational and non-directive.' }),
      bounded({ label: 'Compensation collapse', baseline: 'Relational sensing softens and calibrates decisions.', pressure_expression: 'The sensing remains internally active but is less available in the conversation.', recovery: 'Ask what became hard to say and what signal was missed.', evidenceRefs: ['m05', 'm07', 'm18'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Observers report equal permission to surface incomplete concerns under pressure.' }),
    ],
    conflict_entry: 'Usually through a consequence, dependency, or audience risk rather than personal opposition.',
    judgment_effect: 'The decision frame gets narrower and more sequential.',
    relational_effect: 'People may comply while withholding unfinished concern.',
  },
  work_environment: {
    demands: [
      bounded({ demand: 'Ambiguity', natural_fit: 'High when there is a meaningful public outcome to organize around.', adaptation_cost: 'Rises when no governing experience or decision authority exists.', sustainability: 'Strong with a clear invariant and testable feedback.', evidenceRefs: ['m01', 'm02', 'm09'], falsifier: 'Comparable ambiguous work without an audience outcome remains equally activating and effective.' }),
      bounded({ demand: 'Collaboration', natural_fit: 'High across distinct disciplines when their constraints can be integrated.', adaptation_cost: 'Rises when contributions have no explicit handoff or decision boundary.', sustainability: 'Strong if integration responsibility is distributed.', evidenceRefs: ['m03', 'm06', 'm16'], falsifier: 'Cross-disciplinary work repeatedly produces fragmentation despite explicit handoffs.' }),
      bounded({ demand: 'Pace', natural_fit: 'Variable: deliberate during framing, fast near irreversible milestones.', adaptation_cost: 'Chronic urgency collapses listening and increases hidden integration load.', sustainability: 'Best with staged deadlines rather than continuous emergency.', evidenceRefs: ['m01', 'm04', 'm18'], falsifier: 'Continuous urgency produces no listening loss or additional integration load.' }),
      bounded({ demand: 'Structure', natural_fit: 'Uses structure to protect what cannot drift while leaving execution revisable.', adaptation_cost: 'Rigid procedure without feedback feels expensive and may be bypassed.', sustainability: 'Strong when structure captures learning between cycles.', evidenceRefs: ['m01', 'm12', 'm20'], falsifier: 'Fixed procedure is consistently preferred despite contradictory live evidence.' }),
      bounded({ demand: 'Ownership', natural_fit: 'Strong for whole-experience coherence and consequential integration decisions.', adaptation_cost: 'Too broad when recurring logistics and integration both stay in the same seat.', sustainability: 'Requires a logistics partner and transferred judgment.', evidenceRefs: ['m11', 'm13', 'm19'], falsifier: 'Owning both logistics and integration remains sustainable across repeated cycles.' }),
      bounded({ demand: 'Repetition and maintenance', natural_fit: 'Useful when maintenance clearly protects the experience.', adaptation_cost: 'High for prolonged residue work after the public milestone.', sustainability: 'Needs explicit maintenance ownership and closure criteria.', evidenceRefs: ['m08', 'm17'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Maintenance-only periods show stable activation and no accumulating cleanup debt.' }),
    ],
    fit_summary: 'Most natural in consequential, multi-disciplinary environments where a public experience must stay coherent while reality changes the route.',
    friction_summary: 'Persistent maintenance, unclear integration authority, and chronic emergency create the highest adaptation cost.',
  },
  role_seat: {
    selected_fit: 'NATURAL_FIT',
    selected_configuration: 'Whole-experience integrator with explicit decision rights and a separate production-operations partner.',
    fit_states: [
      bounded({ fit_class: 'Natural Fit', role_configuration: 'Experience integrator with whole-story authority and staged public feedback.', reasoning: 'Matches repeated evidence for sequencing, live revision, and multi-disciplinary coherence.', evidenceRefs: ['m01', 'm02', 'm09', 'm10', 'm13', 'm14'], falsifier: 'Repeated failure to integrate disciplines or use public feedback under equivalent authority.' }),
      bounded({ fit_class: 'Adaptable Fit', role_configuration: 'Program lead with integration authority plus strong operational scaffolding.', reasoning: 'Can carry broader accountability if recurring logistics have a clear partner and decision rails.', evidenceRefs: ['m11', 'm13', 'm16'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Operational scaffolding fails to reduce hidden integration load.' }),
      bounded({ fit_class: 'Compensated Fit', role_configuration: 'Operations-heavy producer who also owns creative integration.', reasoning: 'Quality can be sustained through extra personal effort, but administration crowds the integrative contribution.', evidenceRefs: ['m08', 'm13', 'm19'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Several cycles show equal energy, quality, and distributed ownership while both responsibilities remain combined.' }),
      bounded({ fit_class: 'Seat Risk', role_configuration: 'Maintenance-only administrator with little audience feedback or integration authority.', reasoning: 'The evidence suggests high depletion and low access to the mechanism that activates contribution.', evidenceRefs: ['m08', 'm13', 'm17'], confidenceState: 'TENTATIVE', falsifier: 'Sustained effectiveness and activation in comparable maintenance-only work.' }),
    ],
    scaffolding: ['Separate recurring logistics ownership', 'Explicit coherence tests for junior producers', 'Staged visitor feedback before fabrication lock', 'Pressure protocol that preserves a dissent channel'],
    plural_success_note: 'Multiple successful seats remain possible when the whole-experience authority, feedback loop, and integration-support conditions are preserved.',
    review_trigger: 'Review after three junior-owned integration decisions or a role shift away from public-facing creative outcomes.',
  },
  leadership: {
    pattern: 'Creates shared meaning and cross-disciplinary coherence; under pressure can centralize sequence and reduce upward signal.',
    transfer_gap: 'The governing experience test is not yet consistently available to other decision owners.',
    complementary_team_effect: 'A production-operations partner protects recurring logistics while junior integrators practice bounded judgment.',
    evidence_refs: ['m06', 'm11', 'm13', 'm16', 'm18', 'm19'],
    confidence: 'SUPPORTED_HYPOTHESIS',
    falsifier: 'Team evidence that authority distribution does not improve signal flow or independent integration judgment.',
  },
  cognition: {
    boundary: 'These are task-specific process indicators, not IQ, rank, or universal aptitude claims.',
    indicators: [
      bounded({ indicator: 'Systems synthesis', task_demand: 'Integrate many specialist constraints into one public journey.', observed_process: 'Maps facts, unknowns, audiences, and sequence around a governing experience.', outcome: 'An outsider test finds narrative gaps before costly lock-in.', correction_transfer: 'Reorders the experience after feedback and records the learning.', assistance: 'Wall map and outsider test.', evidenceRefs: ['m09', 'm10', 'm20'], falsifier: 'Repeated inability to produce a coherent whole from equivalent specialist inputs.' }),
      bounded({ indicator: 'Problem decomposition', task_demand: 'Find the dependency that changes the rest of a complex build.', observed_process: 'Separates facts, unknowns, audiences, and sequence before choosing the next test.', outcome: 'Critical ambiguity becomes a bounded decision.', correction_transfer: 'Updates the sequence when the test changes the model.', assistance: 'Visible dependency map.', evidenceRefs: ['m01', 'm09', 'm10'], falsifier: 'Comparable problems remain undifferentiated despite mapping.' }),
      bounded({ indicator: 'Cognitive flexibility', task_demand: 'Revise an established plan after contradictory visitor evidence.', observed_process: 'Protects the experience principle and changes the route quickly.', outcome: 'The confusing opening is reorganized before fabrication lock.', correction_transfer: 'The postmortem changes a later handoff sequence.', assistance: 'Live visitor feedback.', evidenceRefs: ['m02', 'm10', 'm12', 'm20'], falsifier: 'Contradictory evidence repeatedly fails to change the plan.' }),
      bounded({ indicator: 'Transfer of judgment', task_demand: 'Enable another producer to decide an integration handoff.', observed_process: 'Makes the coherence test explicit rather than supplying the answer.', outcome: 'One fictional junior producer resolves a handoff independently.', correction_transfer: 'Promising but not yet replicated enough for a strong general claim.', assistance: 'Explicit coherence test and bounded decision rights.', evidenceRefs: ['m11', 'm16'], counterevidenceRefs: ['m03', 'm19'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Replicated handoffs still return to the subject despite explicit rules and authority.' }),
    ],
  },
  energy: {
    trait: { status: 'SUPPORTED_HYPOTHESIS', summary: 'Meaningful integration appears to make sustained effort more available.', evidence_refs: ['m08', 'm14'], confounds: ['All evidence comes from one fictional work domain.'], falsifier: 'Repeated low activation during integrative milestones.' },
    state: { status: 'TENTATIVE', summary: 'No current wellbeing or acute activation state is measured by this fixture.', evidence_refs: ['m17'], confounds: ['No current-state check-in.'], falsifier: 'A time-bounded current-state packet.' },
    context: { status: 'STRONGLY_SUPPORTED', summary: 'Energy rises during cross-disciplinary convergence and falls during prolonged maintenance residue.', evidence_refs: ['m08', 'm14'], confounds: ['Public recognition and deadline arousal may contribute.'], falsifier: 'Comparable maintenance periods with stable activation.' },
    trajectory: { status: 'INSUFFICIENT_EVIDENCE', summary: 'Eighteen months of work episodes do not establish a whole-life direction of travel.', evidence_refs: ['m14', 'm17'], confounds: ['Project cycle and life context are not separated.'], falsifier: 'Longitudinal, cross-context observations with repeated recovery measures.' },
    activation: 'Many disciplines becoming one coherent experience.',
    depletion: 'Prolonged post-milestone cleanup and invisible integration debt.',
    resilience: 'Task recovery is suggested by documented postmortems; broader resilience is not established.',
    recovery: 'Quiet walk-through, narrative reconstruction, and a changed next-cycle rule.',
  },
  five_futures: {
    items: [
      bounded({ future_identity: 'Distributed Integrator', condition: 'If junior producers receive explicit coherence tests and bounded decision rights', mechanism: 'The experience invariant travels before the answer does.', trajectory: 'Integration quality becomes less dependent on one person while the subject moves toward higher-leverage synthesis.', triggers: 'Three recurring handoff decisions are delegated.', indicators: 'Others name the tradeoff, decide, and preserve visitor coherence before escalating.', movers: 'Clear decision rights, postmortem feedback, and a logistics partner.', environmental_variables: 'Project complexity and junior-producer experience.', horizon: 'Three project cycles', review_trigger: 'After each independent integration decision', evidenceRefs: ['m11', 'm15', 'm16'], counterevidenceRefs: ['m03', 'm19'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Transferred decisions repeatedly require hidden correction or lose the governing experience.' }),
      bounded({ future_identity: 'Elegant Bottleneck', condition: 'If personal gap-filling remains the fastest way to protect coherence', mechanism: 'Immediate project relief reinforces centralized integration judgment.', trajectory: 'Public quality stays high while invisible workload and decision dependency accumulate.', triggers: 'Late handoffs, unclear ownership, and compressed schedules.', indicators: 'More bridges are completed privately; fewer problems are surfaced before the subject sees them.', movers: 'Ownership clarity, visible exception logs, and explicit transfer tests.', environmental_variables: 'Volume of simultaneous projects and handoff quality.', horizon: 'One to two project cycles', review_trigger: 'When the same integration class returns twice', evidenceRefs: ['m03', 'm19'], counterevidenceRefs: ['m15', 'm16'], confidenceState: confidence, falsifier: 'Project volume grows while integration remains distributed and hidden work does not rise.' }),
      bounded({ future_identity: 'Pressure Conductor', condition: 'If hard deadlines are paired with a protected dissent channel', mechanism: 'Directive sequencing preserves speed while one explicit route keeps unfinished concerns visible.', trajectory: 'Crisis authority becomes a bounded capability rather than a recurring communication tax.', triggers: 'Immovable opening dates and unresolved critical paths.', indicators: 'Checklist ownership rises without post-installation surprise concerns.', movers: 'Red-team checkpoint, decision-closure labels, and recovery review.', environmental_variables: 'Deadline rigidity and consequence of late change.', horizon: 'Next major opening', review_trigger: 'Within forty-eight hours of the pressure event', evidenceRefs: ['m04', 'm05', 'm18'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Protected dissent slows execution without improving issue visibility.' }),
      bounded({ future_identity: 'Maintenance Drain', condition: 'If public milestones remain personally owned while post-opening residue has no explicit owner', mechanism: 'Meaningful convergence receives energy; low-meaning cleanup accumulates after the visible win.', trajectory: 'Creative integration stays strong but recovery windows shrink and maintenance debt crowds the next cycle.', triggers: 'Back-to-back openings and ambiguous closure ownership.', indicators: 'Unfinished cleanup, lower patience after launch, and earlier withdrawal from maintenance work.', movers: 'Closure definition, maintenance owner, and protected recovery interval.', environmental_variables: 'Project cadence and operations support.', horizon: 'Six to twelve months', review_trigger: 'After two consecutive openings', evidenceRefs: ['m08', 'm14', 'm17'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Back-to-back cycles show stable activation, completed cleanup, and no recovery compression.' }),
      bounded({ future_identity: 'Learning Institution Builder', condition: 'If postmortems become shared operating infrastructure rather than private reflection', mechanism: 'Repair and course-correction rules compound across projects.', trajectory: 'The organization learns how to protect audience coherence, collaboration, and adaptation without relearning the same pressure lessons.', triggers: 'A project changes route or experiences a pressure rupture.', indicators: 'Later teams reuse a documented test before the subject intervenes.', movers: 'Shared decision library, cross-project review, and junior ownership.', environmental_variables: 'Continuity of the team and authority to change process.', horizon: 'Three to five project cycles', review_trigger: 'Quarterly across the fictional program', evidenceRefs: ['m02', 'm16', 'm20'], confidenceState: 'SUPPORTED_HYPOTHESIS', falsifier: 'Postmortems accumulate without changing later decisions or handoffs.' }),
    ],
  },
  one_move: bounded({
    target_mechanism: 'Personal gap-filling restores coherence and reinforces centralized integration judgment.',
    intervention: 'For the next three recurring integration decisions, give the owner the visitor-coherence test, the non-negotiable boundary, and authority to decide before Mosaic offers a solution.',
    rationale: 'The current edge is not less care or lower standards; it is discovering whether the governing judgment can travel without hidden correction.',
    strength_preserved: 'Whole-experience coherence and relational care.',
    expected_outcome: 'At least two decisions are made independently with a legible tradeoff and no material coherence regression.',
    burden: 'Requires defining the test early, tolerating a different route, and reviewing exceptions after the decision rather than before it.',
    risk: 'An owner may make a locally reasonable choice that exposes an incomplete rule.',
    reversibility: 'The experiment covers three bounded, non-safety-critical decisions and can stop after any material experience risk.',
    observable_result: 'The owner names the governing tradeoff, makes the call before escalation, and the visitor experience remains coherent at review.',
    horizon: 'Three recurring integration decisions or one project cycle, whichever comes first.',
    falsifier: 'Even with a clear test and real authority, decisions repeatedly require hidden correction or create material coherence loss.',
    stop_adjust_condition: 'Stop or narrow the decision class after one material public-experience risk; adjust the rule if two owners misread the same boundary.',
    alternatives_considered: ['Delegate more tasks without transferring the decision test', 'Keep all integration decisions centralized and hire administrative support', 'Transfer only after the full solution is already designed'],
    evidenceRefs: ['m03', 'm11', 'm15', 'm16', 'm19'],
    counterevidenceRefs: ['m15', 'm16'],
    confidenceState: 'SUPPORTED_HYPOTHESIS',
  }),
  validation: {
    claims: [
      bounded({ human_label: 'The frame-and-improvise pattern', claim: 'A stable audience principle supports rapid revision without loss of coherence.', inference_boundary: 'Strong across several fictional project episodes; still one domain.', evidenceRefs: ['m01', 'm02', 'm10', 'm12'], falsifier: 'Revisions repeatedly lose coherence despite a clear audience principle.', confidenceState: confidence }),
      bounded({ human_label: 'The quiet integration tax', claim: 'Missing bridges are often completed personally, protecting progress while centralizing judgment.', inference_boundary: 'Direct self-report plus goal tension; two counterexamples show transfer is possible.', evidenceRefs: ['m03', 'm19'], counterevidenceRefs: ['m15', 'm16'], falsifier: 'Three comparable gaps resolve without escalation or hidden correction.', confidenceState: confidence }),
      bounded({ human_label: 'The pressure narrowing hypothesis', claim: 'Deadline pressure increases directive sequence and reduces visible unfinished concern.', inference_boundary: 'Supported by one detailed fictional pressure episode; replication is needed.', evidenceRefs: ['m04', 'm07', 'm18'], falsifier: 'Comparable deadlines retain equal signal flow and discussion bandwidth.', confidenceState: 'SUPPORTED_HYPOTHESIS' }),
      bounded({ human_label: 'The repair mechanism', claim: 'Intent-impact reconstruction plus a changed next-cycle rule supports recovery.', inference_boundary: 'Supported by self-report and one later process change, not broad observer confirmation.', evidenceRefs: ['m05', 'm20'], falsifier: 'Repeated repairs do not change later behavior or trust.', confidenceState: 'SUPPORTED_HYPOTHESIS' }),
      bounded({ human_label: 'The role envelope', claim: 'Whole-experience integration fits best with explicit authority and separate recurring-logistics ownership.', inference_boundary: 'Bound to fictional public-facing creative production only.', evidenceRefs: ['m11', 'm13', 'm14'], falsifier: 'Comparable success and sustainability when integration authority is absent or logistics remains combined.', confidenceState: 'SUPPORTED_HYPOTHESIS' }),
      bounded({ human_label: 'The energy context', claim: 'Integrative convergence activates effort while prolonged cleanup depletes it.', inference_boundary: 'A context distinction, not a wellbeing or whole-life trajectory claim.', evidenceRefs: ['m08', 'm14', 'm17'], falsifier: 'Maintenance-only periods show equal activation and no residue debt.', confidenceState: 'SUPPORTED_HYPOTHESIS' }),
      bounded({ human_label: 'The open energy trajectory', claim: 'The direction of whole-life operating energy is not currently known.', inference_boundary: 'Explicit abstention until longitudinal cross-context evidence exists.', evidenceRefs: ['m14', 'm17'], falsifier: 'Repeated cross-context measures establish a stable direction of travel.', confidenceState: 'INSUFFICIENT_EVIDENCE' }),
    ],
    conflicts: ['A plan is valued and willingly broken.', 'Shared ownership is desired and integration gaps are still absorbed personally.'],
    what_would_change_the_map: ['Three owner-led integration decisions', 'Two independently observed deadline episodes', 'Cross-context recovery measures over time', 'A role episode outside public-facing creative production'],
  },
  operating_identity: {
    governing_logic: 'Create a stable frame for what the whole must mean, then improvise with reality until every part belongs to that whole.',
    memorable_use: 'When the work feels chaotic, ask what must stay true for the audience—and which decision test another person can now own.',
    not_a_type: 'This is a compact working model of governing logic, not a fixed personality category, score name, or promise about every context.',
    evidence_refs: ['m01', 'm02', 'm03', 'm09', 'm11', 'm12', 'm16'],
    confidence: 'SUPPORTED_HYPOTHESIS',
    falsifier: 'Cross-context evidence that stable framing, live adaptation, and integrative ownership do not organize the person’s behavior.',
  },
  visual_bos: {
    primary_pattern: 'Frame the whole',
    secondary_pattern: 'Adapt the route',
    tertiary_pattern: 'Carry human constraints',
    operating_core: 'Coherent improvisation',
    inputs: ['Audience meaning', 'Contributor constraints', 'Live feedback', 'Immovable milestones'],
    outputs: ['Integrated experience', 'Revised sequence', 'Visible decision frame', 'Cross-disciplinary coherence'],
    operating_loop: ['Frame', 'Map', 'Invite', 'Test', 'Revise', 'Integrate', 'Capture'],
    energy_source: 'Many disciplines becoming one coherent public experience.',
    fatigue_source: 'Prolonged cleanup and invisible integration debt after the visible milestone.',
    central_tension: 'Coherence versus shared ownership',
    transfer_gap: 'The governing experience test is not yet consistently available to other decision owners.',
    pressure_shift: 'Context-rich integration narrows into directive sequencing.',
    recovery_path: 'Reconstruct intent and impact, reopen signal, then change the next handoff.',
    environment_fit: 'Consequential multi-disciplinary work with a public feedback loop and clear integration authority.',
    environment_risk: 'Chronic emergency, maintenance-only ownership, or responsibility without whole-experience authority.',
    signals: ['A missing bridge is completed privately', 'A calm statement contains an already-closed decision', 'A junior owner names the coherence tradeoff before escalating', 'Cleanup remains ownerless after opening'],
  },
};

function richRendering({ eyebrow, headline, summary, evidenceRefs, ...rest }) {
  return { depth_contract: 'rich_surface_v1', eyebrow, headline, summary, evidence_refs: evidenceRefs, ...rest };
}

const renderings = {
  this_is_you: richRendering({
    eyebrow: 'Recognition',
    headline: 'You make complexity feel coherent by deciding what the whole must mean.',
    summary: 'You do not need every part to stay fixed. You need one clear experience-level principle, and once that is stable you can revise the route quickly. The hidden cost appears when a bridge is missing: you can see how to restore the whole so quickly that you complete the bridge before the system has to learn what you saw.',
    evidenceRefs: ['m01', 'm02', 'm03', 'm09', 'm10', 'm12', 'm19'],
    recognizable_moments: specialist.recognition.recognizable_moments,
    mechanisms: specialist.recognition.mechanisms,
    private_calculations: specialist.recognition.private_calculations,
    tensions: specialist.recognition.tensions,
  }),
  personality_dna: richRendering({
    eyebrow: 'The architecture underneath',
    headline: 'A long-view frame makes precision and improvisation work together.',
    summary: 'The contour is not a type. It is a map of eight behavioral priors whose meaning changes through interaction: Perspective organizes the whole, Adaptability keeps the route responsive, Precision protects consequential detail, and Relational Awareness carries contributor and audience signal. The key constraint is not flexibility; it is whether the frame can travel.',
    evidenceRefs: ['m01', 'm02', 'm03', 'm04', 'm06', 'm09', 'm10', 'm12', 'm16'],
    coordinate_explanations: specialist.personality_dna.coordinate_explanations,
    topology_summary: specialist.personality_dna.topology_summary,
    speed: specialist.personality_dna.speed,
    temperature: specialist.personality_dna.temperature,
  }),
  how_you_operate: richRendering({
    eyebrow: 'Human engine',
    headline: 'Frame the experience, expose the dependency, test it, then revise without ceremony.',
    summary: 'Your engine is neither pure planning nor pure improvisation. You create a frame tight enough to coordinate the work and loose enough to learn from reality. Execution is strongest when the decision test and owner are visible; otherwise integration returns to you at the point where the parts must become one.',
    evidenceRefs: ['m01', 'm02', 'm03', 'm09', 'm10', 'm12', 'm16', 'm20'],
    operating_loop: specialist.operating_engine.loop,
    mechanisms: specialist.operating_engine.mechanisms,
  }),
  how_people_experience_you: richRendering({
    eyebrow: 'Bounded interpersonal hypotheses',
    headline: 'People may feel deeply considered—and still miss the moment your decision becomes final.',
    summary: 'The fictional observer evidence suggests that you remember constraints and translate specialist work into a shared story. It also suggests that calm delivery can conceal urgency or closure. These are testable possibilities from a small observer packet, not facts about every relationship.',
    evidenceRefs: ['m04', 'm05', 'm06', 'm07', 'm08', 'm18', 'm20'],
    states: specialist.people_experience.states,
    observer_boundary: specialist.people_experience.observer_boundary,
  }),
  communication_dna: richRendering({
    eyebrow: 'Communication continua',
    headline: 'Context-rich until the dependency is clear; fast and directive when the window closes.',
    summary: 'Your communication changes with the job the room must do. In framing, you gather disciplines and make the whole visible. Near an immovable deadline, Speed rises, Temperature cools, explanation narrows, and unfinished input becomes harder to surface. Repair works by making closure and impact explicit.',
    evidenceRefs: ['m01', 'm04', 'm05', 'm06', 'm07', 'm09', 'm10', 'm18', 'm20'],
    speed: specialist.communication.speed,
    temperature: specialist.communication.temperature,
    dimensions: specialist.communication.dimensions,
  }),
  strengths_vulnerabilities: richRendering({
    eyebrow: 'Causal edges',
    headline: 'Your best strengths create the conditions for their own hidden cost.',
    summary: 'Integration, adaptive precision, and composed direction all create immediate value. The risk is not that the strengths become bad. It is that repeated relief reinforces personal centralization, unclear closure, or invisible dissent unless the mechanism is made transferable.',
    evidenceRefs: ['m02', 'm03', 'm04', 'm06', 'm09', 'm10', 'm15', 'm16', 'm18', 'm19'],
    mechanisms: specialist.strengths_vulnerabilities.mechanisms,
  }),
  pressure_conflict: richRendering({
    eyebrow: 'Baseline → pressure → recovery',
    headline: 'Pressure does not simply amplify you; it changes which parts of you remain available to the room.',
    summary: 'At baseline you integrate context, people, and audience meaning. Under an immovable deadline, a trained directive mode takes over: the sequence sharpens, listening narrows, and calm can hide closure. Recovery requires more than warmth—it requires reopening signal and changing the next operating rule.',
    evidenceRefs: ['m04', 'm05', 'm07', 'm18', 'm20'],
    baseline: specialist.pressure_conflict.baseline,
    pressure_state: specialist.pressure_conflict.pressure_state,
    recovery: specialist.pressure_conflict.recovery,
    transformations: specialist.pressure_conflict.transformations,
    conflict_entry: specialist.pressure_conflict.conflict_entry,
    relational_effect: specialist.pressure_conflict.relational_effect,
  }),
  work_dna: richRendering({
    eyebrow: 'Environment fit',
    headline: 'You perform where many disciplines must become one meaningful experience.',
    summary: 'Ambiguity itself is not the attraction. Meaningful ambiguity with a public feedback loop is. Sustainability rises with clear integration authority, staged deadlines, and separate maintenance ownership; it falls when responsibility is broad but the governing decision rights are not.',
    evidenceRefs: ['m01', 'm02', 'm03', 'm06', 'm08', 'm09', 'm10', 'm13', 'm17', 'm19'],
    demands: specialist.work_environment.demands,
    fit_summary: specialist.work_environment.fit_summary,
    friction_summary: specialist.work_environment.friction_summary,
  }),
  role_seat: richRendering({
    eyebrow: 'Role demand envelope',
    headline: 'Natural Fit: whole-experience integrator with explicit authority and an operating partner.',
    summary: 'The fit is not “creative leader” in the abstract. It is a configuration: responsibility for public coherence, authority over integration decisions, live audience feedback, and a separate owner for recurring logistics. Other configurations can work, but their adaptation cost changes.',
    evidenceRefs: ['m01', 'm02', 'm08', 'm09', 'm10', 'm11', 'm13', 'm14', 'm16', 'm17', 'm19'],
    selected_fit: specialist.role_seat.selected_fit,
    selected_configuration: specialist.role_seat.selected_configuration,
    fit_states: specialist.role_seat.fit_states,
    scaffolding: specialist.role_seat.scaffolding,
    plural_success_note: specialist.role_seat.plural_success_note,
    review_trigger: specialist.role_seat.review_trigger,
  }),
  cognitive_operating_style: richRendering({
    eyebrow: 'Evidence-grounded process',
    headline: 'You think by making the whole visible, locating the dependency, and testing the story outside your own head.',
    summary: 'The evidence supports task-specific indicators in systems synthesis, decomposition, flexibility, and early judgment transfer. These observations are grounded in process and outcome. They are not an IQ estimate, intelligence rank, or universal aptitude claim.',
    evidenceRefs: ['m01', 'm02', 'm09', 'm10', 'm11', 'm12', 'm16', 'm20'],
    boundary: specialist.cognition.boundary,
    indicators: specialist.cognition.indicators,
  }),
  personal_operating_energy: richRendering({
    eyebrow: 'Trait · State · Context · Trajectory',
    headline: 'Meaningful convergence activates you; whole-life direction remains open.',
    summary: 'The evidence clearly separates context from trajectory. Integration milestones appear to increase available effort, while prolonged cleanup depletes it. There is not enough cross-context longitudinal evidence to claim that your overall energy is rising, falling, or stable over time.',
    evidenceRefs: ['m08', 'm14', 'm17'],
    layers: { trait: specialist.energy.trait, state: specialist.energy.state, context: specialist.energy.context, trajectory: specialist.energy.trajectory },
    activation: specialist.energy.activation,
    depletion: specialist.energy.depletion,
    resilience: specialist.energy.resilience,
    recovery: specialist.energy.recovery,
  }),
  five_futures: richRendering({
    eyebrow: 'Conditional trajectories',
    headline: 'Five futures turn on whether coherence, authority, and recovery can travel.',
    summary: 'These are substantial conditional behavioral trajectories, not predictions. Each names the mechanism, evidence, control variables, signs to watch, and the evidence that would make the map change its mind.',
    evidenceRefs: ['m02', 'm03', 'm04', 'm05', 'm08', 'm11', 'm14', 'm15', 'm16', 'm17', 'm18', 'm19', 'm20'],
    futures: specialist.five_futures.items.map((future) => ({ ...future, label: future.future_identity })),
  }),
  one_move: richRendering({
    eyebrow: 'One reversible experiment',
    headline: 'Transfer the coherence test before you transfer the decision.',
    summary: 'The move is not generic delegation. It targets the mechanism that makes personal gap-filling so effective: you hold the test that lets many parts become one. The experiment preserves that strength while testing whether another owner can use the test without hidden correction.',
    evidenceRefs: ['m03', 'm11', 'm15', 'm16', 'm19'],
    ...specialist.one_move,
  }),
  evidence_certainty: richRendering({
    eyebrow: 'Make your map alive — The Validation',
    headline: 'The map becomes more useful when uncertainty is visible and testable.',
    summary: 'Human-readable claims replace internal IDs. Evidence, counterevidence, inference boundaries, abstentions, and falsifiers remain available through progressive disclosure. Future longitudinal evidence can update the map without erasing why it changed.',
    evidenceRefs: RAW.evidence.map(({ evidence_id: id }) => id),
    claims: specialist.validation.claims,
    conflicts: specialist.validation.conflicts,
    what_would_change_the_map: specialist.validation.what_would_change_the_map,
    future_relationship: 'Your first BOS is our best current model of you. Governed lived evidence can validate beliefs, resolve contradictions, distinguish trait from state, observe experiments, and preserve why the model changed.',
  }),
  operating_identity: richRendering({
    eyebrow: 'Compact whole-person compression',
    headline: 'Create a stable frame for the whole—then improvise with reality.',
    summary: 'This is useful when the work becomes noisy: ask what must remain true for the audience, what can change safely, and which decision test another person can now own. It is a memory aid for governing logic, not a personality type or clever nickname.',
    evidenceRefs: specialist.operating_identity.evidence_refs,
    governing_logic: specialist.operating_identity.governing_logic,
    memorable_use: specialist.operating_identity.memorable_use,
    not_a_type: specialist.operating_identity.not_a_type,
    falsifier: specialist.operating_identity.falsifier,
  }),
};

const DRAFT = {
  topology,
  attributes,
  dynamics,
  specialized: specialist,
  sequences: [
    { sequence_id: 'ms01', steps: ['whole experience framed', 'dependencies mapped', 'disciplines invited', 'live response tested', 'route revised', 'handoff integrated', 'lesson captured'] },
    { sequence_id: 'ms02', steps: ['handoff gap appears', 'coherence risk rises', 'bridge is completed personally', 'schedule recovers', 'integration ownership remains centralized'] },
  ],
  strengths_and_overuse: specialist.strengths_vulnerabilities.mechanisms,
  compensation: [
    { statement: 'Visible wall-mapping compensates for the complexity of internal integration by making dependencies inspectable.', evidence_refs: ['m09', 'm10'] },
    { statement: 'Directive checklists compensate for reduced time and discussion bandwidth under deadline pressure.', evidence_refs: ['m04', 'm18'] },
    { statement: 'Personal gap-filling compensates for missing integration ownership but preserves dependency on the same integrator.', evidence_refs: ['m03', 'm19'], counterevidence_refs: ['m15', 'm16'] },
  ],
  whole_person: {
    core_explanation: 'This person creates coherence by holding what the whole experience must mean, then changing the route as reality teaches what the plan could not.',
    central_tension: 'The same integrative judgment that helps many people create one coherent whole can keep that judgment concentrated in one person.',
    mechanisms: ['A stable experience principle makes rapid adaptation safe.', 'Personal gap-filling protects schedule and relationships while hiding integration debt.', 'Deadline pressure converts inclusive synthesis into directive sequence.', 'Repair compounds only when it changes the next project rule.'],
    identity_tensions: ['Wants shared ownership while remaining the most reliable path to restored coherence.', 'Values careful planning and feels little attachment to a plan contradicted by lived experience.'],
    goal_conflicts: ['Wants junior producers to own integration decisions without accepting a loss of public coherence.'],
    private_calculations: specialist.recognition.private_calculations,
    pressure_and_recovery: 'Under hard deadlines, context-rich integration narrows into directive sequence; recovery requires reopening input and changing the next handoff.',
    work_and_relationships: 'Best evidence supports multi-disciplinary public work with whole-experience authority, live feedback, and a separate owner for recurring operations.',
    identity_distillation: 'Create a stable frame for the whole—then improvise with reality.',
    evidence_refs: RAW.evidence.map(({ evidence_id: id }) => id),
    confidence: 'SUPPORTED_HYPOTHESIS',
    what_would_change_it: 'Cross-context evidence showing that stable framing, live revision, integration centralization, and pressure narrowing do not recur outside this fictional production domain.',
  },
  abstentions: RAW.abstentions,
  validation_backlog: ['Observe three independent integration decisions.', 'Collect two additional fictional pressure episodes.', 'Measure recovery across project and non-project contexts.', 'Test a role configuration outside public-facing creative production.'],
  surface_claims: {
    this_is_you: ['md01', 'md02', 'md03', 'md04', 'md05', 'ma04'],
    personality_dna: ['mt01', 'mt02', 'mt03', 'mt04', 'ma01', 'ma02', 'ma03', 'ma04'],
    how_you_operate: ['md01', 'md02', 'md04', 'ma01', 'ma04'],
    how_people_experience_you: ['mt02', 'ma03', 'md03', 'md04'],
    communication_dna: ['mt02', 'ma03', 'md03', 'md04'],
    strengths_vulnerabilities: ['md01', 'md02', 'md03', 'ma04'],
    pressure_conflict: ['mt02', 'md03', 'md04'],
    work_dna: ['mt01', 'mt03', 'md01', 'md02', 'md05'],
    role_seat: ['mt03', 'ma01', 'ma04', 'md02', 'md05'],
    cognitive_operating_style: ['mt01', 'ma01', 'ma04', 'md01'],
    personal_operating_energy: ['md05'],
    five_futures: ['md01', 'md02', 'md03', 'md04', 'md05', 'ma04'],
    one_move: ['md02', 'ma04'],
    evidence_certainty: ['mt01', 'mt02', 'mt03', 'mt04', 'ma01', 'ma02', 'ma03', 'ma04', 'md01', 'md02', 'md03', 'md04', 'md05'],
    operating_identity: ['mt01', 'mt03', 'md01', 'md02', 'ma04'],
  },
  surface_renderings: renderings,
};

export const RICH_SYNTHETIC_FIXTURE = Object.freeze({
  fixture_id: 'mosaic',
  rawEvidence: RAW,
  interpretationDraft: DRAFT,
});

export default RICH_SYNTHETIC_FIXTURE;
