export const CONTRACT_VERSION = '1.0.0';
export const HASH_ALGORITHM = 'sha256';
export const HASH_VERSION = 'canonical-json-v1';

export const AUTHORITY_TYPES = Object.freeze([
  'USER_DIRECTION', 'USER_EVIDENCE', 'DOMAIN_KNOWLEDGE',
  'PRIVATE_HUMAN_JUDGMENT', 'UNIVERSAL_COACHING', 'MARKET_CONTEXT',
  'INTERVENTION_OUTCOME', 'GOVERNANCE_CONFLICT',
]);

export const TRUTH_CLASSES = Object.freeze([
  'PERSONAL_TRUTH', 'OBSERVED_TRUTH', 'DOMAIN_TRUTH', 'INTERVENTION_TRUTH',
]);

export const PRIVACY_CLASSIFICATIONS = Object.freeze([
  'PUBLIC', 'INTERNAL', 'TENANT_PRIVATE', 'USER_PRIVATE', 'COACH_SESSION_PRIVATE',
  'ORGANIZATION_CONFIDENTIAL', 'RESTRICTED_PERSONAL', 'RESTRICTED_FINANCIAL',
  'RESTRICTED_BEHAVIORAL', 'RESTRICTED_OUTCOME', 'ANONYMIZED_AGGREGATE',
]);

export const CONSENT_STATUSES = Object.freeze([
  'PROPOSED', 'ACTIVE', 'DECLINED', 'REVOKED', 'EXPIRED', 'SUPERSEDED', 'NOT_CONFIGURED',
]);

export const IDENTITY_TYPES = Object.freeze([
  'PERSON', 'PROFILE', 'BUSINESS', 'TEAM', 'COACH', 'ORGANIZATION',
  'SUBSCRIPTION', 'TENANT', 'ACTOR',
]);

export const RELATIONSHIP_TYPES = Object.freeze([
  'TENANT_RELATIONSHIP', 'USER_BUSINESS', 'COACH_USER',
  'ORGANIZATION_MEMBERSHIP', 'SUBSCRIPTION_ENTITLEMENT',
]);

export const RELATIONSHIP_STATUSES = Object.freeze([
  'PROPOSED', 'ACTIVE', 'SUSPENDED', 'REVOKED', 'EXPIRED', 'SUPERSEDED',
]);

export const RECEIPT_TYPES = Object.freeze([
  'EVIDENCE_USE', 'KNOWLEDGE_USE', 'MODEL_USE', 'PROMPT_USE',
  'POLICY_USE', 'AUTHORITY_USE',
]);

export const NO_MODEL_USED = 'NO_MODEL_USED';
export const NO_PROMPT_USED = 'NO_PROMPT_USED';
export const NOT_CONFIGURED = 'NOT_CONFIGURED';

export const VALIDATION_ERROR_CODES = Object.freeze({
  REQUIRED: 'IF_REQUIRED', INVALID_TYPE: 'IF_INVALID_TYPE', INVALID_ENUM: 'IF_INVALID_ENUM',
  INVALID_ID: 'IF_INVALID_ID', INVALID_IDENTITY_SCOPE: 'IF_INVALID_IDENTITY_SCOPE',
  TENANT_REQUIRED: 'IF_TENANT_REQUIRED', CROSS_TENANT_DENIED: 'IF_CROSS_TENANT_DENIED',
  INVALID_TIMESTAMP: 'IF_INVALID_TIMESTAMP', TEMPORAL_ORDER: 'IF_TEMPORAL_ORDER',
  INVALID_JSON: 'IF_INVALID_JSON', HASH_MISMATCH: 'IF_HASH_MISMATCH',
  PROVENANCE_REQUIRED: 'IF_PROVENANCE_REQUIRED', CONSENT_REQUIRED: 'IF_CONSENT_REQUIRED',
  CONSENT_INACTIVE: 'IF_CONSENT_INACTIVE', CONSENT_SCOPE_MISMATCH: 'IF_CONSENT_SCOPE_MISMATCH',
  AUTHORIZATION_REQUIRED: 'IF_AUTHORIZATION_REQUIRED', PRIVACY_DOWNGRADE: 'IF_PRIVACY_DOWNGRADE',
  DIRECT_IDENTITY_FOR_ANONYMIZED: 'IF_DIRECT_IDENTITY_FOR_ANONYMIZED',
  RECEIPT_SOURCE_INCOMPLETE: 'IF_RECEIPT_SOURCE_INCOMPLETE',
  AUTHORITY_TRUTH_CONFLICT: 'IF_AUTHORITY_TRUTH_CONFLICT',
});

export const VALIDATION_WARNING_CODES = Object.freeze({
  FUTURE_EVENT: 'IF_FUTURE_EVENT', LATE_ARRIVAL: 'IF_LATE_ARRIVAL',
  POLICY_NOT_CONFIGURED: 'IF_POLICY_NOT_CONFIGURED', SUSPICIOUS_AUTHORITY_TRUTH: 'IF_SUSPICIOUS_AUTHORITY_TRUTH',
});

export const PRIVACY_RANK = Object.freeze({
  PUBLIC: 0, INTERNAL: 1, ANONYMIZED_AGGREGATE: 1, TENANT_PRIVATE: 2,
  ORGANIZATION_CONFIDENTIAL: 3, USER_PRIVATE: 4, RESTRICTED_OUTCOME: 5,
  RESTRICTED_PERSONAL: 6, RESTRICTED_FINANCIAL: 6, RESTRICTED_BEHAVIORAL: 6,
  COACH_SESSION_PRIVATE: 7,
});
