import { OBJECT_AUTHORITY, OBJECT_TRUTH_CLASS } from './durableCoreConstants.js';
import { createPayloadHash } from './hashing.js';
import { MISSION_001_EXAMPLES, SYNTHETIC_IDS, SYNTHETIC_NOW, syntheticEvent, syntheticProvenance } from './examples.js';

const later = '2026-01-22T12:00:00.000Z';
const common = (object_type, id, extra = {}) => ({
  object_type, contract_version: '1.0.0', schema_version: '1.0.0', object_id: id,
  tenant_id: SYNTHETIC_IDS.tenant, profile_id: SYNTHETIC_IDS.profile,
  business_id: SYNTHETIC_IDS.business, organization_id: null,
  subscription_id: SYNTHETIC_IDS.subscription, status: 'ACTIVE',
  created_at: SYNTHETIC_NOW, updated_at: SYNTHETIC_NOW, effective_at: SYNTHETIC_NOW,
  expires_at: null, source_event_ids: [`evt_source_${id}`], provenance: syntheticProvenance,
  privacy_classification: 'TENANT_PRIVATE', consent_record_ids: [], version: 1,
  previous_version_id: null, supersedes_id: null, validation_state: 'VALIDATED',
  authority_type: OBJECT_AUTHORITY[object_type], truth_class: OBJECT_TRUTH_CLASS[object_type], ...extra,
});

const stateField = (current, previous = null, trend = 'STABLE') => ({ current, previous, trend,
  reason_for_change: previous === current ? null : 'Synthetic evidence changed.',
  reason_for_non_change: previous === current ? 'No qualifying synthetic change.' : null,
  evidence_sources: ['evidence_synthetic_kpi'], confidence: 0.7, last_updated: SYNTHETIC_NOW });

const userIntentState = common('UserIntentState', 'intent_synthetic_001', {
  intent_state_id: 'intent_synthetic_001', goal_claims: [{ claim_id: 'goal_synthetic_001', statement: 'Build a sustainable synthetic business.', conflict_ids: [] }],
  desired_future: 'future_synthetic_optimized', rejected_futures: ['future_synthetic_decline'], risk_tolerance: 'MODERATE',
  lifestyle_constraints: ['synthetic_weekend_boundary'], business_model_preferences: ['relationship_led'], values: ['service'],
  non_negotiables: ['privacy'], decision_preferences: ['evidence_first'], consent_preferences: ['confirm_writes'],
  active_from: SYNTHETIC_NOW, active_until: null,
});

const evidenceEntries = [{ evidence_id: 'evidence_synthetic_kpi', evidence_type: 'KPI', metric_id: 'meaningful_conversations', value: 12, unit: 'count/week', period: '2026-W02', source_event_id: 'evt_source_evidence_synthetic', verification_method: 'USER_ENTERED', verification_state: 'USER_ATTESTED', confidence: 0.8, occurred_at: SYNTHETIC_NOW, observed_at: SYNTHETIC_NOW, recorded_at: later, correction_of_evidence_id: null, supersedes_evidence_id: null, privacy_classification: 'TENANT_PRIVATE', provenance: syntheticProvenance }];
const evidenceLedger = common('UserEvidenceLedger', 'ledger_synthetic_evidence', { ledger_id: 'ledger_synthetic_evidence', scope: 'WEEKLY_REAL_ESTATE', evidence_entries: evidenceEntries, period_start: SYNTHETIC_NOW, period_end: later, verification_state: 'MIXED', completeness_state: 'PARTIAL' });

const knowledgeGraph = common('RealEstateKnowledgeGraph', 'knowledge_synthetic_re', { knowledge_graph_id: 'knowledge_synthetic_re', graph_version: '1.0.0',
  claim_nodes: [{ claim_id: 'claim_synthetic_doctrine', claim_type: 'DETERMINISTIC_RULE', statement: 'Synthetic doctrine claim.', authority_type: 'DOMAIN_KNOWLEDGE', truth_class: 'DOMAIN_TRUTH', applicability: 'synthetic_real_estate', role_scope: ['owner'], business_model_scope: ['relationship_led'], market_scope: ['synthetic_market'], evidence_strength: 'BOOTSTRAP', confidence: 0.7, supporting_source_ids: ['source_synthetic_doctrine'], contradicting_source_ids: [], effective_at: SYNTHETIC_NOW, expires_at: null, review_due_at: later, status: 'ACTIVE', supersedes_claim_id: null, provenance: syntheticProvenance }],
  source_nodes: [{ source_id: 'source_synthetic_doctrine', source_version: '1.0.0', source_hash: 'sha256:synthetic-doctrine' }], benchmark_nodes: [], role_nodes: [], business_model_nodes: [], market_regime_nodes: [], constraint_nodes: [], intervention_hypothesis_nodes: [], relationships: [], refresh_status: 'NOT_CONFIGURED', review_status: 'BOOTSTRAP_ACTIVE' });

const humanJudgment = common('HumanJudgmentAuthority', 'judgment_synthetic_001', { human_judgment_authority_id: 'judgment_synthetic_001', subject_scope: { profile_id: SYNTHETIC_IDS.profile }, authority_actor_ref: { type: 'COACH', id: SYNTHETIC_IDS.coach, tenant_id: SYNTHETIC_IDS.tenant }, relationship_ref: 'rel_synthetic_coach_user', observation_records: [{ observation_id: 'observation_synthetic_001', statement_code: 'FOLLOW_UP_PATTERN', truth_status: 'ATTRIBUTED_JUDGMENT' }], recommendation_records: [{ recommendation_id: 'recommendation_synthetic_001', intervention_id: 'intervention_synthetic_weekly_review' }], review_records: [], privacy_classification: 'COACH_SESSION_PRIVATE', consent_record_ids: ['consent_synthetic_coach'] });

const interventionLibrary = common('CoachingInterventionLibrary', 'library_synthetic_001', { library_id: 'library_synthetic_001', interventions: [{ intervention_id: 'intervention_synthetic_weekly_review', name: 'Synthetic weekly review', description: 'Inspect synthetic follow-up.', target_constraint_types: ['FOLLOW_UP'], eligible_roles: ['owner'], eligible_business_models: ['relationship_led'], behavioral_fit_rules: [], financial_feasibility_rules: [], market_applicability: ['synthetic_market'], required_execution: ['weekly_review'], minimum_duration: 'P30D', expected_outcomes: ['follow_up_visibility'], success_metrics: ['follow_up_rate'], failure_conditions: ['no_execution'], stop_conditions: ['privacy_conflict'], evidence_requirements: ['execution_log'], validation_level: 'ANECDOTAL', replication_count: 0, source_claim_ids: ['claim_synthetic_doctrine'], source_outcome_ids: [], status: 'HYPOTHESIS', provenance: syntheticProvenance }], privacy_classification: 'INTERNAL' });

const marketGraph = common('MarketContextGraph', 'market_synthetic_001', { market_context_graph_id: 'market_synthetic_001', market_scope: 'synthetic_market', regime_nodes: [{ regime_id: 'regime_synthetic_balanced', status: 'BALANCED' }], indicator_nodes: [{ indicator_id: 'indicator_synthetic_inventory', indicator_type: 'INVENTORY', value: 3, unit: 'months', geographic_scope: 'synthetic_market', role_scope: ['owner'], business_model_scope: ['relationship_led'], occurred_at: SYNTHETIC_NOW, effective_at: SYNTHETIC_NOW, expires_at: later, source_reference: { source_id: 'provider_synthetic', source_version: '1.0.0', source_hash: 'sha256:synthetic-provider' }, confidence: 0.6, verification_state: 'SYNTHETIC', status: 'ACTIVE', provenance: syntheticProvenance }], policy_nodes: [], provider_nodes: [{ provider_id: 'provider_synthetic' }], relationships: [], effective_window: { from: SYNTHETIC_NOW, to: later }, refresh_status: 'NOT_CONFIGURED' });

const outcomeLedger = common('OutcomeValidationLedger', 'ledger_synthetic_outcomes', { ledger_id: 'ledger_synthetic_outcomes', outcome_records: [{ outcome_id: 'outcome_synthetic_personal', intervention_id: 'intervention_synthetic_weekly_review', intervention_state_id: 'intervention_state_synthetic_active', state_before_id: 'state_synthetic_previous', belief_before_ids: ['belief_synthetic_followup'], future_state_before_id: 'future_synthetic_steady', expected_outcome: 'follow_up_visibility', expected_time_window: 'P30D', success_metrics: ['follow_up_rate'], baseline_reference: 'evidence_synthetic_baseline', decision_status: 'ACCEPTED', execution_status: 'PARTIAL', execution_quality: 0.6, execution_evidence_ids: ['evidence_synthetic_execution'], market_context_ids: ['market_synthetic_001'], confounder_records: [{ code: 'SYNTHETIC_MARKET_SHIFT' }], alternative_explanations: ['seasonality'], actual_outcome: 'synthetic_improvement', outcome_metric_results: [{ metric_id: 'follow_up_rate', delta: 0.1 }], occurred_at: later, validated_at: later, state_after_id: 'state_synthetic_current', belief_after_ids: ['belief_synthetic_followup'], future_state_after_id: 'future_synthetic_steady', attribution_confidence: 0.4, replication_status: 'PERSONAL_ONLY', learning_eligibility: false, privacy_classification: 'RESTRICTED_OUTCOME', consent_record_ids: [], provenance: syntheticProvenance, status: 'OBSERVED', effectiveness_status: 'LIMITED_ATTRIBUTION' }] });

const conflictGraph = common('AuthorityConflictGraph', 'conflict_graph_synthetic', { conflict_graph_id: 'conflict_graph_synthetic', conflicts: [{ conflict_id: 'conflict_synthetic_001', conflict_type: 'GOAL_REALITY_GAP', subject_scope: { business_id: SYNTHETIC_IDS.business }, claim_ids: ['goal_synthetic_001'], belief_ids: ['belief_synthetic_followup'], evidence_ids: ['evidence_synthetic_kpi'], authority_positions: [{ position_id: 'position_user', authority_type: 'USER_DIRECTION' }, { position_id: 'position_evidence', authority_type: 'USER_EVIDENCE' }], severity: 'MEDIUM', materiality: 'SCOPED', detected_at: SYNTHETIC_NOW, status: 'OPEN', required_evidence: ['evidence_synthetic_next'], human_review_required: true, resolution_id: null, provenance: syntheticProvenance }], resolutions: [] });

const beliefState = common('BeliefState', 'belief_state_synthetic', { belief_state_id: 'belief_state_synthetic', beliefs: [{ belief_id: 'belief_synthetic_followup', claim: 'Follow-up visibility may constrain synthetic performance.', claim_type: 'CONSTRAINT_HYPOTHESIS', scope: { business_id: SYNTHETIC_IDS.business }, probability: 0.65, confidence_band: 'MODERATE', confidence_score: 0.55, supporting_evidence_ids: ['evidence_synthetic_kpi'], contradicting_evidence_ids: ['evidence_synthetic_counter'], authority_positions: ['position_evidence'], knowledge_claim_ids: ['claim_synthetic_doctrine'], market_context_ids: ['market_synthetic_001'], human_judgment_ids: ['observation_synthetic_001'], outcome_ids: [], conflict_ids: ['conflict_synthetic_001'], causal_hypothesis: null, alternative_hypotheses: ['synthetic_market_shift'], validation_level: 'HYPOTHESIS', last_changed_at: SYNTHETIC_NOW, change_reason: 'Synthetic evidence arrived.', non_change_reason: null, next_best_evidence: 'weekly_follow_up_rate', evidence_gap_ids: ['gap_synthetic_followup'], status: 'ACTIVE', provenance: syntheticProvenance }] });

const businessState = common('BusinessEngineState', 'state_synthetic_current', { business_engine_state_id: 'state_synthetic_current', vertical_id: 'real_estate', operating_policy_id: 'policy_synthetic_re', state_version: 2, previous_state_version_id: 'state_version_synthetic_001', as_of_at: later, financial_reality: stateField({ revenue: 100 }, { revenue: 90 }, 'UP'), behavioral_reality: stateField('RELATIONSHIP_LED'), business_model_alignment: stateField('PARTIAL'), constraint_reality: stateField('FOLLOW_UP'), confidence_reality: stateField('MODERATE'), primary_constraint_id: 'constraint_synthetic_followup', secondary_constraint_ids: [], current_operating_state: stateField('STEADY'), historical_comparison: { period: 'P30D' }, trend_summary: 'Synthetic stable-to-improving.', belief_ids: ['belief_synthetic_followup'], evidence_ids: ['evidence_synthetic_kpi'], knowledge_claim_ids: ['claim_synthetic_doctrine'], market_context_ids: ['market_synthetic_001'], human_judgment_ids: ['observation_synthetic_001'], conflict_ids: ['conflict_synthetic_001'], explanation_trace_id: 'trace_synthetic_state', confidence_state_id: 'confidence_synthetic_001' });

const stateVersion = common('BusinessEngineStateVersion', 'state_version_synthetic_002', { state_version_id: 'state_version_synthetic_002', business_engine_state_id: 'state_synthetic_current', state_version: 2, previous_state_version_id: 'state_version_synthetic_001', projection_version: 'projection-v1', policy_version: 'policy-synthetic-v1', explanation_trace_id: 'trace_synthetic_state', generated_at: later, material_changes: ['constraint_reality'], evaluated_non_material_inputs: ['evidence_synthetic_counter'], changed_fields: ['constraint_reality'], unchanged_fields: ['behavioral_reality'], validation_status: 'VALIDATED', version: 2, previous_version_id: 'state_version_synthetic_001' });

const future = (n, p, rank) => common('FutureState', `future_synthetic_${n}`, { future_state_id: `future_synthetic_${n}`, stable_future_identity: `FUTURE_${n.toUpperCase()}`, name: `Synthetic ${n}`, description: 'Synthetic modeled future.', trajectory_type: n.toUpperCase(), probability: p, probability_band: 'MODELED', current_rank: rank, prior_rank: rank, entry_conditions: [], exit_conditions: [], leading_indicators: [], lagging_indicators: [], supporting_belief_ids: ['belief_synthetic_followup'], contradicting_belief_ids: [], required_interventions: [], time_horizon: 'P90D' });
const futures = [future('growth', .32, 1), future('steady', .27, 2), future('plateau', .19, 3), future('decline', .14, 4), future('reinvention', .08, 5)];

const probabilityChange = common('FutureProbabilityChange', 'probability_change_synthetic', { probability_change_id: 'probability_change_synthetic', future_state_id: 'future_synthetic_growth', from_probability: .30, to_probability: .32, delta: .02, reason: 'Synthetic qualifying evidence.', supporting_ids: ['evidence_synthetic_kpi'], contradicting_ids: [], policy_version: 'future-policy-v1', timestamp: later, explanation_trace_id: 'trace_synthetic_future' });
const interventionState = common('InterventionState', 'intervention_state_synthetic_active', { intervention_state_id: 'intervention_state_synthetic_active', intervention_id: 'intervention_synthetic_weekly_review', one_move_candidate_rank: 1, proposed_at: SYNTHETIC_NOW, accepted_at: later, activated_at: later, decision_actor_ref: { type: 'PROFILE', id: SYNTHETIC_IDS.profile }, target_constraint_ids: ['constraint_synthetic_followup'], expected_outcomes: ['follow_up_visibility'], required_execution: ['weekly_review'], success_metrics: ['follow_up_rate'], stop_conditions: ['privacy_conflict'], execution_evidence_ids: [], outcome_ids: [], status: 'ACTIVE' });
const interventionEvent = common('InterventionEvent', 'intervention_event_synthetic', { intervention_event_id: 'intervention_event_synthetic', intervention_state_id: interventionState.intervention_state_id, from_status: 'ACCEPTED', to_status: 'ACTIVE', intelligence_event: syntheticEvent({ event_id: 'evt_synthetic_intervention_transition', event_type: 'INTERVENTION_ACTIVATED', authority_type: 'INTERVENTION_OUTCOME', truth_class: 'INTERVENTION_TRUTH', payload: { from: 'ACCEPTED', to: 'ACTIVE' }, payload_hash: createPayloadHash({ from: 'ACCEPTED', to: 'ACTIVE' }), idempotency_key: 'idem_synthetic_intervention_transition' }) });
const session = common('ConversationSession', 'session_synthetic_001', { session_id: 'session_synthetic_001', state_snapshot_id: 'state_version_synthetic_002', belief_state_id: 'belief_state_synthetic', future_state_ids: futures.map((x) => x.future_state_id), active_intervention_id: interventionState.intervention_state_id, evidence_gap_ids: ['gap_synthetic_followup'], weekly_update_status: 'REQUIRED', status: 'OPEN', privacy_classification: 'USER_PRIVATE', consent_record_ids: ['consent_synthetic_active'] });
const conversationEvent = common('ConversationEvent', 'conversation_event_synthetic_proposal', { conversation_event_id: 'conversation_event_synthetic_proposal', session_id: session.session_id, conversation_event_type: 'EXTRACTION_PROPOSAL', confirmation_state: 'AWAITING_USER_CONFIRMATION', status: 'PROPOSED', privacy_classification: 'USER_PRIVATE', consent_record_ids: ['consent_synthetic_active'] });
const gap = common('EvidenceGap', 'gap_synthetic_followup', { evidence_gap_id: 'gap_synthetic_followup', target_ids: ['belief_synthetic_followup'], gap_type: 'MISSING_WEEKLY_KPI', missing_data: ['follow_up_rate'], priority: 'HIGH', expected_confidence_gain: .15, expected_future_impact: .05, request_reason: 'Discriminate competing synthetic hypotheses.', recommended_question: 'What was the synthetic follow-up rate?', status: 'OPEN', deferral: null, resolution_event_ids: [] });
const confidence = common('ConfidenceState', 'confidence_synthetic_001', { confidence_state_id: 'confidence_synthetic_001', evidence_completeness: .6, evidence_quality: .7, state_confidence: .65, belief_confidence: .55, future_confidence: .4, intervention_confidence: .5, market_context_confidence: .35 });
const trace = common('ExplanationTrace', 'trace_synthetic_state', { explanation_trace_id: 'trace_synthetic_state', operation: 'PROJECT_SYNTHETIC_STATE', operation_version: '1.0.0', input_ids: ['evidence_synthetic_kpi', 'belief_synthetic_followup'], authority_routes: [{ authority_type: 'USER_EVIDENCE', role: 'DOMINANT' }], dominant_authorities: ['USER_EVIDENCE'], subordinate_authorities: ['DOMAIN_KNOWLEDGE'], conflicts: ['conflict_synthetic_001'], evidence_inputs: ['evidence_synthetic_kpi'], knowledge_inputs: ['claim_synthetic_doctrine'], human_inputs: [], market_inputs: [], model_receipt_ids: [], prompt_receipt_ids: [], policy_receipt_ids: [], changed_outputs: ['constraint_reality'], unchanged_outputs: ['behavioral_reality'], change_reasons: ['synthetic evidence'], non_change_reasons: ['no qualifying change'], missing_evidence: ['follow_up_rate'], human_review_required: false, timestamp: later });
const promotion = common('LearningPromotionRecord', 'promotion_synthetic_candidate', { learning_promotion_id: 'promotion_synthetic_candidate', candidate_id: 'intervention_synthetic_weekly_review', from_state: 'ANECDOTAL', to_state: 'OBSERVED', source_outcome_ids: ['outcome_synthetic_personal'], replication_count: 1, context_match: 'PERSONAL_ONLY', privacy_review: 'PRIVATE', consent_review: 'NOT_ELIGIBLE_UNIVERSAL', causal_review: 'LIMITED_ATTRIBUTION', human_approval: null, promotion_metadata: {}, rejection_metadata: null, rollback_metadata: null, status: 'OBSERVED' });
const experiment = common('ExperimentRecord', 'experiment_synthetic_001', { experiment_id: 'experiment_synthetic_001', hypothesis: 'Weekly review may improve synthetic follow-up visibility.', target_ids: ['belief_synthetic_followup', 'constraint_synthetic_followup'], intervention_id: 'intervention_synthetic_weekly_review', baseline_reference: 'evidence_synthetic_baseline', duration: 'P30D', success_metric: 'follow_up_rate', expected_result: '+0.1', stop_condition: 'privacy_conflict', execution_evidence_ids: ['evidence_synthetic_execution'], observed_result: null, confounders: [], conclusion: 'NOT_YET_EVALUATED', promotion_status: 'ANECDOTAL', status: 'ACTIVE' });
const policy = common('VerticalOperatingPolicy', 'policy_synthetic_re', { operating_policy_id: 'policy_synthetic_re', vertical_id: 'real_estate', role_scope: ['owner'], business_model_scope: ['relationship_led'], required_weekly_metrics: ['meaningful_conversations', 'leads', 'appointments', 'contracts', 'closings', 'database_additions', 'follow_up_rate', 'one_move_execution', 'blockers'], optional_metrics: [], evidence_frequency: 'P7D', staleness_rules: [{ metric: '*', stale_after: 'P14D' }], confidence_requirements: { state: .5 }, question_priority_rules: ['highest_expected_information_gain'], constraint_taxonomy_version: 'synthetic-v1', future_policy_version: 'synthetic-v1', intervention_policy_version: 'synthetic-v1' });

export const MISSION_002_FIXTURES = Object.freeze({
  complete_user_intent_state: userIntentState,
  conflicting_goals: { ...userIntentState, intent_state_id: 'intent_synthetic_conflict', object_id: 'intent_synthetic_conflict', goal_claims: [{ claim_id: 'goal_synthetic_a', conflicts_with: ['goal_synthetic_b'] }, { claim_id: 'goal_synthetic_b', conflicts_with: ['goal_synthetic_a'] }] },
  weekly_real_estate_evidence_ledger: evidenceLedger,
  corrected_kpi: { ...evidenceLedger, ledger_id: 'ledger_synthetic_corrected', object_id: 'ledger_synthetic_corrected', evidence_entries: [...evidenceEntries, { ...evidenceEntries[0], evidence_id: 'evidence_synthetic_kpi_correction', value: 13, correction_of_evidence_id: 'evidence_synthetic_kpi' }] },
  doctrine_claim: knowledgeGraph,
  conflicting_claims: { ...knowledgeGraph, knowledge_graph_id: 'knowledge_synthetic_conflict', object_id: 'knowledge_synthetic_conflict', claim_nodes: [...knowledgeGraph.claim_nodes, { ...knowledgeGraph.claim_nodes[0], claim_id: 'claim_synthetic_counter', statement: 'Synthetic counterclaim.', contradicting_source_ids: ['source_synthetic_doctrine'] }] },
  private_coach_observation: humanJudgment,
  private_coach_recommendation: { ...humanJudgment, human_judgment_authority_id: 'judgment_synthetic_recommendation', object_id: 'judgment_synthetic_recommendation', observation_records: [], recommendation_records: humanJudgment.recommendation_records },
  intervention_hypothesis: interventionLibrary,
  market_regime: marketGraph,
  successful_personal_outcome_limited_attribution: outcomeLedger,
  non_executed_recommendation: { ...outcomeLedger, ledger_id: 'ledger_synthetic_nonexecuted', object_id: 'ledger_synthetic_nonexecuted', outcome_records: [{ ...outcomeLedger.outcome_records[0], outcome_id: 'outcome_synthetic_nonexecuted', execution_status: 'NOT_EXECUTED', execution_evidence_ids: [], effectiveness_status: 'NOT_EVALUABLE' }] },
  authority_conflict: conflictGraph,
  resolved_conflict_with_dissent: { ...conflictGraph, conflict_graph_id: 'conflict_graph_synthetic_resolved', object_id: 'conflict_graph_synthetic_resolved', conflicts: [{ ...conflictGraph.conflicts[0], status: 'RESOLVED', resolution_id: 'resolution_synthetic_001' }], resolutions: [{ resolution_id: 'resolution_synthetic_001', resolution_type: 'HUMAN_DECISION', resolved_by: 'actor_synthetic_governor', decision: 'Request more evidence.', rationale: 'Synthetic scoped decision.', supporting_ids: ['evidence_synthetic_kpi'], effective_at: later, reopen_conditions: ['new_evidence'], status: 'ACTIVE', preserved_dissent: ['position_user'] }] },
  belief_support_and_contradiction: beliefState,
  belief_non_change: { ...beliefState, belief_state_id: 'belief_state_synthetic_unchanged', object_id: 'belief_state_synthetic_unchanged', beliefs: [{ ...beliefState.beliefs[0], change_reason: null, non_change_reason: 'No qualifying synthetic evidence.' }] },
  business_engine_state: businessState,
  business_engine_state_version: stateVersion,
  unequal_five_futures: futures,
  future_probability_change: probabilityChange,
  active_one_move: interventionState,
  blocked_intervention: { ...interventionState, intervention_state_id: 'intervention_state_synthetic_blocked', object_id: 'intervention_state_synthetic_blocked', status: 'BLOCKED', blocked_at: later },
  intervention_event: interventionEvent,
  evidence_gap: gap,
  confidence_state: confidence,
  explanation_trace: trace,
  learning_candidate: promotion,
  rejected_promotion: { ...promotion, learning_promotion_id: 'promotion_synthetic_rejected', object_id: 'promotion_synthetic_rejected', from_state: 'OBSERVED', to_state: 'REJECTED', status: 'REJECTED', rejection_metadata: { reason: 'insufficient synthetic evidence' } },
  experiment_record: experiment,
  vertical_operating_policy: policy,
  session_requiring_weekly_evidence: session,
  extraction_proposal_awaiting_confirmation: conversationEvent,
  consent_reference: MISSION_001_EXAMPLES.consent_activation,
});

export const MISSION_002_CONTRACT_FIXTURES = Object.freeze({
  UserIntentState: userIntentState, UserEvidenceLedger: evidenceLedger, RealEstateKnowledgeGraph: knowledgeGraph,
  HumanJudgmentAuthority: humanJudgment, CoachingInterventionLibrary: interventionLibrary, MarketContextGraph: marketGraph,
  OutcomeValidationLedger: outcomeLedger, AuthorityConflictGraph: conflictGraph, BeliefState: beliefState,
  BusinessEngineState: businessState, BusinessEngineStateVersion: stateVersion, FutureState: futures[0],
  FutureProbabilityChange: probabilityChange, InterventionState: interventionState, InterventionEvent: interventionEvent,
  ConversationSession: session, ConversationEvent: conversationEvent, EvidenceGap: gap, ConfidenceState: confidence,
  ExplanationTrace: trace, LearningPromotionRecord: promotion, ExperimentRecord: experiment, VerticalOperatingPolicy: policy,
});
