import { deepFreeze } from '../validation.js';
import { ACCEPTANCE_CONTEXT_STATUSES, opaqueHash } from '../auth/contracts.js';
import { COACHING_SESSION_STATES, COACH_CONNECT_PRIVACY_CLASSES, COMMITMENT_STATES, ENTITLEMENT_STATES, EVIDENCE_PROPOSAL_STATES, EVIDENCE_SUPPORT_STATES, INTERVENTION_STATES, INVITATION_STATES, JUDGMENT_CLASSES, PROMOTION_STAGES, RELATIONSHIP_STATES } from './constants.js';

const object = (value) => Boolean(value && typeof value === 'object' && !Array.isArray(value));
const timestamp = (value) => typeof value === 'string' && Number.isFinite(Date.parse(value));
const text = (value) => typeof value === 'string' && value.length > 0 && value.length <= 512;
const scopeValid = (scope) => object(scope) && ['tenant_id', 'profile_id', 'business_id', 'subscriber_id'].every((key) => text(scope[key]));
const result = (errors, value) => deepFreeze({ valid: errors.length === 0, errors, value: errors.length ? null : deepFreeze(structuredClone(value)) });

export function validateCoachConnectScope(scope) { const errors = []; if (!scopeValid(scope)) errors.push({ code: 'INVALID_EXACT_SCOPE', field: 'scope' }); return result(errors, scope); }

export function validateCoachInvitation(value) { const errors = []; if (!text(value?.invitation_id)) errors.push({ code: 'INVITATION_ID_REQUIRED' }); if (!scopeValid(value?.subscriber_scope)) errors.push({ code: 'INVALID_EXACT_SCOPE' }); if (!INVITATION_STATES.includes(value?.status)) errors.push({ code: 'INVALID_INVITATION_STATUS' }); if (!timestamp(value?.created_at) || !timestamp(value?.expires_at)) errors.push({ code: 'INVALID_INVITATION_TIME' }); if (!text(value?.token_hash) || value?.raw_token) errors.push({ code: 'OPAQUE_TOKEN_HASH_REQUIRED' }); if (value?.single_use !== true || value?.allowed_purpose !== 'COACH_CONNECT_ACCEPTANCE') errors.push({ code: 'INVITATION_POLICY_INVALID' }); return result(errors, value); }

export function validateCoachRelationship(value) { const errors = []; if (!text(value?.relationship_id) || !text(value?.coach_actor_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'RELATIONSHIP_IDENTITY_INVALID' }); if (!RELATIONSHIP_STATES.includes(value?.relationship_status)) errors.push({ code: 'INVALID_RELATIONSHIP_STATUS' }); if (!['GRANTED', 'REVOKED'].includes(value?.subscriber_consent_state)) errors.push({ code: 'INVALID_CONSENT' }); if (!['PENDING', 'ACCEPTED', 'DECLINED'].includes(value?.coach_acceptance_state)) errors.push({ code: 'INVALID_COACH_ACCEPTANCE' }); return result(errors, value); }

export function validateCoachEntitlement(value) { const errors = []; if (!text(value?.entitlement_id) || !text(value?.relationship_id) || !text(value?.coach_actor_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'ENTITLEMENT_IDENTITY_INVALID' }); if (!ENTITLEMENT_STATES.includes(value?.entitlement_status)) errors.push({ code: 'INVALID_ENTITLEMENT_STATUS' }); if (value?.price?.unit_amount !== 1995 || value?.price?.currency !== 'usd' || value?.price?.interval !== 'month') errors.push({ code: 'COACH_CONNECT_PRICE_MISMATCH' }); return result(errors, value); }

export function validateCoachingSession(value) { const errors = []; if (!text(value?.session_id) || !text(value?.relationship_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'SESSION_IDENTITY_INVALID' }); if (!COACHING_SESSION_STATES.includes(value?.status)) errors.push({ code: 'INVALID_COACHING_SESSION_STATUS' }); if (!COACH_CONNECT_PRIVACY_CLASSES.includes(value?.privacy_classification)) errors.push({ code: 'INVALID_PRIVACY_CLASS' }); return result(errors, value); }

export function validateCoachJudgment(value) { const errors = []; if (!text(value?.judgment_id) || !text(value?.coach_actor_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'JUDGMENT_IDENTITY_INVALID' }); if (!JUDGMENT_CLASSES.includes(value?.judgment_class) || !EVIDENCE_SUPPORT_STATES.includes(value?.evidence_support_status)) errors.push({ code: 'INVALID_JUDGMENT_CLASSIFICATION' }); if (!COACH_CONNECT_PRIVACY_CLASSES.includes(value?.privacy_classification)) errors.push({ code: 'INVALID_PRIVACY_CLASS' }); if (value?.system_authority_class !== 'ATTRIBUTED_COACH_JUDGMENT' || value?.canonical_authority !== false) errors.push({ code: 'COACH_AUTHORITY_ESCALATION' }); return result(errors, value); }

export function validateCoachConfidenceRecord(value) { const errors = []; if (value?.confidence_class !== 'COACHING_NOTE') errors.push({ code: 'COACHING_NOTE_CLASS_REQUIRED' }); if (!Number.isFinite(value?.current_weight) || value.current_weight < 0 || value.current_weight > 0.25) errors.push({ code: 'COACHING_NOTE_WEIGHT_OUT_OF_BOUNDS' }); if (value?.missing_evidence === true || value?.universal_learning_eligible !== false) errors.push({ code: 'CONFIDENCE_AUTHORITY_INVALID' }); return result(errors, value); }

export function validateCoachCommitment(value) { const errors = []; if (!text(value?.commitment_id) || !text(value?.session_id) || !text(value?.relationship_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'COMMITMENT_IDENTITY_INVALID' }); if (!COMMITMENT_STATES.includes(value?.status)) errors.push({ code: 'INVALID_COMMITMENT_STATUS' }); if (value?.status === 'COMPLETED' && value?.outcome_status === 'VALIDATED' && !value?.completion_evidence_reference) errors.push({ code: 'COMPLETION_EVIDENCE_REQUIRED' }); return result(errors, value); }

export function validateCoachInterventionProposal(value) { const errors = []; if (!text(value?.intervention_id) || !text(value?.session_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'INTERVENTION_IDENTITY_INVALID' }); if (!INTERVENTION_STATES.includes(value?.status)) errors.push({ code: 'INVALID_INTERVENTION_STATUS' }); if (value?.canonical_authority !== false || value?.completion_proves_outcome !== false) errors.push({ code: 'INTERVENTION_AUTHORITY_INVALID' }); return result(errors, value); }

export function validateCoachEvidenceProposal(value) { const errors = []; if (!text(value?.evidence_proposal_id) || !text(value?.session_id) || !scopeValid(value?.subscriber_scope)) errors.push({ code: 'EVIDENCE_PROPOSAL_IDENTITY_INVALID' }); if (!EVIDENCE_PROPOSAL_STATES.includes(value?.verification_status)) errors.push({ code: 'INVALID_EVIDENCE_PROPOSAL_STATUS' }); if (value?.coach_self_verified === true || value?.canonical_evidence === true) errors.push({ code: 'COACH_SELF_VERIFICATION_FORBIDDEN' }); return result(errors, value); }

export function validatePromotionRecord(value) { const errors = []; if (!text(value?.promotion_record_id) || !PROMOTION_STAGES.includes(value?.promotion_stage)) errors.push({ code: 'PROMOTION_IDENTITY_INVALID' }); if (value?.universal_learning_eligible !== false) errors.push({ code: 'UNIVERSAL_PROMOTION_FORBIDDEN' }); return result(errors, value); }

export function privacySafeCoachConnectEvent({ event_type, reason_code, occurred_at, actor_id = null, scope = null, references = {} }) { if (!text(event_type) || !text(reason_code) || !timestamp(occurred_at)) return deepFreeze({ ok: false, code: 'INVALID_AUDIT_EVENT' }); return deepFreeze({ ok: true, event: { event_id: opaqueHash('coach_connect_audit', { event_type, reason_code, occurred_at, actor_id, references }), event_type, reason_code, occurred_at, actor_ref: actor_id ? opaqueHash('actor', actor_id) : null, scope_ref: scope ? opaqueHash('scope', scope) : null, references: Object.fromEntries(Object.entries(references).map(([key, value]) => [key, opaqueHash(key, value)])) } }); }

export const AUTH_ACCEPTANCE_CONTEXT_STATES = ACCEPTANCE_CONTEXT_STATUSES;
