import { hashCanonicalJson } from '../hashing.js';
import { deepFreeze } from '../validation.js';
import { opaqueHash } from '../auth/contracts.js';
import { evaluateCoachConnectActivation } from './activation.js';
import { COACH_CONNECT_PRICE, PROMOTION_STAGES } from './constants.js';
import { privacySafeCoachConnectEvent, validateCoachConfidenceRecord, validateCoachEntitlement, validateCoachInvitation, validateCoachJudgment, validateCoachRelationship, validateCoachingSession, validatePromotionRecord } from './contracts.js';
import { projectCoachCockpit, projectSubscriberCoachConnect } from './projections.js';
import { transitionCoachingSession, transitionEntitlement, transitionInvitation, transitionJudgmentEvidence, transitionPromotion, transitionRelationship } from './stateMachines.js';

const sameScope = (a, b) => ['tenant_id', 'profile_id', 'business_id', 'subscriber_id'].every((key) => a?.[key] === b?.[key]);
const addMs = (time, ms) => new Date(Date.parse(time) + ms).toISOString();
const deny = (code, details = {}) => deepFreeze({ ok: false, code, ...details });
const cloneFreeze = (value) => deepFreeze(structuredClone(value));

export function createCoachConnectService({ store, authService, flags, clock = () => new Date().toISOString(), tokenFactory, invitationTtlMs = 900_000, billingVerifier = () => false, canonicalRuntimeAppend = null, billingConfig = {} }) {
  if (!store || typeof tokenFactory !== 'function' || !authService) throw new TypeError('store authService and tokenFactory are required');
  const product = { product_reference: billingConfig.product_reference || 'coach_connect_v1_synthetic', price_reference: billingConfig.price_reference || 'coach_connect_1995_monthly_synthetic', ...COACH_CONNECT_PRICE };
  const gate = (capability) => evaluateCoachConnectActivation({ flags, capability });
  const audit = (input) => { const made = privacySafeCoachConnectEvent(input); if (made.ok) store.appendEvent(made.event); return made.ok ? made.event.event_id : null; };
  const activate = (capability) => { const decision = gate(capability); return decision.allowed ? null : deny(decision.code); };

  function createInvitation({ subscriber_scope, created_by_actor, idempotency_key }) {
    const blocked = activate('INVITATION'); if (blocked) return blocked;
    if (!idempotency_key || !created_by_actor) return deny('INVITATION_COMMAND_INVALID');
    const existing = store.list('invites').find((item) => item.idempotency_key === idempotency_key);
    if (existing) return sameScope(existing.subscriber_scope, subscriber_scope) ? cloneFreeze({ ok: true, status: 'IDEMPOTENT_REPLAY', invitation: existing, qr_payload: null }) : deny('IDEMPOTENCY_CONFLICT');
    const token = tokenFactory('INVITATION'); if (typeof token !== 'string' || token.length < 24) return deny('SECURE_INVITATION_TOKEN_REQUIRED');
    const now = clock(), token_hash = opaqueHash('coach_invitation_token', token), invitation = { invitation_id: opaqueHash('coach_invitation', { token_hash, now }), subscriber_scope, created_by_actor, created_at: now, expires_at: addMs(now, invitationTtlMs), status: 'PENDING', token_hash, allowed_purpose: 'COACH_CONNECT_ACCEPTANCE', single_use: true, consumed_at: null, consumed_by_coach_actor: null, revoked_at: null, revoked_by_actor: null, superseded_by_invitation_id: null, version: 1, idempotency_key, metadata: {} };
    const validation = validateCoachInvitation(invitation); if (!validation.valid) return deny('INVALID_INVITATION', { errors: validation.errors });
    store.save('invites', invitation.invitation_id, invitation); const audit_reference = audit({ event_type: 'INVITATION_CREATED', reason_code: 'PENDING', occurred_at: now, actor_id: created_by_actor, scope: subscriber_scope, references: { invitation_id: invitation.invitation_id } });
    return cloneFreeze({ ok: true, status: 'CREATED', invitation, qr_payload: `more://coach-connect/accept?invite=${encodeURIComponent(token)}`, audit_reference });
  }

  function resolveInvitation({ token }) { const blocked = activate('QR'); if (blocked) return blocked; const tokenHash = opaqueHash('coach_invitation_token', token || ''), invitation = store.list('invites').find((item) => item.token_hash === tokenHash); if (!invitation) return deny('INVITATION_NOT_FOUND'); if (invitation.status !== 'PENDING') return deny(`INVITATION_${invitation.status}`); if (Date.parse(invitation.expires_at) <= Date.parse(clock())) { const moved = transitionInvitation(invitation.status, 'EXPIRE'), updated = { ...invitation, status: moved.current, version: invitation.version + 1 }; store.save('invites', updated.invitation_id, updated); audit({ event_type: 'INVITATION_EXPIRED', reason_code: 'TIME_LIMIT_REACHED', occurred_at: clock(), scope: invitation.subscriber_scope, references: { invitation_id: invitation.invitation_id } }); return deny('INVITATION_EXPIRED'); } return cloneFreeze({ ok: true, invitation_reference: invitation.invitation_id, expires_at: invitation.expires_at, purpose: invitation.allowed_purpose, subscriber_disclosure: null, grants_access: false }); }

  function closeInvitation({ invitation_id, action, actor_id, superseded_by_invitation_id = null }) { const blocked = activate('INVITATION'); if (blocked) return blocked; const invitation = store.get('invites', invitation_id); if (!invitation) return deny('INVITATION_NOT_FOUND'); const moved = transitionInvitation(invitation.status, action); if (!moved.ok) return deny(moved.code); const now = clock(), updated = { ...invitation, status: moved.current, version: invitation.version + 1, revoked_at: action === 'REVOKE' ? now : invitation.revoked_at, revoked_by_actor: action === 'REVOKE' ? actor_id : invitation.revoked_by_actor, superseded_by_invitation_id: action === 'SUPERSEDE' ? superseded_by_invitation_id : invitation.superseded_by_invitation_id }; store.save('invites', invitation_id, updated); const audit_reference = audit({ event_type: `INVITATION_${moved.current}`, reason_code: action, occurred_at: now, actor_id, scope: invitation.subscriber_scope, references: { invitation_id } }); return cloneFreeze({ ok: true, invitation: updated, audit_reference }); }

  function regenerateInvitation(input) { const prior = store.get('invites', input.invitation_id); if (!prior) return deny('INVITATION_NOT_FOUND'); const created = createInvitation({ subscriber_scope: prior.subscriber_scope, created_by_actor: input.actor_id, idempotency_key: input.idempotency_key, correlation_id: input.correlation_id }); if (!created.ok) return created; const closed = closeInvitation({ invitation_id: prior.invitation_id, action: 'SUPERSEDE', actor_id: input.actor_id, superseded_by_invitation_id: created.invitation.invitation_id }); return closed.ok ? created : closed; }

  function acceptInvitation({ token, auth_session_id, auth_session_token, subscriber_consent_reference }) {
    const blocked = activate('RELATIONSHIP'); if (blocked) return blocked;
    const resolved = resolveInvitation({ token }); if (!resolved.ok) return resolved;
    const auth = authService.futureCoachAuthDecision({ session_id: auth_session_id, session_token: auth_session_token }); if (!auth.ok || !auth.decision?.allowed) return deny(auth.decision?.reason_code || auth.code || 'AUTHENTICATED_VERIFIED_COACH_REQUIRED');
    if (!subscriber_consent_reference) return deny('SUBSCRIBER_CONSENT_REQUIRED');
    const invitation = store.get('invites', resolved.invitation_reference), duplicate = store.list('relationships').find((item) => item.coach_actor_id === auth.decision.coach_actor_id && sameScope(item.subscriber_scope, invitation.subscriber_scope) && !['REVOKED', 'EXPIRED', 'DECLINED'].includes(item.relationship_status));
    if (duplicate) return deny('DUPLICATE_RELATIONSHIP', { relationship_id: duplicate.relationship_id });
    const now = clock(), relationship = { relationship_id: opaqueHash('coach_relationship', { invitation_id: invitation.invitation_id, actor: auth.decision.coach_actor_id }), subscriber_scope: invitation.subscriber_scope, coach_actor_id: auth.decision.coach_actor_id, invitation_id: invitation.invitation_id, subscriber_consent_state: 'GRANTED', subscriber_consent_reference, coach_acceptance_state: 'ACCEPTED', relationship_status: 'ACCEPTED', created_at: now, accepted_at: now, activated_at: null, suspended_at: null, revoked_at: null, expired_at: null, ended_by_actor: null, reason_code: 'COACH_ACCEPTED', version: 1 };
    const validation = validateCoachRelationship(relationship); if (!validation.valid) return deny('INVALID_RELATIONSHIP', { errors: validation.errors });
    const consumed = transitionInvitation(invitation.status, 'CONSUME'); if (!consumed.ok) return deny(consumed.code); store.save('invites', invitation.invitation_id, { ...invitation, status: consumed.current, consumed_at: now, consumed_by_coach_actor: auth.decision.coach_actor_id, version: invitation.version + 1 }); store.save('relationships', relationship.relationship_id, relationship);
    const audit_reference = audit({ event_type: 'RELATIONSHIP_ACCEPTED', reason_code: 'EXACT_COACH_BOUND', occurred_at: now, actor_id: auth.decision.coach_actor_id, scope: relationship.subscriber_scope, references: { relationship_id: relationship.relationship_id, invitation_id: invitation.invitation_id } });
    return cloneFreeze({ ok: true, relationship, audit_reference });
  }

  function changeRelationship({ relationship_id, action, actor_id, reason_code }) { const blocked = activate('RELATIONSHIP'); if (blocked) return blocked; const current = store.get('relationships', relationship_id); if (!current) return deny('RELATIONSHIP_NOT_FOUND'); const moved = transitionRelationship(current.relationship_status, action); if (!moved.ok) return deny(moved.code); const now = clock(), updated = { ...current, relationship_status: moved.current, reason_code: reason_code || action, version: current.version + 1, activated_at: moved.current === 'ACTIVE' ? now : current.activated_at, suspended_at: moved.current === 'SUSPENDED' ? now : current.suspended_at, revoked_at: moved.current === 'REVOKED' ? now : current.revoked_at, expired_at: moved.current === 'EXPIRED' ? now : current.expired_at, ended_by_actor: ['REVOKED', 'DECLINED'].includes(moved.current) ? actor_id : current.ended_by_actor, subscriber_consent_state: moved.current === 'REVOKED' ? 'REVOKED' : current.subscriber_consent_state }; store.save('relationships', relationship_id, updated); const audit_reference = audit({ event_type: `RELATIONSHIP_${moved.current}`, reason_code: updated.reason_code, occurred_at: now, actor_id, scope: current.subscriber_scope, references: { relationship_id } }); return cloneFreeze({ ok: true, relationship: updated, audit_reference }); }

  function createCheckoutContext({ relationship_id, coach_actor_id }) { const blocked = activate('CHECKOUT'); if (blocked) return blocked; const relationship = store.get('relationships', relationship_id); if (!relationship || relationship.coach_actor_id !== coach_actor_id || relationship.relationship_status !== 'ACCEPTED' || relationship.subscriber_consent_state !== 'GRANTED') return deny('CHECKOUT_RELATIONSHIP_INVALID'); const existing = store.list('entitlements').find((item) => item.relationship_id === relationship_id && !['CANCELLED', 'EXPIRED'].includes(item.entitlement_status)); if (existing) return cloneFreeze({ ok: true, status: 'IDEMPOTENT_REPLAY', entitlement: existing, provider_request: null }); const now = clock(), entitlement = { entitlement_id: opaqueHash('coach_entitlement', relationship_id), relationship_id, coach_actor_id, subscriber_scope: relationship.subscriber_scope, billing_provider: 'STRIPE_SYNTHETIC_TRANSLATION', billing_customer_reference: null, billing_subscription_reference: null, billing_product_reference: product.product_reference, billing_price_reference: product.price_reference, price: { currency: product.currency, unit_amount: product.unit_amount, interval: product.interval }, entitlement_status: 'PENDING', current_period_start: null, current_period_end: null, cancel_at_period_end: false, cancelled_at: null, suspended_at: null, provider_event_cursor: 0, created_at: now, updated_at: now, version: 1 };
    const validation = validateCoachEntitlement(entitlement); if (!validation.valid) return deny('INVALID_ENTITLEMENT', { errors: validation.errors }); store.save('entitlements', entitlement.entitlement_id, entitlement); return cloneFreeze({ ok: true, status: 'CREATED', entitlement, provider_request: { mode: 'subscription', livemode: false, product_reference: product.product_reference, price_reference: product.price_reference, relationship_reference: opaqueHash('billing_relationship', relationship_id), entitlement_reference: entitlement.entitlement_id, unit_amount: 1995, currency: 'usd', interval: 'month', protected_business_content: null } }); }

  function processBillingEvent({ event }) { const blocked = activate('BILLING_EVENT'); if (blocked) return blocked; if (!billingVerifier(event) || event?.livemode !== false) return deny('BILLING_EVENT_UNVERIFIED'); if (store.billingEvents.has(event.event_id)) return cloneFreeze({ ok: true, status: 'IDEMPOTENT_REPLAY', result: store.billingEvents.get(event.event_id) }); const entitlement = store.get('entitlements', event.entitlement_id); if (!entitlement) return deny('ENTITLEMENT_NOT_FOUND'); if (event.relationship_id !== entitlement.relationship_id || event.coach_actor_id !== entitlement.coach_actor_id || !sameScope(event.subscriber_scope, entitlement.subscriber_scope) || event.product_reference !== product.product_reference || event.price_reference !== product.price_reference) return deny('BILLING_OBJECT_MISMATCH'); if (!Number.isInteger(event.cursor) || event.cursor <= entitlement.provider_event_cursor) { const stale = { event_id: event.event_id, status: 'STALE_EVENT_IGNORED', entitlement_id: entitlement.entitlement_id }; store.billingEvents.set(event.event_id, stale); return cloneFreeze({ ok: true, status: stale.status, result: stale }); }
    const actions = { ACTIVE: ['PAST_DUE', 'SUSPENDED'].includes(entitlement.entitlement_status) ? 'RECOVER' : 'ACTIVATE', PAST_DUE: 'PAYMENT_FAIL', SUSPENDED: 'SUSPEND', CANCELLED: 'CANCEL', EXPIRED: 'EXPIRE', DISPUTED: 'DISPUTE' }; const action = actions[event.target_status]; if (!action) return deny('UNSUPPORTED_BILLING_STATUS'); const moved = transitionEntitlement(entitlement.entitlement_status, action); if (!moved.ok) return deny(moved.code); const now = clock(), updated = { ...entitlement, entitlement_status: moved.current, billing_customer_reference: event.customer_reference, billing_subscription_reference: event.subscription_reference, current_period_start: event.current_period_start || entitlement.current_period_start, current_period_end: event.current_period_end || entitlement.current_period_end, cancel_at_period_end: Boolean(event.cancel_at_period_end), cancelled_at: moved.current === 'CANCELLED' ? now : entitlement.cancelled_at, suspended_at: ['SUSPENDED', 'DISPUTED'].includes(moved.current) ? now : entitlement.suspended_at, provider_event_cursor: event.cursor, updated_at: now, version: entitlement.version + 1 }; store.save('entitlements', updated.entitlement_id, updated);
    const relationship = store.get('relationships', updated.relationship_id); if (moved.current === 'ACTIVE' && relationship.relationship_status === 'ACCEPTED' && relationship.subscriber_consent_state === 'GRANTED') changeRelationship({ relationship_id: relationship.relationship_id, action: 'ACTIVATE', actor_id: 'billing_translation', reason_code: 'ENTITLEMENT_ACTIVE' }); else if (moved.current !== 'ACTIVE' && relationship.relationship_status === 'ACTIVE') changeRelationship({ relationship_id: relationship.relationship_id, action: 'SUSPEND', actor_id: 'billing_translation', reason_code: `ENTITLEMENT_${moved.current}` });
    const result = { event_id: event.event_id, status: 'APPLIED', entitlement_status: moved.current, entitlement_id: updated.entitlement_id }; store.billingEvents.set(event.event_id, result); audit({ event_type: `ENTITLEMENT_${moved.current}`, reason_code: event.type, occurred_at: now, actor_id: updated.coach_actor_id, scope: updated.subscriber_scope, references: { entitlement_id: updated.entitlement_id, provider_event_id: event.event_id } }); return cloneFreeze({ ok: true, status: 'APPLIED', entitlement: updated, result });
  }

  function authorize({ relationship_id, entitlement_id, requested_scope, requested_resource, requested_action, purpose, auth_session_id, auth_session_token }) { const blocked = activate(requested_resource === 'COACHING_SESSION' ? 'SESSION' : 'COCKPIT'); if (blocked) return cloneFreeze({ allowed: false, reason_code: blocked.code }); const auth = authService.futureCoachAuthDecision({ session_id: auth_session_id, session_token: auth_session_token }); const relationship = store.get('relationships', relationship_id), entitlement = store.get('entitlements', entitlement_id), now = clock(); let reason = 'AUTHORIZED'; if (!auth.ok || !auth.decision?.allowed) reason = auth.decision?.reason_code || auth.code || 'INVALID_SESSION'; else if (!relationship || !entitlement) reason = 'RELATIONSHIP_OR_ENTITLEMENT_NOT_FOUND'; else if (relationship.coach_actor_id !== auth.decision.coach_actor_id || entitlement.coach_actor_id !== auth.decision.coach_actor_id) reason = 'ACTOR_SCOPE_MISMATCH'; else if (!sameScope(requested_scope, relationship.subscriber_scope) || !sameScope(requested_scope, entitlement.subscriber_scope) || entitlement.relationship_id !== relationship.relationship_id) reason = 'EXACT_SCOPE_MISMATCH'; else if (relationship.relationship_status !== 'ACTIVE') reason = `RELATIONSHIP_${relationship.relationship_status}`; else if (relationship.subscriber_consent_state !== 'GRANTED') reason = 'CONSENT_REQUIRED'; else if (entitlement.entitlement_status !== 'ACTIVE') reason = `ENTITLEMENT_${entitlement.entitlement_status}`; else if (!['COACH_COCKPIT', 'COACHING_SESSION'].includes(requested_resource) || !['READ', 'CONNECT', 'CREATE'].includes(requested_action) || purpose !== 'AUTHORIZED_COACHING') reason = 'RESOURCE_ACTION_PURPOSE_DENIED'; const allowed = reason === 'AUTHORIZED', audit_reference = audit({ event_type: allowed ? 'AUTHORITY_ALLOWED' : 'AUTHORITY_DENIED', reason_code: reason, occurred_at: now, actor_id: auth.decision?.coach_actor_id, scope: requested_scope, references: { relationship_id, entitlement_id } }); return cloneFreeze({ allowed, reason_code: reason, evaluated_scope: requested_scope, relationship_status: relationship?.relationship_status || null, entitlement_status: entitlement?.entitlement_status || null, consent_status: relationship?.subscriber_consent_state || null, feature_status: 'ACTIVE', decision_timestamp: now, audit_reference, canonical_mutation_allowed: false, one_move_authorization_allowed: false, five_futures_mutation_allowed: false }); }

  function cockpit(input) { const authority = authorize({ ...input, requested_resource: 'COACH_COCKPIT', requested_action: 'READ', purpose: 'AUTHORIZED_COACHING' }); if (!authority.allowed) return deny(authority.reason_code, { authority }); const relationship = store.get('relationships', input.relationship_id), entitlement = store.get('entitlements', input.entitlement_id); return projectCoachCockpit({ authority, business_engine_projection: input.business_engine_projection, relationship, entitlement, sessions: store.list('sessions').filter((item) => item.relationship_id === relationship.relationship_id), confidence_records: store.list('confidence').filter((item) => item.relationship_id === relationship.relationship_id), generated_at: clock() }); }

  function createSession({ relationship_id, entitlement_id, subscriber_scope, auth_session_id, auth_session_token, idempotency_key }) { const authority = authorize({ relationship_id, entitlement_id, requested_scope: subscriber_scope, requested_resource: 'COACHING_SESSION', requested_action: 'CREATE', purpose: 'AUTHORIZED_COACHING', auth_session_id, auth_session_token }); if (!authority.allowed) return deny(authority.reason_code); const existing = store.list('sessions').find((item) => item.idempotency_key === idempotency_key); if (existing) return sameScope(existing.subscriber_scope, subscriber_scope) && existing.relationship_id === relationship_id ? cloneFreeze({ ok: true, status: 'IDEMPOTENT_REPLAY', session: existing }) : deny('IDEMPOTENCY_CONFLICT'); const relationship = store.get('relationships', relationship_id), now = clock(), session = { session_id: opaqueHash('coaching_session', { relationship_id, idempotency_key }), relationship_id, subscriber_scope, coach_actor_id: relationship.coach_actor_id, entitlement_id, status: 'DRAFT', scheduled_reference: null, started_at: null, ended_at: null, duration_seconds: null, session_mode: 'STRUCTURED_NON_VOICE', source_artifact_references: [], privacy_classification: 'COACH_SESSION_PRIVATE', created_at: now, updated_at: now, version: 1, idempotency_key, recovery_count: 0, structured_artifact: null };
    const validation = validateCoachingSession(session); if (!validation.valid) return deny('INVALID_COACHING_SESSION', { errors: validation.errors }); store.save('sessions', session.session_id, session); return cloneFreeze({ ok: true, status: 'CREATED', session }); }

  function transitionSession({ session_id, action, structured_artifact = null }) { const session = store.get('sessions', session_id); if (!session) return deny('COACHING_SESSION_NOT_FOUND'); const moved = transitionCoachingSession(session.status, action); if (!moved.ok) return deny(moved.code); if (action === 'COMPLETE' && (!structured_artifact || !Array.isArray(structured_artifact.judgments))) return deny('STRUCTURED_SESSION_ARTIFACT_REQUIRED'); const now = clock(), updated = { ...session, status: moved.current, version: session.version + 1, updated_at: now, started_at: action === 'START' ? now : session.started_at, ended_at: action === 'COMPLETE' ? now : session.ended_at, recovery_count: action === 'INTERRUPT' ? session.recovery_count + 1 : session.recovery_count, structured_artifact: action === 'COMPLETE' ? { judgments: structured_artifact.judgments.map((item) => ({ class: item.class, protected_summary_reference: item.protected_summary_reference })), commitments: structured_artifact.commitments || [], evidence_candidates: structured_artifact.evidence_candidates || [], raw_transcript: null, canonical_mutation: false } : session.structured_artifact }; store.save('sessions', session_id, updated); audit({ event_type: `SESSION_${moved.current}`, reason_code: action, occurred_at: now, actor_id: session.coach_actor_id, scope: session.subscriber_scope, references: { session_id } }); return cloneFreeze({ ok: true, session: updated }); }

  function recordJudgment({ session_id, judgment_class, protected_summary_reference, coach_confidence, privacy_classification = 'COACH_SESSION_PRIVATE' }) { const session = store.get('sessions', session_id); if (!session || !['IN_PROGRESS', 'COMPLETED'].includes(session.status)) return deny('ACTIVE_OR_COMPLETED_SESSION_REQUIRED'); const now = clock(), judgment = { judgment_id: opaqueHash('coach_judgment', { session_id, judgment_class, protected_summary_reference }), session_id, relationship_id: session.relationship_id, subscriber_scope: session.subscriber_scope, coach_actor_id: session.coach_actor_id, judgment_class, content_reference_or_protected_summary: protected_summary_reference, coach_confidence, system_authority_class: 'ATTRIBUTED_COACH_JUDGMENT', evidence_support_status: 'UNSUPPORTED', contradiction_status: 'NONE', subscriber_visibility: privacy_classification === 'COACH_ATTRIBUTED_SHAREABLE' ? 'GOVERNED_SUMMARY_ELIGIBLE' : 'PRIVATE', privacy_classification, created_at: now, updated_at: now, version: 1, canonical_authority: false }; const validation = validateCoachJudgment(judgment); if (!validation.valid) return deny('INVALID_COACH_JUDGMENT', { errors: validation.errors }); store.save('judgments', judgment.judgment_id, judgment); return cloneFreeze({ ok: true, judgment }); }

  function updateJudgmentEvidence({ judgment_id, action }) { const judgment = store.get('judgments', judgment_id); if (!judgment) return deny('JUDGMENT_NOT_FOUND'); const moved = transitionJudgmentEvidence(judgment.evidence_support_status, action); if (!moved.ok) return deny(moved.code); const updated = { ...judgment, evidence_support_status: moved.current, contradiction_status: moved.current === 'CONTRADICTED' ? 'MATERIAL_CONTRADICTION' : judgment.contradiction_status, updated_at: clock(), version: judgment.version + 1 }; store.save('judgments', judgment_id, updated); const confidence = store.list('confidence').find((item) => item.source_judgment_id === judgment_id); if (confidence) store.save('confidence', confidence.confidence_record_id, { ...confidence, evidence_status: moved.current, contradiction_status: updated.contradiction_status, current_weight: ['CONTRADICTED', 'DISPROVEN'].includes(moved.current) ? 0 : moved.current === 'SUPPORTED' ? 0.25 : confidence.current_weight, promotion_eligibility: moved.current === 'SUPPORTED' ? 'ELIGIBLE_FOR_EVALUATION' : 'HELD' }); return cloneFreeze({ ok: true, judgment: updated }); }

  function createCoachingNote({ judgment_id }) { const judgment = store.get('judgments', judgment_id); if (!judgment) return deny('JUDGMENT_NOT_FOUND'); const now = clock(), note = { confidence_record_id: opaqueHash('coach_confidence', judgment_id), subscriber_scope: judgment.subscriber_scope, relationship_id: judgment.relationship_id, session_id: judgment.session_id, coach_actor_id: judgment.coach_actor_id, source_judgment_id: judgment_id, confidence_class: 'COACHING_NOTE', subject_reference: judgment.content_reference_or_protected_summary, current_weight: judgment.evidence_support_status === 'SUPPORTED' ? 0.25 : 0.1, evidence_status: judgment.evidence_support_status, contradiction_status: judgment.contradiction_status, subscriber_confirmation_status: 'NOT_REQUESTED', promotion_eligibility: judgment.evidence_support_status === 'SUPPORTED' ? 'ELIGIBLE_FOR_EVALUATION' : 'HELD_FOR_EVIDENCE', validation_pathway: 'PROMOTION_LADDER_V1', privacy_classification: judgment.privacy_classification, created_at: now, updated_at: now, version: 1, missing_evidence: false, universal_learning_eligible: false, canonical_authority: false };
    const validation = validateCoachConfidenceRecord(note); if (!validation.valid) return deny('INVALID_COACHING_NOTE', { errors: validation.errors }); store.save('confidence', note.confidence_record_id, note); audit({ event_type: 'COACHING_NOTE_CREATED', reason_code: note.evidence_status, occurred_at: now, actor_id: note.coach_actor_id, scope: note.subscriber_scope, references: { confidence_record_id: note.confidence_record_id } }); return cloneFreeze({ ok: true, coaching_note: note, evidence_request_required: note.evidence_status !== 'SUPPORTED' }); }

  function createPromotion({ judgment_id }) { const blocked = activate('PROMOTION'); if (blocked) return blocked; const judgment = store.get('judgments', judgment_id); if (!judgment) return deny('JUDGMENT_NOT_FOUND'); const now = clock(), record = { promotion_record_id: opaqueHash('coach_promotion', judgment_id), source_judgment_or_proposal_id: judgment_id, subscriber_scope: judgment.subscriber_scope, relationship_id: judgment.relationship_id, promotion_stage: 'COACH_OBSERVATION', business_engine_evaluation: null, subscriber_confirmation_state: 'NOT_REQUESTED', supporting_evidence_references: [], outcome_validation_references: [], canonical_mutation_reference: null, status: 'PENDING', created_at: now, updated_at: now, version: 1, universal_learning_eligible: false, history: [{ stage: 'COACH_OBSERVATION', at: now }] }; const validation = validatePromotionRecord(record); if (!validation.valid) return deny('INVALID_PROMOTION_RECORD', { errors: validation.errors }); store.save('promotions', record.promotion_record_id, record); return cloneFreeze({ ok: true, promotion: record }); }

  function advancePromotion({ promotion_record_id, expected_next_stage, business_engine_evaluation = null, subscriber_confirmation_state = null, supporting_evidence_references = null, outcome_validation_references = null, canonical_event = null }) { const blocked = activate('PROMOTION'); if (blocked) return blocked; const record = store.get('promotions', promotion_record_id); if (!record) return deny('PROMOTION_NOT_FOUND'); const moved = transitionPromotion(record.promotion_stage, 'ADVANCE'); if (!moved.ok || moved.current !== expected_next_stage) return deny('PROMOTION_STAGE_SKIP_DENIED'); if (moved.current === 'BUSINESS_ENGINE_EVALUATION' && !business_engine_evaluation) return deny('BUSINESS_ENGINE_EVALUATION_REQUIRED'); if (record.business_engine_evaluation === 'REJECTED') return deny('BUSINESS_ENGINE_REJECTED_PROMOTION'); if (moved.current === 'SUBSCRIBER_CONFIRMATION' && !subscriber_confirmation_state) return deny('SUBSCRIBER_CONFIRMATION_REQUIRED'); if (moved.current === 'SUPPORTING_EVIDENCE' && !(supporting_evidence_references?.length)) return deny('SUPPORTING_EVIDENCE_REQUIRED'); if (moved.current === 'OUTCOME_VALIDATION' && !(outcome_validation_references?.length)) return deny('OUTCOME_VALIDATION_REQUIRED'); if (moved.current === 'CANONICAL_BUSINESS_STATE' && (record.subscriber_confirmation_state !== 'CONFIRMED' || !record.supporting_evidence_references.length || !record.outcome_validation_references.length || typeof canonicalRuntimeAppend !== 'function' || !canonical_event)) return deny('CANONICAL_RUNTIME_AUTHORITY_REQUIRED');
    const now = clock(), updated = { ...record, promotion_stage: moved.current, business_engine_evaluation: business_engine_evaluation ?? record.business_engine_evaluation, subscriber_confirmation_state: subscriber_confirmation_state ?? record.subscriber_confirmation_state, supporting_evidence_references: supporting_evidence_references ?? record.supporting_evidence_references, outcome_validation_references: outcome_validation_references ?? record.outcome_validation_references, status: moved.current === 'CANONICAL_BUSINESS_STATE' ? 'COMPLETED' : 'ADVANCED', updated_at: now, version: record.version + 1, history: [...record.history, { stage: moved.current, at: now }] };
    if (moved.current === 'CANONICAL_BUSINESS_STATE') { const appended = canonicalRuntimeAppend({ ...canonical_event, confirmation_status: 'CONFIRMED_AS_PROPOSED', source_promotion_record_id: promotion_record_id }); if (!appended?.ok) return deny('CANONICAL_RUNTIME_APPEND_FAILED'); updated.canonical_mutation_reference = appended.event_id || appended.reference; }
    store.save('promotions', promotion_record_id, updated); audit({ event_type: moved.current === 'CANONICAL_BUSINESS_STATE' ? 'CANONICAL_UPDATE_COMPLETED' : 'PROMOTION_ADVANCED', reason_code: moved.current, occurred_at: now, scope: record.subscriber_scope, references: { promotion_record_id } }); return cloneFreeze({ ok: true, promotion: updated }); }

  function subscriberProjection({ invitation_id = null, relationship_id = null, entitlement_id = null, confirmation_requests = [], governed_updates = [] }) { const active = gate('SUBSCRIBER_PROJECTION'); return projectSubscriberCoachConnect({ enabled: active.allowed, invitation: invitation_id ? store.get('invites', invitation_id) : null, relationship: relationship_id ? store.get('relationships', relationship_id) : null, entitlement: entitlement_id ? store.get('entitlements', entitlement_id) : null, confirmation_requests, governed_updates }); }
  function exactRelationship({ relationship_id, coach_actor_id }) { const relationship = store.get('relationships', relationship_id); return relationship?.coach_actor_id === coach_actor_id ? cloneFreeze({ ok: true, relationship }) : deny('RELATIONSHIP_NOT_FOUND'); }
  function inspect() { return cloneFreeze({ public_routes: [], price: product, one_business_engine: true, second_business_engine: false, live_billing: false, live_provider: false, canonical_write_entry: canonicalRuntimeAppend ? 'INJECTED_GOVERNED_RUNTIME_ONLY' : null, broad_relationship_list: false, stored_hash: hashCanonicalJson(store.snapshot()) }); }
  return Object.freeze({ createInvitation, resolveInvitation, closeInvitation, regenerateInvitation, acceptInvitation, changeRelationship, createCheckoutContext, processBillingEvent, authorize, cockpit, createSession, transitionSession, recordJudgment, updateJudgmentEvidence, createCoachingNote, createPromotion, advancePromotion, subscriberProjection, exactRelationship, inspect });
}
