import { hashCanonicalJson } from '../hashing.js'; import { deepFreeze } from '../validation.js';
const ROLE_ACTIONS=Object.freeze({SUBSCRIBER:['READ_SUBSCRIBER','WRITE_CONFIRMED_EVIDENCE','EXPORT_SELF'],COACH:['READ_AUTHORIZED_COACH','PROPOSE_SHARE'],ADMIN:['READ_AUDIT','PLAN_DELETION','PLAN_EXPORT'],SYSTEM:['REFRESH_PROJECTION','MODEL_PROPOSAL'],RECOVERY_OPERATOR:['REPLAY','REBUILD']});
export const RETENTION_CLASSES=Object.freeze({TENANT_PRIVATE:{status:'NOT_CONFIGURED',action:'BLOCK_DESTRUCTIVE_EXECUTION'},COACH_SESSION_PRIVATE:{status:'NOT_CONFIGURED',action:'BLOCK_DESTRUCTIVE_EXECUTION'},SYSTEM_INTERNAL:{status:'NOT_CONFIGURED',action:'BLOCK_DESTRUCTIVE_EXECUTION'},ANONYMIZED_AGGREGATE:{status:'NOT_CONFIGURED',action:'BLOCK_DESTRUCTIVE_EXECUTION'}});
const exactScope=(a,b)=>['tenant_id','profile_id','business_id'].every(k=>a?.[k]&&a[k]===b?.[k]);
const sessionExpired=(session,asOf)=>{if(!session?.expires_at)return false;const expiresAt=Date.parse(session.expires_at),evaluatedAt=Date.parse(asOf);return !Number.isFinite(expiresAt)||!Number.isFinite(evaluatedAt)||expiresAt<=evaluatedAt;};
export function authorizeRuntimeOperation({scope,actor,session,action,resource_scope,relationship=null,as_of_at}){let code='AUTHORIZED';if(!exactScope(scope,resource_scope)||!actor?.actor_id||!session?.session_id)code='SCOPE_OR_IDENTITY_REQUIRED';else if(actor.revoked===true||session.invalidated===true||sessionExpired(session,as_of_at))code='ACTOR_OR_SESSION_REVOKED';else if(!(ROLE_ACTIONS[actor.role]||[]).includes(action))code='ACTION_DENIED';else if(action==='READ_AUTHORIZED_COACH'&&(!relationship||relationship.status!=='ACTIVE'||!exactScope(relationship,scope)))code='COACH_RELATIONSHIP_DENIED';return deepFreeze({authorized:code==='AUTHORIZED',code,policy_version:'runtime-authorization-v1'});}
const BLOCKED_KEYS=new Set(['raw_payload','payload','transcript','notes','note','content','content_ref','prompt','response','secret','token','authorization','coach_private']);
export function redactProtected(value,depth=0){if(depth>8)return'[DEPTH_LIMIT]';if(Array.isArray(value))return value.slice(0,100).map(x=>redactProtected(x,depth+1));if(value&&typeof value==='object'){const out={};for(const[key,child]of Object.entries(value).slice(0,100))out[key]=BLOCKED_KEYS.has(key.toLowerCase())?'[REDACTED]':redactProtected(child,depth+1);return out;}return typeof value==='string'&&value.length>500?`${value.slice(0,80)}…[TRUNCATED]`:value;}
export function createSecurityAuditRecord(input){const safe={audit_version:'1.0.0',audit_id:input.audit_id,occurred_at:input.occurred_at,actor_ref:input.actor_ref,session_ref:input.session_ref,action:input.action,resource_type:input.resource_type,resource_ref:input.resource_ref,scope_hash:hashCanonicalJson(input.scope),purpose:input.purpose,decision:input.decision,reason_codes:[...(input.reason_codes||[])].sort(),policy_version:input.policy_version,correlation_id:input.correlation_id,idempotency_key_hash:input.idempotency_key?hashCanonicalJson(input.idempotency_key):null,before_hash:input.before_hash||null,after_hash:input.after_hash||null};return deepFreeze({...safe,audit_hash:hashCanonicalJson(safe)});}
export function createDataWorkflow({type,scope,actor,as_of_at,legal_hold=false}){if(!['DELETION','EXPORT'].includes(type)||!scope?.tenant_id||!actor?.actor_id)return deepFreeze({ok:false,code:'WORKFLOW_INPUT_REQUIRED'});const status=type==='DELETION'?(legal_hold?'BLOCKED_BY_LEGAL_HOLD':'REQUESTED'):'REQUESTED';const body={workflow_type:type,scope_hash:hashCanonicalJson(scope),actor_ref:actor.actor_id,status,legal_hold,retention_policy_status:'NOT_CONFIGURED',destructive_execution_authorized:false,requested_at:as_of_at,steps:['IDENTITY_SCOPE_VERIFY','AUTHORIZATION_VERIFY',...(type==='DELETION'?['LEGAL_HOLD_CHECK','PLAN_TOMBSTONE_OR_KEY_ERASURE','VERIFY']:['PRIVACY_FILTER','PACKAGE','VERIFY'])]};return deepFreeze({ok:true,workflow:{...body,workflow_id:`workflow_${hashCanonicalJson(body).slice(0,20)}`}});}
export const SECURITY_ASSUMPTIONS=deepFreeze({encryption_in_transit:'REQUIRED_NOT_VERIFIED',encryption_at_rest:'REQUIRED_NOT_VERIFIED',secrets:'EXTERNAL_SECRET_MANAGER_REQUIRED_NO_VALUES_IN_SOURCE',compliance_certification:'NONE'});
