import { useState, useMemo, useEffect } from "react"
import MiniProfileReport from "./components/reports/MiniProfileReport.jsx";
import WebProfileReport from "./components/reports/WebProfileReport.jsx";
import Page0A_OrganizationalContext from "./components/Page0A_OrganizationalContext.jsx";
import Page0B_ContextualSignals from "./components/Page0B_ContextualSignals.jsx";
import MOREMINDMAP_QUESTIONS from "./lib/assessments/moremindmap-questions";
import { createCheckoutIdempotencyKey, startStripeCheckout } from "./lib/stripeCheckout.js";
import UniversalTranslatorDrawer from "./components/universalTranslator/UniversalTranslatorDrawer.jsx";
import {
  ORDINARY_CUSTOMER_ENTRY_UNAVAILABLE_MESSAGE,
  resolveOrdinaryBosEntry,
} from "./lib/customerEntry/ordinaryCustomerEntryRouting.js";
import {
  createBosDraftCoordinator,
  createBosDraftSnapshot,
} from "./lib/bosIntakeDurability.js";
import {
  createBosSubmissionGuard,
  hasUsableBosCompletedHtml,
  normalizeBosCanonicalProfileId,
  pollBosGenerationJob,
  runBosGenerationRequest,
} from "./lib/bosGenerationJourney.js";
import { renewStoredPublicStartToken } from './lib/publicProductStartSession.js';
import {
  resolveRecruitingBosLanding,
  resumeRecruitingBoundBos,
} from './lib/recruitingV1/continuation.js';

// Complimentary authority is server-owned by publicSiteAirlockV1. No active
// capability value or digest may be shipped in this client bundle.
const BEHAVIOR_PROFILE_PROMO_CODES = new Set()

function publicStartToken() {
  if (typeof window === 'undefined') return ''
  return window.sessionStorage.getItem('more.public.start_token.v1') || ''
}

function publicStartHeaders(headers = {}) {
  const token = publicStartToken()
  return token ? { ...headers, 'X-MORE-Start-Token': token } : headers
}

function visibleTextFromHtml(html, maxLength = 5000) {
  if (!html) return "";
  if (typeof window !== "undefined" && window.DOMParser) {
    const parsed = new window.DOMParser().parseFromString(String(html), "text/html");
    return String(parsed.body?.textContent || "")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, maxLength);
  }
  return String(html)
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maxLength);
}

function cleanVisibleProfileText(text) {
  return String(text || "")
    .replace(/\s+/g, " ")
    .replace(/MORE MINDMAP SYSTEM/gi, " ")
    .replace(/Generated by MORE MindMap System/gi, " ")
    .replace(/Prepared for:/gi, " ")
    .trim();
}

const BOS_SECTION_MAPPINGS = [
  {
    title: "Behavior Operating System summary",
    pattern: /\b(executive summary|summary|behavioral intelligence profile|behavioral profile|personal operating profile|profile report)\b/i
  },
  {
    title: "Core Operating Style",
    pattern: /\b(how you operate|operating pattern|operating style|primary pattern|secondary pattern|behavioral pattern|primary drivers|dominance structure)\b/i
  },
  {
    title: "Behavioral Advantages",
    pattern: /\b(strengths?|advantages?|what works|natural advantage|operating advantage|superpower|leverage)\b/i
  },
  {
    title: "Behavioral Risks",
    pattern: /\b(risks?|watch outs?|constraints?|where it can cost you|blind spots?|drag|de-prioritized|wrong-seat|operating risk)\b/i
  },
  {
    title: "Pressure Pattern",
    pattern: /\b(under pressure|pressure|stress|system under strain|strained|when pressure rises)\b/i
  },
  {
    title: "Communication Style",
    pattern: /\b(communication|how others experience you|others experience|message|listening|persuasion)\b/i
  },
  {
    title: "Decision Style",
    pattern: /\b(decision|decision-making|decide|clarity|command clarity|speed vs fidelity)\b/i
  },
  {
    title: "Execution Pattern",
    pattern: /\b(execution|follow through|follow-through|systems?|implementation|fidelity|finish|operational)\b/i
  },
  {
    title: "Growth Edge",
    pattern: /\b(growth|scaling|scale|growth edge|next level|purposeful scale|scaling constraint)\b/i
  },
  {
    title: "Recommended Next Move",
    pattern: /\b(recommended|next step|next move|one move|intervention|highest-leverage)\b/i
  },
  {
    title: "Profile DNA / DNA Summary",
    pattern: /\b(profile dna|dna summary|your dna|behavioral dna|dna signature)\b/i
  }
];

const BOS_SECTION_BUTTON_PRIORITY = [
  "Core Operating Style",
  "Behavioral Advantages",
  "Behavioral Risks",
  "Pressure Pattern",
  "Communication Style",
  "Growth Edge",
  "Profile DNA / DNA Summary"
];

const BOS_SECTION_BUTTON_LABELS = {
  "Core Operating Style": "Explain operating style",
  "Behavioral Advantages": "Explain advantages",
  "Behavioral Risks": "Explain risks",
  "Pressure Pattern": "Explain pressure pattern",
  "Communication Style": "Explain communication style",
  "Growth Edge": "Explain growth edge",
  "Profile DNA / DNA Summary": "Explain profile DNA"
};

function categoryForBosHeading(heading) {
  const match = BOS_SECTION_MAPPINGS.find((section) => section.pattern.test(heading));
  return match?.title || "";
}

function headingLooksUseful(text) {
  const cleaned = cleanVisibleProfileText(text);
  if (cleaned.length < 3 || cleaned.length > 110) return false;
  if (/^(more mindmap|profile id|prepared for|generated by|back to home)$/i.test(cleaned)) return false;
  return /[a-z]/i.test(cleaned);
}

function parseBosHtmlSections(html) {
  if (typeof window === "undefined" || !window.DOMParser || !html) return [];
  const parsed = new window.DOMParser().parseFromString(String(html), "text/html");
  const body = parsed.body;
  if (!body) return [];

  const headingNodes = Array.from(body.querySelectorAll("h1,h2,h3,h4,strong,b,[class*='title'],[class*='heading']"))
    .filter((node) => headingLooksUseful(node.textContent));
  if (!headingNodes.length) return [];

  const fullText = cleanVisibleProfileText(body.textContent || "");
  const positioned = headingNodes
    .map((node) => {
      const heading = cleanVisibleProfileText(node.textContent || "");
      return { heading, index: fullText.indexOf(heading) };
    })
    .filter((item) => item.index >= 0)
    .sort((a, b) => a.index - b.index);

  return positioned.map((item, index) => {
    const nextIndex = positioned[index + 1]?.index ?? Math.min(fullText.length, item.index + 900);
    const bodyText = fullText.slice(item.index + item.heading.length, nextIndex).trim();
    return {
      heading: item.heading,
      text: bodyText.slice(0, 760)
    };
  }).filter((section) => section.heading && section.text);
}

function sentenceWindowAround(visibleText, pattern, maxLength = 700) {
  const match = visibleText.match(pattern);
  if (!match || match.index === undefined) return "";
  const start = Math.max(0, match.index - 180);
  return visibleText.slice(start, start + maxLength).replace(/\s+/g, " ").trim();
}

function buildFallbackBosSections(visibleText) {
  return BOS_SECTION_MAPPINGS
    .map((section) => {
      const text = sentenceWindowAround(visibleText, section.pattern);
      return text ? { category: section.title, heading: section.title, text } : null;
    })
    .filter(Boolean);
}

function reliableBosSectionText(text) {
  const cleaned = cleanVisibleProfileText(text).slice(0, 1200);
  if (cleaned.length < 90) return "";
  if (/^(not available|none listed)$/i.test(cleaned)) return "";
  return cleaned;
}

function buildBosSectionTranslatorPayloadsFromRenderedProfile(html, profileId) {
  const visibleText = cleanVisibleProfileText(visibleTextFromHtml(html, 14000));
  const mapped = new Map();

  parseBosHtmlSections(html).forEach((section) => {
    const category = categoryForBosHeading(section.heading);
    const text = reliableBosSectionText(section.text);
    if (!category || !text || mapped.has(category)) return;
    mapped.set(category, {
      category,
      heading: section.heading,
      text
    });
  });

  if (mapped.size < 2) {
    buildFallbackBosSections(visibleText).forEach((section) => {
      const text = reliableBosSectionText(section.text);
      if (!text || mapped.has(section.category)) return;
      mapped.set(section.category, {
        category: section.category,
        heading: section.heading,
        text
      });
    });
  }

  const ordered = [
    ...BOS_SECTION_BUTTON_PRIORITY
      .map((category) => mapped.get(category))
      .filter(Boolean),
    ...Array.from(mapped.values()).filter((section) => !BOS_SECTION_BUTTON_PRIORITY.includes(section.category))
  ];

  return ordered
    .slice(0, 6)
    .map((section) => ({
      category: section.category,
      heading: section.heading,
      buttonLabel: BOS_SECTION_BUTTON_LABELS[section.category] || `Explain ${section.category.toLowerCase()}`,
      source: {
        source_type: "bos_section",
        source_title: section.heading || section.category,
        source_excerpt: [
          `${section.category}:`,
          `Source heading: ${section.heading || section.category}`,
          section.text
        ].join("\n"),
        profile_context: `Retrieved Profile ID: ${profileId || "available"}`
      }
    }));
}

function buildBosTranslatorExcerptFromRenderedProfile(html, profileId) {
  const visibleText = cleanVisibleProfileText(visibleTextFromHtml(html, 14000));
  const htmlSections = parseBosHtmlSections(html);
  const mapped = new Map();

  htmlSections.forEach((section) => {
    const category = categoryForBosHeading(section.heading);
    if (!category || mapped.has(category)) return;
    mapped.set(category, {
      heading: section.heading,
      text: cleanVisibleProfileText(section.text).slice(0, 760)
    });
  });

  if (mapped.size < 3) {
    buildFallbackBosSections(visibleText).forEach((section) => {
      if (!mapped.has(section.category)) {
        mapped.set(section.category, {
          heading: section.heading,
          text: section.text.slice(0, 760)
        });
      }
    });
  }

  const structuredSections = Array.from(mapped.entries()).map(([category, section]) => (
    `${category}:\nSource heading: ${section.heading}\n${section.text}`
  ));

  const fallbackLength = structuredSections.length >= 3 ? 900 : 1800;
  const fallback = visibleText.slice(0, fallbackLength);

  return [
    "BOS section-aware excerpt: true",
    "Profile context:",
    `Retrieved Profile ID: ${profileId || "available"}`,
    "",
    ...structuredSections,
    "",
    "Visible source excerpt fallback:",
    fallback
  ]
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .slice(0, 6000);
}

/**
 * buildApiUrl - Safely join API base URL with endpoint path
 * Handles both absolute URLs (production) and relative paths (local dev with proxy)
 * 
 * Examples:
 * - buildApiUrl('https://example.com', '/api/endpoint') → 'https://example.com/api/endpoint'
 * - buildApiUrl('/', '/api/endpoint') → '/api/endpoint'
 * - buildApiUrl('', '/api/endpoint') → '/api/endpoint'
 */
function buildApiUrl(baseUrl, endpoint) {
  // Handle relative/proxy case: / or empty string
  if (baseUrl === '/' || baseUrl === '' || !baseUrl) {
    // For relative paths, just return the endpoint as-is
    return endpoint.startsWith('/') ? endpoint : `/${endpoint}`
  }
  
  // Handle absolute URL case (production)
  // Remove trailing slash from baseUrl, remove leading slash from endpoint, join with /
  const base = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl
  const path = endpoint.startsWith('/') ? endpoint : `/${endpoint}`
  return `${base}${path}`
}

export default function Profile() {
  const checkoutIdempotencyKey = useMemo(
    () => createCheckoutIdempotencyKey('bos-checkout'),
    [],
  )
  const ownerRouteProfileId = typeof window !== 'undefined'
    ? new URLSearchParams(window.location.search).get('id') || ''
    : ''
  const recruitingRequested = typeof window !== 'undefined'
    && new URLSearchParams(window.location.search).get('recruiting') === '1'
  const [recruitingAuthorized, setRecruitingAuthorized] = useState(false)
  const [publicBosAuthorized, setPublicBosAuthorized] = useState(false)
  const [page0AComplete, setPage0AComplete] = useState(false)
  const [organizationalMetadata, setOrganizationalMetadata] = useState(null)
  const [page0BComplete, setPage0BComplete] = useState(false)
  const [contextualSignals, setContextualSignals] = useState(null)
  const [paymentPassed, setPaymentPassed] = useState(() => Boolean(publicStartToken()))
  const [started, setStarted] = useState(false)
  const [step, setStep] = useState(0)
  const [fullName, setFullName] = useState("")
  const [email, setEmail] = useState("")
  const [submitted, setSubmitted] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [processing, setProcessing] = useState(false)
  const [result, setResult] = useState(null)
  const [selectedOffer, setSelectedOffer] = useState(null)
  const [promoCode, setPromoCode] = useState("")
  const [promoValidated, setPromoValidated] = useState(false)
  const [checkoutLoading, setCheckoutLoading] = useState(false)
  const [checkoutError, setCheckoutError] = useState("")
  const [translatorSource, setTranslatorSource] = useState(null)
  const [savedDraftAvailable, setSavedDraftAvailable] = useState(false)
  const [draftState, setDraftState] = useState({ state: 'idle', message: '' })
  const [generationJourney, setGenerationJourney] = useState({
    mode: 'unknown',
    state: 'idle',
    stage: '',
    message: '',
    jobId: '',
  })
  
  // Profile ID retrieval (recovery/testing path)
  const [profileId, setProfileId] = useState("")
  const [profileIdError, setProfileIdError] = useState(null)
  const [profileIdLoading, setProfileIdLoading] = useState(false)

  // Use the locked 24-question set
  const questions = MOREMINDMAP_QUESTIONS
  const [responses, setResponses] = useState({})
  const draftCoordinator = useMemo(() => createBosDraftCoordinator(), [])
  const submissionGuard = useMemo(() => createBosSubmissionGuard(), [])
  const retrievedBosSectionPayloads = useMemo(() => {
    if (!(result?.success && result?.version === "retrieved" && result?.html)) return [];
    return buildBosSectionTranslatorPayloadsFromRenderedProfile(result.html, result.profile_id);
  }, [result]);

  // Check for payment success query param on mount
  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    if (params.has('payment_success')) {
      console.log('[PAYMENT SUCCESS] Redirect success is pending webhook verification')
      window.history.replaceState({}, document.title, window.location.pathname)
    }
  }, [])

  useEffect(() => {
    const token = publicStartToken()
    if (!token) return
    let cancelled = false
    async function enterPublicBos() {
      try {
        const refreshed = await renewStoredPublicStartToken().catch(() => token)
        const response = await fetch('/api/public-v1/product-start', {
          method: 'POST',
          headers: publicStartHeaders({ 'Content-Type': 'application/json' }),
          credentials: 'same-origin',
          body: JSON.stringify({ start_token: refreshed })
        })
        const payload = await response.json().catch(() => null)
        if (cancelled) return
        const authorized = Boolean(
          response.ok
            && payload?.ok === true
            && payload?.product_key === 'behavior_operating_system'
        )
        setPublicBosAuthorized(authorized)
        setPaymentPassed(authorized)
      } catch {
        if (!cancelled) {
          setPublicBosAuthorized(false)
          setPaymentPassed(false)
        }
      }
    }
    void enterPublicBos()
    return () => {
      cancelled = true
    }
  }, [])

  useEffect(() => {
    if (!recruitingRequested) return
    let cancelled = false
    fetch('/api/recruiting/runtime?view=invite_session', {
      credentials: 'same-origin',
      cache: 'no-store'
    }).then(async (response) => {
      const payload = await response.json().catch(() => null)
      if (cancelled) return
      if (!response.ok || payload?.ok !== true || !payload?.relationship?.relationship_ref) {
        throw new Error('Your recruiting invitation session is unavailable. Return to the invitation link and accept again.')
      }
      const progressState = payload?.continuation?.progress_state
      const bosLanding = ['INVITED', 'BOS_IN_PROGRESS'].includes(progressState)
        ? resolveRecruitingBosLanding(payload.continuation)
        : null
      setRecruitingAuthorized(true)
      setPaymentPassed(true)
      if (bosLanding?.mode === 'RESUME_BOUND_BOS') {
        void resumeRecruitingBoundBos({
          continuation: payload.continuation,
          pollBoundJob: (jobId) => cancelled
            ? undefined
            : resumeExistingGeneration(jobId, {
                recruiting: true,
                isCancelled: () => cancelled,
              }),
        }).catch(() => {
          if (cancelled) return
          setProcessing(false)
          setSubmitted(true)
          setResult({
            success: false,
            code: 'BOS_GENERATION_RESUME_UNAVAILABLE',
            error: 'We could not reopen the saved generation job. Return to your private continuation and try again; your assessment was not submitted again.',
            retryable: false,
          })
        })
      }
    }).catch((error) => {
      if (!cancelled) setCheckoutError(error.message)
    })
    return () => {
      cancelled = true
    }
    // The accepted-invitation bootstrap runs once for this route request. Re-running
    // when the local resume callback is recreated would poll the same job twice.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [recruitingRequested])

  useEffect(() => {
    setSavedDraftAvailable(draftCoordinator.hasLocalDraft())
  }, [draftCoordinator])

  const progress = Math.round(((step + 1) / questions.length) * 100)
  const currentAnswer = responses[questions[step].id] || null

  function currentDraftMetadata({
    organizational = organizationalMetadata,
    signals = contextualSignals,
    personName = fullName,
    personEmail = email
  } = {}) {
    return {
      person_name: personName.trim() || null,
      email: personEmail.trim() || null,
      ...(organizational || {}),
      contextual_signals: signals || {},
      access_path: 'CURRENT_BOS_ENTRY',
      recruiting_mode: recruitingAuthorized ? 'accepted_invitation' : undefined
    }
  }

  async function persistDraft({
    phase,
    nextStep = step,
    nextResponses = responses,
    metadata = currentDraftMetadata()
  }) {
    const snapshot = createBosDraftSnapshot({
      phase,
      step: nextStep,
      metadata,
      responses: nextResponses
    })
    setDraftState({ state: 'saving', message: 'Saving your progress…' })
    try {
      const envelope = await draftCoordinator.save(snapshot)
      setSavedDraftAvailable(false)
      setDraftState({ state: 'saved', message: 'Progress saved.' })
      return envelope
    } catch (error) {
      if (error?.code === 'BOS_DRAFT_STALE_REVISION' && error?.restored?.ok) {
        applyRestoredDraft(error.restored.envelope)
        setDraftState({ state: 'restored', message: 'A newer saved version was restored. Review it before continuing.' })
      } else if (error?.code === 'BOS_DRAFT_LOCAL_PERSISTENCE_UNAVAILABLE') {
        setDraftState({ state: 'error', message: 'This browser could not keep a secure resume key. Progress is not safe to continue; enable site storage and try again.' })
      } else {
        setDraftState({ state: 'error', message: 'We could not sync your progress. Your latest answers remain on this device; try again before submitting.' })
      }
      return null
    }
  }

  function applyRestoredDraft(envelope) {
    const snapshot = envelope?.snapshot || {}
    const metadata = snapshot.metadata || {}
    const organizational = {
      identity: metadata.identity || {
        full_name: metadata.person_name || '',
        email: metadata.email || ''
      },
      organization: metadata.organization || {}
    }
    setFullName(metadata.person_name || metadata.identity?.full_name || '')
    setEmail(metadata.email || metadata.identity?.email || '')
    setOrganizationalMetadata(organizational)
    setContextualSignals(metadata.contextual_signals || {})
    setResponses(snapshot.responses || {})
    setStep(Number.isInteger(snapshot.step) ? snapshot.step : 0)
    setPaymentPassed(true)
    setPromoValidated(true)
    setSelectedOffer('full_profile')
    setPage0AComplete(true)
    const assessmentStarted = ['ASSESSMENT', 'READY_TO_SUBMIT'].includes(snapshot.phase)
    setPage0BComplete(assessmentStarted)
    setStarted(assessmentStarted)
  }

  async function resumeSavedAssessment() {
    setDraftState({ state: 'restoring', message: 'Restoring your saved assessment…' })
    const restored = await draftCoordinator.restore()
    if (restored.ok) {
      applyRestoredDraft(restored.envelope)
      setSavedDraftAvailable(false)
      setDraftState({ state: 'restored', message: 'Your saved assessment was restored.' })
      return
    }
    if (restored.code === 'BOS_DRAFT_NOT_FOUND' && restored.local?.snapshot) {
      draftCoordinator.clear()
      const recovered = await draftCoordinator.save(restored.local.snapshot).catch(() => null)
      if (recovered) {
        applyRestoredDraft(recovered)
        setSavedDraftAvailable(false)
        setDraftState({ state: 'restored', message: 'Your device copy was recovered and saved again.' })
        return
      }
    }
    setDraftState({ state: 'error', message: 'Your saved assessment could not be restored right now. Please try again.' })
  }

  async function discardSavedAssessment() {
    await draftCoordinator.discard().catch(() => draftCoordinator.clear())
    setSavedDraftAvailable(false)
    setDraftState({ state: 'idle', message: '' })
  }

  function selectAnswer(questionId, key) {
    const nextResponses = { ...responses, [questionId]: key }
    setResponses(nextResponses)
    void persistDraft({ phase: 'ASSESSMENT', nextResponses })
  }

  function validatePromoCode() {
    const code = promoCode.trim().toUpperCase()
    if (BEHAVIOR_PROFILE_PROMO_CODES.has(code)) {
      console.log("[PROMO VALIDATION] Behavior Profile promo code accepted")
      setPromoValidated(true)
      setPaymentPassed(true)
      setSelectedOffer("full_profile")
    } else {
      console.log("[PROMO VALIDATION] Invalid code:", code)
    }
  }

  async function validateProfileId(requestedId = profileId) {
    setProfileIdError(null)
    const id = String(requestedId || '').trim()
    
    if (!id) {
      setProfileIdError("Please enter a profile ID")
      return
    }
    
    const profileIdPattern = /^MM-\d{8}-[a-z0-9]{6,12}$/i
    if (!profileIdPattern.test(id)) {
      setProfileIdError("Please enter a valid Profile ID.")
      return
    }
    
    setProfileIdLoading(true)
    try {
      const fullUrl =
        `/api/moremindmap/retrieve-profile?id=${encodeURIComponent(id)}`
      console.log('[VALIDATE] Full URL:', fullUrl)
      const res = await fetch(fullUrl, { headers: publicStartHeaders(), credentials: 'same-origin', cache: 'no-store' })
      console.log('[VALIDATE] Response status:', res.status)
      console.log('[VALIDATE] Response ok?', res.ok)
      
      if (!res.ok) {
        console.log('[VALIDATE] Response NOT ok')
        console.log('[VALIDATE] Response status:', res.status)
        if (res.status === 404) {
          console.log('[VALIDATE] 404 not found')
          setProfileIdError("We couldn't find that profile. Please check the ID and try again.")
        } else {
          try {
            const error = await res.json()
            console.log('[VALIDATE] Error response:', error)
            setProfileIdError(error.error || "Failed to retrieve profile")
          } catch (e) {
            console.log('[VALIDATE] Could not parse error JSON:', e.message)
            setProfileIdError("Failed to retrieve profile")
          }
        }
        setProfileIdLoading(false)
        return
      }
      
      const data = await res.json()
      console.log("[PROFILE RETRIEVED]", data.profile_id)
      
      if (!data.canonical_dossier) {
        setProfileIdError("Invalid profile data")
        setProfileIdLoading(false)
        return
      }

      const currentBos = await resolveOrdinaryBosEntry(data.profile_id || id)
      if (currentBos.status === 'current') {
        window.location.assign(currentBos.destination)
        return
      }
      if (currentBos.status !== 'governed_fallback') {
        setProfileIdError(ORDINARY_CUSTOMER_ENTRY_UNAVAILABLE_MESSAGE)
        return
      }
      
      // A governed incompatibility may still use the supported legacy BOS fallback.
      setResult({
        success: true,
        version: "web",
        canonical_dossier: data.canonical_dossier,
        behavioral_intelligence_v1: data.behavioral_intelligence_v1,
        visual_dna: data.visual_dna,
        profile_id: data.profile_id,
        retrieved_at: data.retrieved_at
      })
      
      setSubmitted(true)
      setProcessing(false)
    } catch (error) {
      console.error("[VALIDATE] EXCEPTION:", error)
      console.log('[VALIDATE] Error message:', error.message)
      console.log('[VALIDATE] Error type:', error.name)
      setProfileIdError("Failed to retrieve profile. Please try again.")
    } finally {
      setProfileIdLoading(false)
    }
  }

  useEffect(() => {
    if (!ownerRouteProfileId) return
    setProfileId(ownerRouteProfileId)
    void validateProfileId(ownerRouteProfileId)
    // Exact owner-receipt route bootstrap intentionally runs once on mount.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  async function handleStartAssessment() {
    // If promo is active, skip checkout and enter Page 0A
    if (promoValidated) {
      console.log("[PROMO PATH] Promo validated, entering Page 0A")
      // Page 0A will show because page0AComplete is false
      // User must complete Page 0A before assessment starts
      return
    }

    // Otherwise, redirect to Stripe checkout
    if (!selectedOffer) {
      console.log("[ERROR] No selectedOffer but button was enabled?")
      return
    }

    console.log("[CHECKOUT PATH] Redirecting to Stripe with offer:", selectedOffer)
    setCheckoutLoading(true)
    setCheckoutError("")
    try {
      await startStripeCheckout({
        product_key: "behavior_operating_system",
        email: email.trim(),
        source_context: "behavior_operating_system_profile"
      }, { idempotencyKey: checkoutIdempotencyKey })
    } catch {
      setCheckoutError("Payment setup is not available yet. Please try again shortly.")
      setCheckoutLoading(false)
    }
  }

  function goNext() {
    console.log("BUTTON CLICKED — goNext() called")
    console.log("STEP:", step)
    console.log("TOTAL QUESTIONS:", questions.length)
    if (!currentAnswer) {
      console.log("BLOCKED: currentAnswer is falsy")
      return
    }
    
    if (step < questions.length - 1) {
      console.log("NOT FINAL STEP — advancing to next question")
      const nextStep = step + 1
      setStep(nextStep)
      void persistDraft({ phase: 'ASSESSMENT', nextStep })
    } else {
      console.log("FINAL STEP — CALLING submitAssessment()")
      submitAssessment()
    }
  }

  function goBack() {
    if (step > 0) {
      const nextStep = step - 1
      setStep(nextStep)
      void persistDraft({ phase: 'ASSESSMENT', nextStep })
    }
  }

  function discardCompletedBosDraft() {
    const discardRequest = draftCoordinator.discard()
    draftCoordinator.clear()
    setSavedDraftAvailable(false)
    void discardRequest.catch(() => {})
  }

  function settleOpenedBos(nextResult, jobId) {
    setResult(nextResult)
    setProcessing(false)
    setGenerationJourney({
      mode: 'async',
      state: 'ready',
      stage: 'complete',
      message: 'Your Behavioral Operating System is ready.',
      jobId,
    })
    discardCompletedBosDraft()
  }

  async function openCompletedBos(statusData, jobId, API, {
    recruiting = recruitingAuthorized,
    isCancelled = () => false,
  } = {}) {
    if (isCancelled()) return
    const canonicalProfileId = normalizeBosCanonicalProfileId(statusData?.canonical_profile_id)
    if (!canonicalProfileId) {
      setProcessing(false)
      setResult({
        success: false,
        code: 'BOS_COMPLETED_PROFILE_UNAVAILABLE',
        error: 'We could not verify the completed profile reference. Your answers are saved; check the same generation job again.',
        retryable: true,
        job_id: jobId,
      })
      return
    }

    console.log("[MINI-V2] Generation complete!")
    setProfileId(canonicalProfileId)
    setProfileIdLoading(true)
    setGenerationJourney({
      mode: 'async',
      state: 'opening',
      stage: 'complete',
      message: 'Your BOS is complete. Opening the saved profile.',
      jobId,
    })

    try {
      const fullUrl = buildApiUrl(API, `/api/moremindmap/retrieve-profile?id=${encodeURIComponent(canonicalProfileId)}`)
      const data = await runBosGenerationRequest({
        request: async ({ signal }) => {
          const res = await fetch(fullUrl, {
            headers: publicStartHeaders(),
            credentials: recruiting ? 'same-origin' : 'omit',
            signal,
          })
          if (!res.ok) throw new Error(`Failed to fetch profile: ${res.status}`)
          return res.json()
        },
      })
      if (isCancelled()) return
      const retrievedProfileId = normalizeBosCanonicalProfileId(data?.profile_id)
      const hasCanonicalDossier = data?.canonical_dossier
        && typeof data.canonical_dossier === 'object'
        && !Array.isArray(data.canonical_dossier)
      if (data?.success !== true || retrievedProfileId !== canonicalProfileId || !hasCanonicalDossier) {
        throw new Error('Completed profile retrieval returned an invalid contract')
      }

      settleOpenedBos({
        success: true,
        version: "web",
        canonical_dossier: data.canonical_dossier,
        behavioral_intelligence_v1: data.behavioral_intelligence_v1,
        visual_dna: data.visual_dna,
        profile_id: canonicalProfileId,
        retrieved_at: data.retrieved_at
      }, jobId)
    } catch (error) {
      if (isCancelled()) return
      if (hasUsableBosCompletedHtml(statusData)) {
        console.error("[MINI-V2-ROUTE] Governed retrieval unavailable; using completed job payload:", error.message)
        settleOpenedBos({
          success: true,
          version: "mini-v2",
          html: statusData.html,
          snapshot: statusData.metadata,
          profile_id: canonicalProfileId
        }, jobId)
      } else {
        console.error("[MINI-V2-ROUTE] Completed profile could not be opened:", error.message)
        setProcessing(false)
        setGenerationJourney({
          mode: 'async',
          state: 'status_unavailable',
          stage: 'complete',
          message: 'Your BOS completed, but the saved profile could not be opened yet.',
          jobId,
        })
        setResult({
          success: false,
          code: 'BOS_COMPLETED_PROFILE_UNAVAILABLE',
          error: 'Your BOS finished, but we could not safely open the completed profile. Your answers are saved; check the same generation job again.',
          retryable: true,
          job_id: jobId,
        })
      }
    } finally {
      if (!isCancelled()) setProfileIdLoading(false)
    }
  }

  async function pollExistingBosJob(jobId, API, {
    recruiting = recruitingAuthorized,
    isCancelled = () => false,
  } = {}) {
    if (isCancelled()) return
    setGenerationJourney({
      mode: 'async',
      state: 'pending',
      stage: 'queued',
      message: 'Checking your saved BOS generation job.',
      jobId,
    })

    const generationOutcome = await pollBosGenerationJob({
      readStatus: async ({ signal } = {}) => {
        const statusRes = await fetch(buildApiUrl(API, `/api/moremindmap/status?job_id=${jobId}`), {
          headers: publicStartHeaders(),
          credentials: recruiting ? 'same-origin' : 'omit',
          signal,
        })
        const payload = await statusRes.json().catch(() => null)
        return { ok: statusRes.ok, statusCode: statusRes.status, payload }
      },
      onProgress: (status) => {
        if (isCancelled()) return
        console.log('[MINI-V2] Status:', status.stage)
        setGenerationJourney({
          mode: 'async',
          state: 'pending',
          stage: status.stage,
          message: status.message,
          jobId,
        })
      },
      shouldContinue: () => !isCancelled(),
    })

    if (isCancelled() || generationOutcome.state === 'cancelled') return

    if (generationOutcome.state === 'complete') {
      await openCompletedBos(generationOutcome.payload, jobId, API, { recruiting, isCancelled })
      return
    }

    if (generationOutcome.state === 'failed') {
      const terminalFailureMessage = 'Generation stopped before your BOS was ready. Your answers remain saved. This generation job is final, so checking its status again will not restart it.'
      setProcessing(false)
      setGenerationJourney({
        mode: 'async',
        state: 'failed',
        stage: 'failed',
        message: terminalFailureMessage,
        jobId,
      })
      setResult({
        success: false,
        code: 'BOS_GENERATION_FAILED',
        error: terminalFailureMessage,
        retryable: false,
        job_id: jobId,
      })
      return
    }

    const statusUnavailable = generationOutcome.state === 'status_unavailable'
    setProcessing(false)
    setGenerationJourney({
      mode: 'async',
      state: generationOutcome.state,
      stage: generationOutcome.state,
      message: statusUnavailable
        ? 'We could not confirm the current job status after several checks.'
        : 'Your saved generation job is taking longer than the expected window.',
      jobId,
    })
    setResult({
      success: false,
      code: statusUnavailable ? 'BOS_GENERATION_STATUS_UNAVAILABLE' : 'BOS_GENERATION_SLOW',
      error: statusUnavailable
        ? 'We could not confirm the current status. Your answers are saved; check the same generation job again.'
        : 'Your BOS is taking longer than expected. Your answers are saved; check the same generation job again.',
      retryable: true,
      job_id: jobId,
    })
  }

  async function resumeExistingGeneration(jobId, {
    recruiting = recruitingAuthorized,
    isCancelled = () => false,
  } = {}) {
    if (!jobId || isCancelled() || !submissionGuard.tryStart()) return

    setSubmitting(true)
    setProcessing(true)
    setSubmitted(false)
    setResult(null)
    try {
      const API = import.meta.env.VITE_API_URL || ""
      if (publicBosAuthorized) await renewStoredPublicStartToken()
      if (isCancelled()) return
      await pollExistingBosJob(jobId, API, { recruiting, isCancelled })
    } catch {
      if (isCancelled()) return
      setProcessing(false)
      setResult({
        success: false,
        code: 'BOS_GENERATION_STATUS_UNAVAILABLE',
        error: 'We could not confirm the current status. Your answers are saved; check the same generation job again.',
        retryable: true,
        job_id: jobId,
      })
    } finally {
      if (!isCancelled()) {
        setSubmitting(false)
        setSubmitted(true)
      }
      submissionGuard.finish()
    }
  }

  function retryBosGenerationStart() {
    return submitAssessment({ reuseSavedSubmission: true })
  }

  async function submitAssessment({ reuseSavedSubmission = false } = {}) {
    if (!submissionGuard.tryStart()) return

    console.log("SUBMIT FUNCTION TRIGGERED")
    setSubmitting(true)
    setProcessing(true)
    setSubmitted(false)
    setResult(null)
    setGenerationJourney({
      mode: 'unknown',
      state: reuseSavedSubmission ? 'starting' : 'securing_answers',
      stage: reuseSavedSubmission ? 'starting' : 'saving',
      message: reuseSavedSubmission
        ? 'Safely retrying generation from your saved answers.'
        : 'Securely saving your final answers.',
      jobId: '',
    })
    const savedSubmissionEnvelope = reuseSavedSubmission ? draftCoordinator.localEnvelope() : null
    let shouldShowCompletion = true
    let answersSaved = savedSubmissionEnvelope?.snapshot?.phase === 'READY_TO_SUBMIT'
    let activeJobId = ''
    
    try {
      if (publicBosAuthorized) await renewStoredPublicStartToken()
      // Transform responses to new format: { questionId: answer }
      const answers = {}
      questions.forEach((q) => {
        answers[q.id] = responses[q.id] || null
      })

      const metadata = currentDraftMetadata()
      const draftEnvelope = reuseSavedSubmission
        ? savedSubmissionEnvelope
        : await persistDraft({
            phase: 'READY_TO_SUBMIT',
            nextStep: questions.length - 1,
            nextResponses: answers,
            metadata
          })
      if (!reuseSavedSubmission) await draftCoordinator.flush()
      if (!draftEnvelope) {
        setProcessing(false)
        shouldShowCompletion = false
        return
      }
      if (draftEnvelope.snapshot?.phase !== 'READY_TO_SUBMIT') {
        setProcessing(false)
        return setResult({
          success: false,
          code: 'BOS_GENERATION_SAVED_SUBMISSION_UNAVAILABLE',
          error: 'The saved final answers needed for this recovery are unavailable. Return to the assessment before trying again.',
          retryable: false,
        })
      }
      answersSaved = true
      const submissionAnswers = draftEnvelope.snapshot.responses
      const submissionMetadata = draftEnvelope.snapshot.metadata

      // Current production BOS API is same-origin. A stale legacy backend host
      // previously accepted preflight and returned 404 on the final POST.
      const API = import.meta.env.VITE_API_URL || ""
      
      // CONTROLLED BETA: Route validated Behavior Profile promo users to Mini V2 async endpoint
      const useV2 = recruitingAuthorized
        || publicBosAuthorized
        || (promoValidated && BEHAVIOR_PROFILE_PROMO_CODES.has(promoCode.trim().toUpperCase()))
      
      console.log("[SUBMIT] Using Mini V2:", useV2)

      if (useV2) {
        // ASYNC JOB FLOW for Mini V2
        console.log("[MINI-V2] Starting async job flow")
        setGenerationJourney({
          mode: 'async',
          state: 'starting',
          stage: 'starting',
          message: 'Starting your saved BOS generation job.',
          jobId: '',
        })
        
        // Step 1: Start job
        const { response: startRes, payload: startData } = await runBosGenerationRequest({
          request: async ({ signal }) => {
            const response = await fetch(buildApiUrl(API, `/api/moremindmap/start`), {
              method: "POST",
              headers: publicStartHeaders({
                "Content-Type": "application/json",
                "X-BOS-Draft-Token": draftEnvelope.resume_token
              }),
              body: JSON.stringify({
                answers: submissionAnswers,
                metadata: submissionMetadata,
                draft_reference: {
                  contract_version: 'bos_intake_draft_v1',
                  draft_id: draftEnvelope.draft_id,
                  revision: draftEnvelope.revision,
                  snapshot: draftEnvelope.snapshot
                }
              }),
              credentials: recruitingAuthorized ? 'same-origin' : 'omit',
              signal,
            })
            const payload = response.ok ? await response.json().catch(() => null) : null
            return { response, payload }
          },
        })
        
        if (!startRes.ok) {
          console.error("[MINI-V2] Start failed:", startRes.status)
          setProcessing(false)
          return setResult({
            success: false,
            error: 'We could not confirm generation started. Your answers are saved; try generation again.',
            retryable: true,
            code: 'BOS_GENERATION_START_FAILED',
          })
        }
        
        const jobId = String(startData?.job_id || '').trim()
        if (!jobId) throw new Error('Generation started without a recoverable job reference.')
        activeJobId = jobId
        console.log("[MINI-V2] Job started:", jobId)
        await pollExistingBosJob(jobId, API)
      } else {
        // Synchronous legacy flow for callers outside the governed async path.
        console.log("[MINI-V1] Using synchronous endpoint")
        setGenerationJourney({
          mode: 'sync',
          state: 'pending',
          stage: 'generating',
          message: 'Your completed answers are being analyzed.',
          jobId: '',
        })
        const endpoint = `${API}/api/moremindmap/mini-profile`
        
        const res = await fetch(endpoint, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            answers,
            metadata: {
              person_name: fullName.trim() || null,
              email: email.trim() || null,
              ...organizationalMetadata,
              contextual_signals: contextualSignals
            }
          }),
        })

        if (!res.ok) {
          const text = await res.text()
          console.error("[RESPONSE] Error text:", text)
          setProcessing(false)
          return setResult({
            success: false,
            error: `Server error (${res.status}): ${text}`,
          })
        }

        const data = await res.json()
        // Show processing screen for 2 seconds before displaying report
        setTimeout(() => {
          setProcessing(false)
          setResult(data)
          setGenerationJourney({
            mode: 'sync',
            state: 'ready',
            stage: 'complete',
            message: 'Your Behavioral Operating System is ready.',
            jobId: '',
          })
        }, 2000)
      }
    } catch (error) {
      console.error("[SUBMIT] Assessment submission error:", error)
      console.error("[SUBMIT] Error stack:", error.stack)
      setProcessing(false)
      if (activeJobId) {
        setResult({
          success: false,
          code: 'BOS_GENERATION_STATUS_UNAVAILABLE',
          error: 'We could not confirm the current status. Your answers are saved; check the same generation job again.',
          retryable: true,
          job_id: activeJobId,
        })
      } else if (answersSaved) {
        setResult({
          success: false,
          code: 'BOS_GENERATION_START_UNAVAILABLE',
          error: 'We could not confirm generation started. Your answers are saved; try generation again.',
          retryable: true,
        })
      } else {
        setResult({
          success: false,
          error: 'We could not prepare your saved answers for generation. Return to the assessment and try again.',
          retryable: false,
        })
      }
    } finally {
      setSubmitting(false)
      setSubmitted(shouldShowCompletion)
      submissionGuard.finish()
    }
  }

  const handlePage0AComplete = async (metadata) => {
    const personName = metadata.identity.full_name
    const personEmail = metadata.identity.email
    const saved = await persistDraft({
      phase: 'CONTEXTUAL_SIGNALS',
      nextStep: 0,
      nextResponses: {},
      metadata: currentDraftMetadata({
        organizational: metadata,
        signals: {},
        personName,
        personEmail
      })
    })
    if (!saved) return
    setOrganizationalMetadata(metadata)
    setFullName(personName)
    setEmail(personEmail)
    setPage0AComplete(true)
  }

  const handlePage0BComplete = async (signals) => {
    const saved = await persistDraft({
      phase: 'ASSESSMENT',
      nextStep: 0,
      nextResponses: {},
      metadata: currentDraftMetadata({ signals })
    })
    if (!saved) return
    setContextualSignals(signals)
    setPage0BComplete(true)
  }

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      <ProfileBackground />

      <div className="relative z-10 px-6 py-16 md:py-20">
        <div className="max-w-4xl mx-auto">

          {draftState.message && !submitted && (
            <div
              role="status"
              className={`mb-5 rounded-2xl border px-5 py-3 text-sm ${
                draftState.state === 'error'
                  ? 'border-red-400/30 bg-red-500/10 text-red-100'
                  : 'border-emerald-300/20 bg-emerald-400/[0.08] text-emerald-100'
              }`}
            >
              {draftState.message}
            </div>
          )}

          {/* INTRO SCREEN (Payment Page) — Shows FIRST, before payment */}
          {!paymentPassed && !promoValidated && !submitted && (
            <IntroScreen
              fullName={fullName}
              setFullName={setFullName}
              email={email}
              setEmail={setEmail}
              selectedOffer={selectedOffer}
              setSelectedOffer={setSelectedOffer}
              promoCode={promoCode}
              setPromoCode={setPromoCode}
              promoValidated={promoValidated}
              validatePromoCode={validatePromoCode}
              profileId={profileId}
              setProfileId={setProfileId}
              profileIdError={profileIdError}
              profileIdLoading={profileIdLoading}
              validateProfileId={() => validateProfileId()}
              onStart={handleStartAssessment}
              checkoutLoading={checkoutLoading}
              checkoutError={checkoutError}
              savedDraftAvailable={savedDraftAvailable}
              onResumeSavedAssessment={resumeSavedAssessment}
              onDiscardSavedAssessment={discardSavedAssessment}
            />
          )}

          {/* PAGE 0A: ORGANIZATIONAL CONTEXT — Shows AFTER payment or promo validation */}
          {(paymentPassed || promoValidated) && !page0AComplete && !submitted && (
            <Page0A_OrganizationalContext onComplete={handlePage0AComplete} />
          )}

          {/* PAGE 0B: CONTEXTUAL SIGNALS — Shows AFTER Page 0A complete */}
          {page0AComplete && !page0BComplete && !submitted && (
            <Page0B_ContextualSignals onComplete={handlePage0BComplete} />
          )}

          {/* START BUTTON — After Page 0B complete, before questions */}
          {page0BComplete && !started && !submitted && (
            <div className="max-w-2xl mx-auto space-y-8">
              <div className="rounded-[2rem] border border-white/10 bg-white/5 backdrop-blur-md p-8 md:p-10 shadow-2xl shadow-black/30 text-center">
                <h1 className="text-3xl md:text-4xl font-semibold tracking-tight">
                  Ready to begin.
                </h1>
                <p className="mt-4 text-white/72 text-lg">
                  You've completed the context layer. Let's dive into your behavioral assessment.
                </p>
                <button
                  onClick={() => setStarted(true)}
                  className="mt-8 inline-flex items-center justify-center rounded-2xl bg-white text-black px-8 py-4 text-base font-medium hover:bg-white/90 transition shadow-[0_0_40px_rgba(255,255,255,0.1)]"
                >
                  Start Assessment
                </button>
              </div>
            </div>
          )}

          {/* QUESTION FLOW */}
          {started && !submitted && !submitting && (
            <QuestionScreen
              step={step}
              total={questions.length}
              progress={progress}
              question={questions[step]}
              selectedKey={currentAnswer}
              onSelect={(key) => selectAnswer(questions[step].id, key)}
              onNext={goNext}
              onBack={goBack}
              isFirst={step === 0}
              isLast={step === questions.length - 1}
            />
          )}

          {/* SUBMITTING */}
          {submitting && (
            <BosGenerationWaitingScreen journey={generationJourney} />
          )}

          {/* COMPLETION */}
          {submitted && (
            <div className="space-y-8">
              <a
                href="/"
                className="inline-flex items-center text-sm text-white/60 hover:text-white transition"
              >
                ← Back to Home
              </a>

              {/* PROCESSING SCREEN */}
              {processing && (
                <BosGenerationWaitingScreen journey={generationJourney} />
              )}

              {!processing && result?.success && result?.profile_id && (
                <ProfileIdentityCustody
                  profileId={result.profile_id}
                  offerRecruitingContinuation={recruitingAuthorized}
                />
              )}

              {/* MINI V2: 10-PAGE HTML REPORT (CONTROLLED BETA) */}
              {!processing && result?.success && result?.version === "mini-v2" && result?.html && (
                <>
                  <div className="bg-white rounded-[2rem] shadow-2xl overflow-hidden">
                    <div className="p-4 md:p-6 bg-gradient-to-r from-blue-600 to-purple-600 text-white">
                      <div className="text-xs uppercase tracking-wider opacity-90">Mini Profile V2 Beta</div>
                      <div className="text-sm mt-1">10-Page Behavioral Profile Report</div>
                    </div>
                    <div 
                      className="mini-v2-report-container"
                      dangerouslySetInnerHTML={{ __html: result.html }}
                    />
                  </div>
                  <a
                    href="/"
                    className="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-white/5 px-6 py-4 text-base font-medium text-white hover:bg-white/10 transition"
                  >
                    ← Back to Home
                  </a>
                </>
              )}

              {/* RETRIEVED: PROFILE REGENERATION FROM VAULT */}
              {!processing && result?.success && result?.version === "retrieved" && result?.html && (
                <>
                  <div className="bg-white rounded-[2rem] shadow-2xl overflow-hidden">
                    <div className="p-4 md:p-6 bg-gradient-to-r from-amber-600 to-orange-600 text-white">
                      <div className="text-xs uppercase tracking-wider opacity-90">Profile Report</div>
                      <div className="text-sm mt-1">Regenerated from Profile ID: {result.profile_id}</div>
                      <button
                        type="button"
                        onClick={() => setTranslatorSource({
                          source_type: "bos_profile",
                          source_title: "Behavior Operating System Profile",
                          source_excerpt: buildBosTranslatorExcerptFromRenderedProfile(result.html, result.profile_id),
                          profile_context: `Retrieved Profile ID: ${result.profile_id || "available"}`
                        })}
                        className="mt-4 rounded-full border border-white/35 bg-white/15 px-4 py-2 text-xs font-bold uppercase tracking-[0.16em] text-white transition hover:border-white hover:bg-white/22"
                      >
                        Explain This Profile
                      </button>
                      {retrievedBosSectionPayloads.length >= 2 && (
                        <div className="mt-4 max-w-3xl rounded-2xl border border-white/18 bg-black/10 p-3">
                          <p className="text-[0.68rem] font-semibold uppercase tracking-[0.22em] text-white/72">
                            Explain specific parts
                          </p>
                          <div className="mt-3 flex flex-wrap gap-2">
                            {retrievedBosSectionPayloads.map((section) => (
                              <button
                                key={`${section.category}-${section.heading}`}
                                type="button"
                                onClick={() => setTranslatorSource(section.source)}
                                className="rounded-full border border-white/24 bg-white/10 px-3 py-2 text-[0.68rem] font-bold uppercase tracking-[0.13em] text-white transition hover:border-white/70 hover:bg-white/18"
                              >
                                {section.buttonLabel}
                              </button>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                    <div 
                      className="mini-v2-report-container"
                      dangerouslySetInnerHTML={{ __html: result.html }}
                    />
                  </div>
                  <a
                    href="/"
                    className="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-white/5 px-6 py-4 text-base font-medium text-white hover:bg-white/10 transition"
                  >
                    ← Back to Home
                  </a>
                </>
              )}

              <UniversalTranslatorDrawer
                isOpen={Boolean(translatorSource)}
                onClose={() => setTranslatorSource(null)}
                source={translatorSource}
              />

              {/* WEB-FIRST: PREMIUM PROFILE REPORT */}
              {!processing && result?.success && result?.version === "web" && result?.canonical_dossier && (
                <>
                  <WebProfileReport 
                    canonical={result.canonical_dossier}
                    profileId={result.profile_id}
                    behavioralIntelligence={result.behavioral_intelligence_v1}
                    visualDNA={result.visual_dna}
                  />
                  <a
                    href="/"
                    className="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-white/5 px-6 py-4 text-base font-medium text-white hover:bg-white/10 transition mt-6"
                  >
                    ← Back to Home
                  </a>
                </>
              )}

                            {/* NEW: 5-PAGE MINI PROFILE REPORT (OLD VERSION) */}
              {!processing && result?.success && result?.miniProfile && !result?.version && (
                <>
                  <div className="bg-white text-black rounded-[2rem] shadow-2xl overflow-hidden">
                    <MiniProfileReport 
                      scoringPayload={result?.scoringPayload || {}}
                      miniProfile={result?.miniProfile || {}}
                      userName={fullName}
                    />
                  </div>
                  <a
                    href="/"
                    className="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-white/5 px-6 py-4 text-base font-medium text-white hover:bg-white/10 transition"
                  >
                    ← Back to Home
                  </a>
                </>
              )}

              {/* ERROR RESULT */}
              {result && !result.success && (
                <div className="rounded-[2rem] border border-white/10 bg-white/5 backdrop-blur-md p-8 md:p-10 shadow-2xl shadow-black/30">
                  <div className="inline-flex items-center rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs uppercase tracking-[0.22em] text-white/60">
                    Error
                  </div>

                  <h1 className="mt-6 text-3xl md:text-4xl font-semibold tracking-tight">
                    Something went wrong.
                  </h1>

                  <p className="mt-6 text-lg text-white/72 leading-relaxed">
                    {result.error || "An unexpected error occurred. Please try again."}
                  </p>

                  {result.retryable && (
                    <button
                      type="button"
                      onClick={() => result.job_id
                        ? resumeExistingGeneration(result.job_id)
                        : retryBosGenerationStart()}
                      className="mt-7 inline-flex items-center justify-center rounded-2xl bg-white px-6 py-4 text-base font-semibold text-black transition hover:bg-white/90"
                      data-testid="bos-generation-check-again"
                    >
                      {result.job_id ? 'Check the same generation job' : 'Try generation again'}
                    </button>
                  )}

                  {result.retryable && (
                    <p className="mt-4 text-sm leading-relaxed text-white/50">
                      {result.job_id
                        ? 'This checks the same saved generation job. It does not submit another assessment.'
                        : 'This uses the same saved assessment to try generation again. It does not submit a second assessment.'}
                    </p>
                  )}

                  <a
                    href="/"
                    className="inline-flex items-center justify-center rounded-2xl border border-white/15 bg-white/5 px-6 py-4 text-base font-medium text-white hover:bg-white/10 transition mt-6"
                  >
                    ← Back to Home
                  </a>
                </div>
              )}
            </div>
          )}

        </div>
      </div>
    </div>
  )
}

/* ── Intro Screen ── */

function IntroScreen({ fullName, setFullName, email, setEmail, selectedOffer, setSelectedOffer, promoCode, setPromoCode, promoValidated, validatePromoCode, profileId, setProfileId, profileIdError, profileIdLoading, validateProfileId, onStart, checkoutLoading, checkoutError, savedDraftAvailable, onResumeSavedAssessment, onDiscardSavedAssessment }) {
  const featureList = [
    "24 scenario-based questions",
    "Behavior Operating System profile",
    "Primary and secondary patterns",
    "Strengths and blind spots",
    "Pressure response",
    "Communication and decision style",
    "Profile DNA",
    "Five Futures",
    "One Move",
    "Universal Translator"
  ];

  return (
    <div className="mx-auto max-w-6xl">
      <a
        href="/"
        className="inline-flex items-center text-sm text-white/52 transition hover:text-white"
      >
        ← Back to Home
      </a>

      {savedDraftAvailable && (
        <div className="mt-6 rounded-2xl border border-emerald-300/25 bg-emerald-400/[0.08] p-5 sm:flex sm:items-center sm:justify-between sm:gap-5">
          <div>
            <p className="font-semibold text-white">Saved assessment found on this device.</p>
            <p className="mt-1 text-sm text-white/62">Resume from the last durable question boundary or clear it and start over.</p>
          </div>
          <div className="mt-4 flex gap-3 sm:mt-0">
            <button type="button" onClick={onResumeSavedAssessment} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black">
              Resume
            </button>
            <button type="button" onClick={onDiscardSavedAssessment} className="rounded-xl border border-white/15 px-4 py-2 text-sm text-white/72">
              Start over
            </button>
          </div>
        </div>
      )}

      <div className="pt-8 text-center md:pt-10">
        <p className="text-4xl font-semibold tracking-[0.12em] text-white md:text-5xl">
          MOREMINDMAP
        </p>
        <h1 className="mx-auto mt-5 max-w-3xl text-3xl font-semibold leading-tight tracking-tight text-white md:text-5xl">
          Build the profile that explains how you operate.
        </h1>
        <p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-white/64 md:text-lg">
          A premium Behavior Operating System profile for how you think, communicate, decide, lead,
          and respond under pressure.
        </p>
      </div>

      <div className="mt-10 grid gap-6 lg:grid-cols-2 lg:items-stretch">
        <div className="relative overflow-hidden rounded-[2rem] border border-white/12 bg-[#101114] p-6 shadow-[0_24px_90px_rgba(0,0,0,0.4)] md:p-8">
          <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_70%_0%,rgba(56,189,248,0.14),transparent_34%),linear-gradient(145deg,rgba(255,255,255,0.075),transparent_46%)]" />
          <div className="relative">
            <div className="flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-start sm:justify-between">
              <div>
                <p className="text-xl font-semibold text-white">Full MORE MindMap Profile</p>
                <div className="mt-4 flex items-end gap-3">
                  <span className="text-5xl font-semibold tracking-tight text-white md:text-6xl">$149</span>
                  <span className="pb-2 text-sm font-medium text-white/45">One profile</span>
                </div>
              </div>
              <button
                type="button"
                onClick={() => setSelectedOffer("mini_profile")}
                className={[
                  "rounded-full border px-4 py-2 text-xs font-bold uppercase tracking-[0.16em] transition",
                  selectedOffer === "mini_profile"
                    ? "border-cyan-200/70 bg-cyan-300/[0.14] text-cyan-50"
                    : "border-white/18 bg-white/[0.06] text-white/66 hover:border-white/38 hover:text-white"
                ].join(" ")}
              >
                {selectedOffer === "mini_profile" ? "Selected" : "Select Profile"}
              </button>
            </div>

            <p className="mt-6 text-base font-semibold leading-7 text-white">
              Understand how you think, communicate, decide, lead, and operate under pressure.
            </p>

            <div className="mt-6 grid gap-3 sm:grid-cols-2">
              {featureList.map((feature) => (
                <div key={feature} className="flex items-start gap-3 text-sm leading-6 text-white/72">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan-200/80" />
                  <span>{feature}</span>
                </div>
              ))}
            </div>

            <div className="mt-8 space-y-4 border-t border-white/10 pt-6">
              <label className="block">
                <div className="mb-2 text-sm font-medium text-white/62">Your Name</div>
                <input
                  value={fullName}
                  onChange={(e) => setFullName(e.target.value)}
                  placeholder="Enter your full name"
                  className="w-full rounded-2xl border border-white/10 bg-black/[0.42] px-4 py-3.5 text-white caret-white placeholder:text-white/32 outline-none transition focus:border-cyan-200/45"
                />
              </label>
              <label className="block">
                <div className="mb-2 text-sm font-medium text-white/62">Email</div>
                <input
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email"
                  className="w-full rounded-2xl border border-white/10 bg-black/[0.42] px-4 py-3.5 text-white caret-white placeholder:text-white/32 outline-none transition focus:border-cyan-200/45"
                />
              </label>
            </div>

            <button
              type="button"
              onClick={() => onStart()}
              disabled={!fullName.trim() || !email.trim() || (!promoValidated && !selectedOffer) || checkoutLoading}
              className="mt-6 inline-flex w-full items-center justify-center rounded-2xl bg-white px-6 py-4 text-base font-semibold text-black transition hover:bg-white/90 disabled:cursor-not-allowed disabled:opacity-40"
            >
              {checkoutLoading ? "Redirecting to checkout..." : promoValidated ? "Start Assessment (Promo Active)" : "Continue to Checkout"}
            </button>

            {checkoutError && (
              <div className="mt-4 rounded-xl border border-red-400/30 bg-red-500/[0.08] p-4">
                <p className="text-sm text-red-100">{checkoutError}</p>
              </div>
            )}

            {!promoValidated && !selectedOffer && fullName.trim() && email.trim() && (
              <div className="mt-4 rounded-xl border border-white/16 bg-white/[0.06] p-4">
                <p className="text-sm text-white/64">
                  Select the profile option above to continue to checkout.
                </p>
              </div>
            )}
          </div>
        </div>

        <div className="rounded-[2rem] border border-white/12 bg-[#111216] p-6 shadow-[0_24px_90px_rgba(0,0,0,0.35)] md:p-8">
          <div className="border-b border-white/10 pb-6">
            <p className="text-xl font-semibold text-white">Already have access?</p>
            <p className="mt-3 text-sm leading-6 text-white/56">
              Use an approved promo code or retrieve an existing profile by Profile ID.
            </p>
          </div>

          <div className="mt-6 space-y-7">
            <section>
              <div className="text-xs font-semibold uppercase tracking-[0.22em] text-white/42">Promo Code</div>
              <p className="mt-2 text-sm leading-6 text-white/56">
                Approved promo access lets you start without checkout.
              </p>
              {!promoValidated ? (
                <div className="mt-4 flex flex-col gap-3 sm:flex-row">
                  <input
                    type="text"
                    value={promoCode}
                    onChange={(e) => setPromoCode(e.target.value)}
                    placeholder="Enter promo code"
                    className="flex-1 rounded-2xl border border-white/10 bg-black/[0.42] px-4 py-3.5 text-white caret-white placeholder:text-white/32 outline-none uppercase transition focus:border-cyan-200/45"
                  />
                  <button
                    onClick={validatePromoCode}
                    disabled={!promoCode.trim()}
                    className="rounded-2xl border border-white/15 bg-white/[0.06] px-6 py-3.5 text-sm font-medium text-white transition hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    Validate
                  </button>
                </div>
              ) : (
                <div className="mt-4 rounded-2xl border border-green-400/28 bg-green-400/10 p-4">
                  <div className="text-xs uppercase tracking-[0.22em] text-green-200">Promo Code Active</div>
                  <div className="mt-1 text-sm text-white">{promoCode.trim().toUpperCase()} - Full Profile unlocked</div>
                </div>
              )}
            </section>

            <section className="border-t border-white/10 pt-7">
              <div className="text-xs font-semibold uppercase tracking-[0.22em] text-white/42">Profile ID Retrieval</div>
              <p className="mt-2 text-sm leading-6 text-white/56">
                Regenerate a saved report without retaking the assessment.
              </p>
              <div className="mt-4 flex flex-col gap-3 sm:flex-row">
                <input
                  type="text"
                  value={profileId}
                  onChange={(e) => setProfileId(e.target.value)}
                  placeholder="MM-20260523-xxxxxxx"
                  className="flex-1 rounded-2xl border border-white/10 bg-black/[0.42] px-4 py-3.5 font-mono text-sm text-white caret-white placeholder:text-white/32 outline-none transition focus:border-cyan-200/45"
                />
                <button
                  onClick={validateProfileId}
                  disabled={!profileId.trim() || profileIdLoading}
                  className="whitespace-nowrap rounded-2xl border border-white/15 bg-white/[0.06] px-6 py-3.5 text-sm font-medium text-white transition hover:bg-white/10 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  {profileIdLoading ? "Loading..." : "Validate"}
                </button>
              </div>

              {profileIdError && (
                <div className="mt-3 rounded-xl border border-red-500/30 bg-red-500/10 p-3">
                  <p className="text-sm text-red-300">{profileIdError}</p>
                </div>
              )}
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}

/* ── Question Screen ── */

function QuestionScreen({
  step,
  total,
  progress,
  question,
  selectedKey,
  onSelect,
  onNext,
  onBack,
  isFirst,
  isLast,
}) {
  // Determine question type and handle accordingly
  const questionType = question.type
  const hasAnswers = question.answers && question.answers.length > 0
  const answerOptions = question.answers || question.options || []

  // Determine if answer is complete for this type
  let isAnswered = false
  if (questionType === "single_choice") {
    isAnswered = !!selectedKey
  } else if (questionType === "choose_two") {
    isAnswered = Array.isArray(selectedKey) && selectedKey.length === 2
  } else if (questionType === "ranking") {
    isAnswered = Array.isArray(selectedKey) && selectedKey.length === answerOptions.length
  } else if (questionType === "written_response") {
    isAnswered = selectedKey && typeof selectedKey === "string" && selectedKey.trim().length > 0
  }

  return (
    <div className="space-y-8">
      <a
        href="/"
        className="inline-flex items-center text-sm text-white/60 hover:text-white transition"
      >
        ← Back to Home
      </a>

      <div className="rounded-[2rem] border border-white/10 bg-white/5 backdrop-blur-md p-8 md:p-10 shadow-2xl shadow-black/30">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <div className="text-xs uppercase tracking-[0.22em] text-white/45">Assessment in progress</div>
            <h1 className="mt-3 text-2xl md:text-3xl font-semibold tracking-tight">
              Question {step + 1} of {total}
            </h1>
          </div>
          <div className="text-sm text-white/55">{progress}% complete</div>
        </div>

        <div className="mt-6 h-2 w-full rounded-full bg-white/10 overflow-hidden">
          <div
            className="h-full rounded-full bg-white transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>

        <div className="mt-10">
          <h2 className="text-lg md:text-xl font-medium leading-relaxed max-w-3xl">
            {question.question || question.prompt}
          </h2>

          <div className="mt-6">
            {/* SINGLE CHOICE */}
            {questionType === "single_choice" && hasAnswers && (
              <div className="space-y-3">
                {answerOptions.map((opt) => (
                  <button
                    key={opt.key}
                    onClick={() => onSelect(opt.key)}
                    className={[
                      "w-full text-left rounded-[1.25rem] border px-5 py-4 transition duration-200",
                      selectedKey === opt.key
                        ? "border-white/40 bg-white/[0.12] text-white"
                        : "border-white/10 bg-white/[0.03] text-white/70 hover:bg-white/[0.06] hover:border-white/20",
                    ].join(" ")}
                  >
                    <span className="text-white/40 font-medium mr-3">{opt.key}.</span>
                    {opt.text}
                  </button>
                ))}
              </div>
            )}

            {/* CHOOSE TWO */}
            {questionType === "choose_two" && hasAnswers && (
              <div className="space-y-3">
                <p className="text-sm text-white/50 mb-4">Select exactly 2 options</p>
                {answerOptions.map((opt) => {
                  const isSelected = Array.isArray(selectedKey) && selectedKey.includes(opt.key)
                  return (
                    <button
                      key={opt.key}
                      onClick={() => {
                        const current = Array.isArray(selectedKey) ? [...selectedKey] : []
                        if (current.includes(opt.key)) {
                          onSelect(current.filter((k) => k !== opt.key))
                        } else if (current.length < 2) {
                          onSelect([...current, opt.key])
                        }
                      }}
                      className={[
                        "w-full text-left rounded-[1.25rem] border px-5 py-4 transition duration-200",
                        isSelected
                          ? "border-white/40 bg-white/[0.12] text-white"
                          : "border-white/10 bg-white/[0.03] text-white/70 hover:bg-white/[0.06] hover:border-white/20",
                      ].join(" ")}
                    >
                      <span className="text-white/40 font-medium mr-3">{opt.key}.</span>
                      {opt.text}
                    </button>
                  )
                })}
              </div>
            )}

            {/* RANKING */}
            {questionType === "ranking" && hasAnswers && (
              <div className="space-y-3">
                <p className="text-sm text-white/50 mb-4">Click in order (1st, 2nd, 3rd, 4th)</p>
                {!Array.isArray(selectedKey) ? (
                  answerOptions.map((opt) => (
                    <button
                      key={opt.key}
                      onClick={() => onSelect([opt.key])}
                      className="w-full text-left rounded-[1.25rem] border border-white/10 bg-white/[0.03] px-5 py-4 text-white/70 hover:bg-white/[0.06] hover:border-white/20 transition duration-200"
                    >
                      <span className="text-white/40 font-medium mr-3">{opt.key}.</span>
                      {opt.text}
                    </button>
                  ))
                ) : (
                  <div className="space-y-3">
                    {selectedKey.map((key, rank) => {
                      const opt = answerOptions.find((o) => o.key === key)
                      return (
                        <div
                          key={key}
                          className="w-full rounded-[1.25rem] border border-white/40 bg-white/[0.12] px-5 py-4 text-white flex justify-between items-center"
                        >
                          <span>
                            <span className="text-white/40 font-medium mr-3">{rank + 1}.</span>
                            {opt?.text}
                          </span>
                          <button
                            onClick={() => {
                              const updated = selectedKey.filter((k) => k !== key)
                              onSelect(updated.length > 0 ? updated : null)
                            }}
                            className="text-white/50 hover:text-white transition"
                          >
                            ✕
                          </button>
                        </div>
                      )
                    })}
                    {selectedKey.length < answerOptions.length && (
                      <div className="space-y-2">
                        <p className="text-xs text-white/40 mt-4">Remaining options:</p>
                        {answerOptions
                          .filter((o) => !selectedKey.includes(o.key))
                          .map((opt) => (
                            <button
                              key={opt.key}
                              onClick={() => onSelect([...selectedKey, opt.key])}
                              className="w-full text-left rounded-[1.25rem] border border-white/10 bg-white/[0.03] px-5 py-4 text-white/70 hover:bg-white/[0.06] hover:border-white/20 transition duration-200"
                            >
                              <span className="text-white/40 font-medium mr-3">{opt.key}.</span>
                              {opt.text}
                            </button>
                          ))}
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* WRITTEN RESPONSE */}
            {questionType === "written_response" && (
              <textarea
                value={selectedKey || ""}
                onChange={(e) => onSelect(e.target.value)}
                placeholder="Write your response here... (min. 10 characters)"
                className="w-full rounded-[1.25rem] border border-white/10 bg-black/40 px-5 py-4 text-white placeholder:text-white/30 outline-none focus:border-white/25 resize-none"
                rows={6}
              />
            )}

            {/* FALLBACK: No question type matched */}
            {!["single_choice", "choose_two", "ranking", "written_response"].includes(questionType) && (
              <div className="rounded-[1rem] border border-white/10 bg-white/[0.05] px-4 py-3 text-white/60 text-sm">
                Unable to render question type: {questionType}
              </div>
            )}
          </div>
        </div>

        <div className="mt-8 flex flex-col sm:flex-row gap-4 sm:justify-between">
          <button
            onClick={onBack}
            disabled={isFirst}
            className="inline-flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 px-5 py-3.5 text-sm font-medium text-white hover:bg-white/10 transition disabled:opacity-30 disabled:cursor-not-allowed"
          >
            Back
          </button>

          <button
            onClick={onNext}
            disabled={!isAnswered}
            className="inline-flex items-center justify-center rounded-2xl bg-white text-black px-6 py-3.5 text-sm font-medium hover:bg-white/90 transition disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {isLast ? "Submit Assessment" : "Next Question"}
          </button>
        </div>
      </div>
    </div>
  )
}

/* ── Truthful BOS generation journey ── */

export function BosGenerationWaitingScreen({ journey }) {
  const currentStatus = journey?.message || 'Securely saving your completed answers.'

  return (
    <section
      className="space-y-8 rounded-[2rem] border border-white/15 bg-white/[0.07] p-8 text-center shadow-2xl shadow-black/30 backdrop-blur-md md:p-14"
      role="status"
      aria-live="polite"
      data-testid="bos-generation-waiting-screen"
    >
      <div className="inline-flex items-center rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-semibold uppercase tracking-[0.22em] text-white/65">
        BOS generation in progress
      </div>

      <div className="mx-auto max-w-2xl space-y-5">
        <h1 className="text-3xl font-semibold tracking-tight md:text-5xl">
          We’re creating your Behavioral Operating System.
        </h1>
        <p className="text-lg font-medium text-white/88 md:text-xl">
          Please keep this screen open.
        </p>
        <p className="text-base leading-relaxed text-white/65 md:text-lg">
          Creating your BOS involves a detailed analysis and may take up to 10 minutes.
          You do not need to submit your answers again.
        </p>
      </div>

      <div className="mx-auto max-w-xl rounded-2xl border border-white/10 bg-black/25 px-5 py-4 text-left">
        <p className="text-[0.68rem] font-semibold uppercase tracking-[0.2em] text-white/45">
          Current confirmed status
        </p>
        <p className="mt-2 text-base text-white/80" data-testid="bos-generation-confirmed-status">
          {currentStatus}
        </p>
      </div>

      <div className="flex justify-center" aria-hidden="true">
        <LoadingDots />
      </div>

      <div className="mx-auto max-w-2xl border-t border-white/10 pt-6 text-left">
        <p className="font-semibold text-white">When your BOS opens, save your Profile ID.</p>
        <p className="mt-2 text-sm leading-relaxed text-white/58 md:text-base">
          It starts with mm and is your MORE reference number for retrieving your profile and
          continuing through MORE MindMap. It is not a password, and the ID alone does not prove
          ownership; existing access verification still applies.
        </p>
      </div>
    </section>
  )
}

export function ProfileIdentityCustody({ profileId, offerRecruitingContinuation = false }) {
  const [copyState, setCopyState] = useState('idle')
  const normalizedProfileId = String(profileId || '').trim()

  async function copyProfileId() {
    if (!normalizedProfileId || typeof navigator === 'undefined' || !navigator.clipboard?.writeText) {
      setCopyState('unavailable')
      return
    }

    try {
      await navigator.clipboard.writeText(normalizedProfileId)
      setCopyState('copied')
    } catch {
      setCopyState('unavailable')
    }
  }

  return (
    <section
      className="rounded-[2rem] border-2 border-emerald-300/45 bg-emerald-300/[0.08] p-7 shadow-[0_0_60px_rgba(110,231,183,0.08)] md:p-10"
      aria-labelledby="profile-id-custody-title"
      data-testid="profile-id-custody"
    >
      <p className="text-xs font-bold uppercase tracking-[0.22em] text-emerald-200">
        Save this now
      </p>
      <h2 id="profile-id-custody-title" className="mt-3 text-2xl font-semibold tracking-tight md:text-3xl">
        Your Profile ID is your MORE reference number.
      </h2>
      <p className="mt-3 max-w-2xl text-sm leading-relaxed text-white/65 md:text-base">
        It starts with mm. Save it so you can retrieve this profile and continue through MORE MindMap.
      </p>

      <div className="mt-6 flex flex-col gap-3 rounded-2xl border border-white/15 bg-black/35 p-4 sm:flex-row sm:items-center sm:justify-between">
        <code className="select-all break-all text-lg font-semibold tracking-[0.05em] text-white md:text-xl" data-testid="ready-profile-id">
          {normalizedProfileId}
        </code>
        <button
          type="button"
          onClick={copyProfileId}
          className="shrink-0 rounded-xl bg-white px-5 py-3 text-sm font-bold text-black transition hover:bg-white/90"
          data-testid="copy-profile-id"
        >
          {copyState === 'copied' ? 'Copied' : 'Copy Profile ID'}
        </button>
      </div>

      <p className="mt-3 text-sm leading-relaxed text-white/50" aria-live="polite">
        {copyState === 'copied'
          ? 'Profile ID copied. Save it somewhere you control.'
          : copyState === 'unavailable'
            ? 'Automatic copy is unavailable. Select the Profile ID above and copy it manually.'
            : 'The ID is not a password and does not by itself prove ownership. Access verification still applies.'}
      </p>

      {offerRecruitingContinuation && (
        <div className="mt-7 border-t border-emerald-200/15 pt-7">
          <p className="text-sm leading-relaxed text-white/65">
            Your completed BOS is connected to this recruiting invitation, so you do not need to enter
            the Profile ID again for the next step.
          </p>
          <a
            href="/recruiting/continue"
            className="mt-4 inline-flex w-full items-center justify-center rounded-2xl bg-emerald-200 px-6 py-4 text-base font-bold text-black transition hover:bg-emerald-100 sm:w-auto"
            data-testid="continue-complimentary-business-assessment"
          >
            Continue to your complimentary Business Assessment
          </a>
        </div>
      )}
    </section>
  )
}

/* ── Loading Dots ── */

function LoadingDots() {
  return (
    <div className="flex gap-2">
      <style>{`
        @keyframes dotPulse {
          0%, 80%, 100% { opacity: 0.2; transform: scale(0.8); }
          40% { opacity: 1; transform: scale(1); }
        }
      `}</style>
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          className="h-3 w-3 rounded-full bg-white"
          style={{ animation: `dotPulse 1.4s ease-in-out ${i * 0.16}s infinite` }}
        />
      ))}
    </div>
  )
}

/* ── Background ── */

function ProfileBackground() {
  return (
    <div className="pointer-events-none absolute inset-0 overflow-hidden">
      <style>{`
        @keyframes driftSlow {
          0% { transform: translate3d(-2%, 0, 0) scaleX(1.02); }
          50% { transform: translate3d(2%, 0, 0) scaleX(0.99); }
          100% { transform: translate3d(-2%, 0, 0) scaleX(1.02); }
        }
        @keyframes glowPulse {
          0% { opacity: 0.08; }
          50% { opacity: 0.16; }
          100% { opacity: 0.08; }
        }
      `}</style>

      <div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_20%,rgba(255,255,255,0.07),transparent_24%),radial-gradient(circle_at_82%_70%,rgba(255,255,255,0.05),transparent_28%)]" />

      <svg
        viewBox="0 0 1600 900"
        className="absolute inset-x-[-10%] bottom-[-5%] h-[55%] w-[120%] opacity-50"
        preserveAspectRatio="none"
        style={{ animation: 'driftSlow 20s ease-in-out infinite' }}
      >
        <defs>
          <linearGradient id="profileWave" x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stopColor="rgba(255,255,255,0)" />
            <stop offset="24%" stopColor="rgba(255,255,255,0.16)" />
            <stop offset="50%" stopColor="rgba(255,255,255,0.9)" />
            <stop offset="76%" stopColor="rgba(255,255,255,0.16)" />
            <stop offset="100%" stopColor="rgba(255,255,255,0)" />
          </linearGradient>
        </defs>

        {Array.from({ length: 18 }).map((_, i) => (
          <path
            key={i}
            d={`M -100 ${440 + i * 11} C 170 ${560 - i * 3}, 420 ${285 + i * 5}, 740 ${398 + i * 1} S 1220 ${560 - i * 4}, 1710 ${390 + i * 2}`}
            stroke="url(#profileWave)"
            strokeWidth={1.05}
            strokeOpacity={0.95 - i * 0.04}
            fill="none"
          />
        ))}
      </svg>

      <div
        className="absolute left-[16%] top-[18%] h-40 w-40 rounded-full bg-white blur-[110px]"
        style={{ animation: 'glowPulse 8s ease-in-out infinite' }}
      />
      <div
        className="absolute right-[12%] bottom-[18%] h-56 w-56 rounded-full bg-white blur-[150px]"
        style={{ animation: 'glowPulse 10s ease-in-out infinite' }}
      />

      <div className="absolute inset-0 bg-gradient-to-b from-black/10 via-black/15 to-black/65" />
    </div>
  )
}
