import { Buffer } from 'node:buffer';
import { randomBytes, randomUUID, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { digest, requireValue } from './repository.js';
import { ageOn, resolveInstitution } from './config.js';
const scrypt = promisify(scryptCallback);
const token = () => randomBytes(32).toString('hex');
export const emailKey = email => `email:${digest(email)}`;
export const normalizeEmail = value => { const e=String(value||'').trim().toLowerCase(); requireValue(e.length<=254 && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e),'VALID_EMAIL_REQUIRED'); return e; };
export async function passwordHash(password) { requireValue(typeof password==='string' && password.length>=12 && password.length<=256,'PASSWORD_12_CHARACTERS_REQUIRED'); const salt=token(); const key=await scrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024}); return `${salt}:${key.toString('hex')}`; }
async function matches(password, encoded) { if(typeof password!=='string'||password.length>256)return false; const [salt,expected]=encoded.split(':');const key=await scrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024});return timingSafeEqual(key,Buffer.from(expected,'hex')); }
export const publicAccount = a => a ? {id:a.id,displayName:a.displayName,email:a.email,verified:a.verified,mm:a.mm,role:a.role} : null;
export function createAuth({repo,config,now=Date.now}) {
 const sessionKey=t=>`session:${digest(t)}`;
 const event=(type,actor,extra={})=>({id:randomUUID(),type,actor,at:new Date(now()).toISOString(),...extra});
 async function limited(key,limit=12,window=900000){await repo.transact([`rate:${digest(key)}`],s=>{const k=Object.keys(s)[0],r=s[k]&&s[k].until>now()?s[k]:{count:0,until:now()+window};requireValue(r.count<limit,'PLEASE_WAIT_BEFORE_TRYING_AGAIN',429);r.count++;return {writes:{[k]:r},result:true};});}
 async function session(raw) {if(!raw||!/^[a-f0-9]{64}$/.test(raw))return null;const saved=await repo.read(sessionKey(raw));if(!saved||saved.expiresAt<now()||saved.revoked)return null;const a=saved.accountId?await repo.read(`account:${saved.accountId}`):null;if(saved.accountId&&(!a||a.sessionVersion!==saved.version))return null;return {...saved,account:a};}
 async function createSession(account=null){const raw=token(),s={accountId:account?.id||null,version:account?.sessionVersion||0,csrf:token(),expiresAt:now()+(account?7*86400000:3600000),createdAt:now()};await repo.putImmutable(sessionKey(raw),s);return {raw,session:{...s,account}};}
 async function revokeSession(raw){if(!raw)return;const k=sessionKey(raw);await repo.transact([k],s=>({writes:s[k]?{[k]:{...s[k],revoked:true}}:{},result:true}));}
 async function logout(raw){if(!raw)return;const k=sessionKey(raw),prior=await repo.read(k);if(!prior)return;const ak=prior.accountId?`account:${prior.accountId}`:null;await repo.transact([k,...(ak?[ak]:[])],s=>{const writes={[k]:{...s[k],revoked:true}};if(ak&&s[ak])writes[ak]={...s[ak],sessionVersion:s[ak].sessionVersion+1};return {writes,result:true};});}
 function validProfile(body){const email=normalizeEmail(body.email),age=ageOn(body.dateOfBirth,now());requireValue(body.region==='US-CA'&&age>=17&&age<=120,'PILOT_CALIFORNIA_17_PLUS');requireValue(typeof body.displayName==='string'&&body.displayName.trim().length>=2&&body.displayName.length<=100,'NAME_REQUIRED');requireValue(typeof body.sport==='string'&&body.sport.trim().length>0&&body.sport.length<=120,'SPORT_REQUIRED');return {email,age};}
 function queueMail(queue,id){const q=queue||{ids:[]};requireValue(q.ids.length<10000,'EMAIL_QUEUE_BUSY',503);return {ids:[...q.ids,id]};}
 function mailRecord(id,email,kind,raw,extra={}) {return {id,email,kind,token:raw,status:'pending',attempts:0,createdAt:now(),expiresAt:now()+86400000,...extra};}
 async function signup(body){const {email,age}=validProfile(body);requireValue(!config.syntheticPreview||email.endsWith('@test.invalid'),'LOCAL_REVIEW_USE_TEST_EMAIL');await limited(`signup:${email}`,3,86400000);requireValue(config.mailEnabled,'EMAIL_SERVICE_UNAVAILABLE',503);const membership=body.institutionCode?resolveInstitution(config,{institutionId:body.institutionId,code:body.institutionCode}):null;const hash=await passwordHash(body.password),id=randomUUID(),mm=`MM-${new Date(now()).toISOString().slice(0,10).replaceAll('-','')}-${randomBytes(4).toString('hex').toUpperCase()}`,raw=token(),mailId=randomUUID(),ek=emailKey(email),ak=`account:${id}`,tk=`token:${digest(raw)}`,mk=`mail:${mailId}`,dk=`dossier:${mm}`;
 const account={id,email,passwordHash:hash,displayName:body.displayName.trim(),dateOfBirth:body.dateOfBirth,region:body.region,sport:body.sport.trim(),pronouns:String(body.pronouns||'').slice(0,80),verified:false,mm,role:'participant',sessionVersion:1,securityVersion:1,pendingMembership:membership,createdAt:now()};
 const person={name:account.displayName,dateOfBirth:account.dateOfBirth,age,sport:account.sport,pronouns:account.pronouns,mm};
 const dossier={mm,synthetic:config.syntheticPreview===true,ownerId:id,revision:0,person,memberships:[],entitlements:{bos:false,apa:false,coach:false},participation:{status:age<18?'guardian_required':'self_authorized',policyVersion:config.reviewedPolicyVersion},intake:{bos:{revision:0,answers:[],complete:false},apa:{revision:0,answers:[],complete:false}},reports:{bos:null,apa:null},jobs:[],events:[event('account_created',id)],createdAt:now()};
 const created=await repo.transact([ek,ak,tk,mk,dk,'queue:mail'],s=>{if(s[ek])return {writes:{},result:false};requireValue(!s[dk],'ACCOUNT_CANNOT_BE_CREATED',409);return {writes:{[ek]:{id},[ak]:account,[dk]:dossier,[tk]:{kind:'verify_email',accountId:id,email,expiresAt:now()+86400000,used:false},[mk]:mailRecord(mailId,email,'verify_email',raw),'queue:mail':queueMail(s['queue:mail'],mailId)},result:true};});return {verificationRequired:true,...(created?{mailId}:{})};}
 async function verifyEmail(raw){requireValue(/^[a-f0-9]{64}$/.test(raw||''),'LINK_INVALID');const tk=`token:${digest(raw)}`,first=await repo.read(tk);requireValue(first?.kind==='verify_email','LINK_INVALID');const ak=`account:${first.accountId}`,a=await repo.read(ak),dk=`dossier:${a.mm}`;await repo.transact([tk,ak,dk],s=>{const t=s[tk];requireValue(t&&!t.used&&t.expiresAt>now(),'LINK_EXPIRED_OR_USED');const account=s[ak],d=s[dk];account.verified=true;if(account.pendingMembership){d.memberships=[{...account.pendingMembership,status:'active',at:now()}];d.entitlements={bos:true,apa:true,coach:true};account.pendingMembership=null;}d.revision++;d.events.push(event('email_verified',account.id));return {writes:{[tk]:{...t,used:true},[ak]:account,[dk]:d},result:true};});return {verified:true};}
 async function login(body){const email=normalizeEmail(body.email);await limited(`login:${email}`,10);const ref=await repo.read(emailKey(email)),a=ref?await repo.read(`account:${ref.id}`):null;const dummy='0'.repeat(64)+':'+ '0'.repeat(128);const correct=await matches(body.password,a?.passwordHash||dummy);requireValue(a&&correct,'EMAIL_OR_PASSWORD_NOT_RECOGNIZED',401);requireValue(a.verified,'VERIFY_EMAIL_FIRST',403);if(body.institutionCode)await redeem(a,body);return createSession(a);}
 async function redeem(a,body){const member=resolveInstitution(config,{institutionId:body.institutionId,code:body.institutionCode}),dk=`dossier:${a.mm}`;return repo.transact([dk],s=>{const d=s[dk];requireValue(d?.ownerId===a.id,'NOT_FOUND',404);if(!d.memberships.some(m=>m.institutionId===member.institutionId&&m.status==='active')){d.memberships.push({...member,status:'active',at:now()});d.entitlements={bos:true,apa:true,coach:true};d.revision++;d.events.push(event('institution_enrolled',a.id,{institutionId:member.institutionId}));}return {writes:{[dk]:d},result:{enrolled:true,mm:a.mm}};});}
 async function requestVerification(body){const email=normalizeEmail(body.email);await limited(`verification:${email}`,3,3600000);requireValue(config.mailEnabled,'EMAIL_SERVICE_UNAVAILABLE',503);const ref=await repo.read(emailKey(email)),a=ref?await repo.read(`account:${ref.id}`):null;if(!a||a.verified)return {requested:true};const raw=token(),id=randomUUID(),tk=`token:${digest(raw)}`,mk=`mail:${id}`;await repo.transact([tk,mk,'queue:mail'],s=>({writes:{[tk]:{kind:'verify_email',accountId:a.id,email,expiresAt:now()+86400000,used:false},[mk]:mailRecord(id,email,'verify_email',raw),'queue:mail':queueMail(s['queue:mail'],id)},result:true}));return {requested:true,mailId:id};}
 async function requestReset(body){const email=normalizeEmail(body.email);await limited(`reset:${email}`,3,3600000);requireValue(config.mailEnabled,'EMAIL_SERVICE_UNAVAILABLE',503);const ref=await repo.read(emailKey(email));if(!ref)return {requested:true};const raw=token(),id=randomUUID(),tk=`token:${digest(raw)}`,mk=`mail:${id}`;const ak=`account:${ref.id}`;await repo.transact([ak,tk,mk,'queue:mail'],s=>({writes:{[tk]:{kind:'reset_password',accountId:ref.id,securityVersion:s[ak].securityVersion||1,expiresAt:now()+3600000,used:false},[mk]:mailRecord(id,email,'reset_password',raw,{expiresAt:now()+3600000}),'queue:mail':queueMail(s['queue:mail'],id)},result:true}));return {requested:true,mailId:id};}
 async function resetPassword(body){requireValue(/^[a-f0-9]{64}$/.test(body.token||''),'LINK_INVALID');const tk=`token:${digest(body.token)}`,t=await repo.read(tk);requireValue(t?.kind==='reset_password','LINK_INVALID');const ak=`account:${t.accountId}`,hash=await passwordHash(body.password);await repo.transact([tk,ak],s=>{requireValue(s[tk]&&!s[tk].used&&s[tk].expiresAt>now(),'LINK_EXPIRED_OR_USED');const a=s[ak];requireValue(s[tk].securityVersion===(a.securityVersion||1),'LINK_EXPIRED_OR_USED');a.passwordHash=hash;a.sessionVersion++;a.securityVersion=(a.securityVersion||1)+1;return {writes:{[tk]:{...s[tk],used:true},[ak]:a},result:true};});return {reset:true};}
 return {session,createSession,logout,revokeSession,signup,verifyEmail,login,redeem,requestReset,requestVerification,resetPassword,limited,event,token,mailRecord,queueMail};
}
